archethic-foundation/archethic-node

scripts/install.sh
Removed Docker Double Installation (line 75 to 85 were repeated)
Use TPM2-TSS Release 3.1
=> Use TPM2-TSS Release 3.1 and Minor Fixes

scripts/install.sh
Some desktop distributions do not have curl installed.
=> Added curl installation

config/prod.exs, scripts/release.sh
=> Enable systemd service

lib/archethic/bootstrap.ex, lib/archethic/bootstrap/network_init.ex, lib/archethic/utils/benchmarks/balance.ex, mix.exs
Use runtime configuration instead of compile configuration
to be able to overload the testnet genesis address and amount.
=> Fix the testnet genesis overloading on runtime

lib/archethic/self_repair/sync/beacon_summary_handler.ex, lib/archethic/self_repair/sync/beacon_summary_handler/transaction_handler.ex, mix.exs
Tries to fetch the transaction from the closest nodes, but retry until the end of the node list.
Because it's not subject to important latency here, in case of issue of sync from one node, try to load from the next one.
Fixes #92 
Fixes #83
=> Ensure to fetch missed transaction from the beacon in the self repair

config/prod.exs, lib/archethic/crypto.ex, lib/archethic/mining/pending_transaction_validation.ex, test/archethic/mining/distributed_workflow_test.exs, test/archethic/mining/pending_transaction_validation_test.exs
Enable verification of the node origin key family to avoid node on prod using software implementation.
However, an environment variable can be set to overload it.
Fixes #109
=> Verify the origin  of node public key

lib/archethic_web/controllers/api/transaction_controller.ex, lib/archethic_web/router.ex, test/archethic_web/controllers/api/transaction_controller_test.exs
Added transaction fee api for calculating and sending fee of transaction body received
Added new route for transaction fee api
Added testcases for transaction body validation
=> Add transaction fee api, fix archethic-foundation/archethic-node#196

lib/archethic_web/controllers/faucet_controller.ex, test/archethic_web/controllers/faucet_controller_test.exs
Faucet success flash now points to transaction address instead of recipient address
Added testcases for faucet controller create_transfer/2
Fixed error pattern matching in faucet controller to better detect network errors
=> Change faucet success flash link to tx URL, fix #204

lib/archethic/oracle_chain/scheduler.ex, test/archethic/oracle_chain/scheduler_test.exs
By using a Finite State Machine we are gaining more control of the
events triggered and the transitions between states.
This way we can fix the oracle chain duplication as we know how to
trigger polling events and therefore dates for the key derivation.
=> Use a FSM in the OracleChain Scheduler

config/config.exs, lib/archethic/mining/pending_transaction_validation.ex, lib/archethic_web/controllers/api/schema/transaction_data.ex, lib/archethic_web/controllers/api/transaction_payload.ex, test/archethic/mining/pending_transaction_validation_test.exs, test/archethic_web/controllers/api/transaction_payload_test.exs
In this change, we are keeping the **threshold** limit for the size of the `content` in the `data` field of the `transaction`. This means we are not allowing the content size to be greater than the configured threshold limit.
Add validation functions for the changesest `TransactionPayload` and `TransactionData` structs.
A new config line was added as follows
```elixir
config :archethic, :transaction_data_content_max_size, 3_145_728
```
Fixes #165 
Creating the content size greater than content_max_size using the LOC 
```elixir
Base.encode16(:crypto.strong_rand_bytes(4 * 1024 * 1024))
```` 
and trying to create a changeset of the transaction payload.
=> 165 transaction content max size

assets/css/app.scss, assets/css/variables.scss, config/config.exs, lib/archethic/utils.ex, lib/archethic_web/controllers/faucet_controller.ex, lib/archethic_web/faucet_rate_limiter.ex, lib/archethic_web/supervisor.ex, lib/archethic_web/templates/faucet/index.html.eex, lib/archethic_web/views/faucet_view.ex, test/archethic_web/controllers/faucet_controller_test.exs
Provide a limit for the number of faucet transactions within the period of time.
Fixes #111
The following two variables has been set in `config.exs`
```elixir
config :archethic, :faucet_rate_limit, 3
config :archethic, :faucet_rate_limit_expiry, 3_600_000
```
Make 4 faucet transactions within an hour. At present limited to only three transactions per hour. When you try to make fourth transaction, you will get a flash "Archived address" and time left to retry
- Faucet Controller Test
- I have commented on my code, particularly in hard-to-understand areas …
=> 111 faucet rate limiter

lib/archethic/crypto/keystore/shared_secrets/software_impl.ex, lib/archethic/db.ex, lib/archethic/db/embedded_impl.ex, lib/archethic/transaction_chain.ex, test/archethic/crypto/keystore/shared_secrets/software_impl_test.exs, test/support/template.ex
Because of the new DB design, the order of transaction is not desc but
asc.
So the loader had to be changed, to load the latest transaction
When you run the node after few times, when you restart it should have error of proof_of_election, due to an invalid last shared secrets tx.
Also unit tests have been update …
=> Fix the shared secret keystore loading

assets/css/app.scss, assets/js/ui.js, lib/archethic_web/templates/faucet/index.html.eex
After the implementation of the faucet's limiter, the text of the alert in case of error flow outside the banner, because
the alert size have been hard-coded.
This is a simple fix, to put the size of the faucet's  alert to 100%
Go the faucet, emit more than 3 transactions and you should see the alert taking the entire screen
- New and …
=> Fix faucet's alert width

config/test.exs, lib/archethic/p2p/geo_patch.ex, test/archethic/bootstrap_test.exs, test/archethic/p2p/geo_patch_test.exs, test/test_helper.exs
Fixes bug on GeoPatch algorithm to match the following rules : 
- first digit represent latitude patch
- second digit represent longitude patch
- third digit is a precision within the previous two digits
Fixes #253 
- Runned a script with all coordinates possibilities (2 nested loop from -90 to 90 and -180 to 180), result is 2048 distinct geo patch (16x8x16)
- Geo patch match the grid coordinates shown in issue (pos 0,0 is patch 000, pos -1,-1 is patch FFF)
- I have added …
=> Fix GeoPatch algorithm

lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations/transaction_movement.ex
This PR fixes the transaction movement issue from the `to_map` decoding of the NFT cases.
Fixes #281 
- Create an address and allocate funds through the faucet
- Create a transaction chain with NFT, with allocated funds
- Create another address for a recipient
- Create a transaction to transfer the NFT
- Go to the explorer, it should not reproduce the error of decoding
- I have added tests that prove my fix is effective or that my …
=> Fix NFT tx movement decoding

lib/archethic/db/embedded_impl/encoding.ex
Fix problem of decoding of nested list fields due to a problem of range
Go the `/api/graphiql`, and run the `transactions` query with list of fields like:
- crossValidationStamps
- ownerships
- unspentOutputs
- transactionMovements
- recipients
=> Fix DB decoding of nested list

lib/archethic/mining/distributed_workflow.ex
This PR aims to help to identify errors by logging through errors the unexpected behaviors.
Before the mining unexpected messages were ignored causing troubles to identify faults.
=> improve mining error handling

lib/archethic/beacon_chain/summary_timer.ex, lib/archethic/self_repair/sync.ex, lib/archethic/self_repair/sync/beacon_aggregate.ex, lib/archethic/self_repair/sync/beacon_summary_handler.ex, lib/mix/tasks/clean_db.ex, test/archethic/beacon_chain/summary_timer_test.exs
This PR fixes the ordering of transaction during synchronization of the missed transactions in the self-repair when a node joins after some time of network liveness.
The issue resolved is not present on docker-compose or local node environment, but only when a node joins after a first one is there for several minutes.
The issue was about the aggregation of beacon summaries
Fixes #287 
- Start a node using `iex -S mix`
- After several 5/10 min, start another using: `ARCHETHIC_P2P_PORT=3005 ARCHETHIC_HTTP_PORT=4005 ARCHETHIC_CRYPTO_SEED="node2" iex -S mix`
- The transaction should be synchronized without the `:invalid_proof_of_election` error
- My code follows the style guidelines of this …
=> Fix beacon summary aggregate

lib/archethic_web/templates/explorer/chain.html.eex
Fix the formatting of the UCO in the explorer, specifically in the chain UI .
Fixes #295 
- Go the faucet at: http://localhost:4000/faucet and send funds to an address
- Go the chain explorer: http://localhost:4000/explorer/chain?address={youraddress}
- You should see 100.0 UC0 instead of 10000000000
- New and existing unit tests pass locally with my …
=> Format UCO's amount in the chain UI

lib/archethic/utils/regression/playbook.ex
Correction of a bug in benchmark where the origin private key was still hardcoded and not asked threw the API
Runned benchmark without error
=> Correct playbook origin key error

.github/workflows/ci.yml, .gitignore, mix.exs, test/archethic/beacon_chain_test.exs, test/archethic/bootstrap/sync_test.exs, test/archethic/oracle_chain/scheduler_test.exs, test/archethic/self_repair/sync/beacon_summary_handler_test.exs, test/archethic/shared_secrets/node_renewal_scheduler_test.exs
Improve caching datas in Github Actions to reduce test time, add `MIX_ENV=test` to compile code once (previously code was compiled two times), update some test files to not set the state name to avoid test error (state already started).
Fixes #302 
Runned Github actions on a test branch, the result is a test time 3x faster : 
Before : 
After : 
- New and existing unit tests pass locally with my …
=> Improve GitHub actions duration

lib/archethic/p2p/message.ex
Correction of a bug occuring in CrossValidate message :
`MatchError) no match of right hand side value: <<192, 6::size(4)>>
(archethic 0.14.0) lib/archethic/p2p/message.ex:653: Archethic.P2P.Message.decode/1`
Error is reproductible by this way : 
Start node1 and node2 -> everything is going well
Start node3 -> node3 goes in pending
When node3 goes in pending, node1 send a CrossValidate message to node2 and then here is the error on node2 side
Do not have Github issue for this error
Run 3 nodes as described before, and there is no more error …
=> Correct CrossValidate message error

lib/archethic/crypto.ex, lib/archethic/crypto/keystore/shared_secrets/software_impl.ex, lib/archethic/p2p/mem_table_loader.ex, test/archethic/p2p/mem_table_loader_test.exs
This PR fixes the invalid authorization nodes list when validation are churning (leave and join)
Fixes #315 
- Start a node: `iex -S mix`
- Start another node: `ARCHETHIC_CRYPTO_SEED="node2" ARCHETHIC_HTTP_PORT=4003 ARCHETHIC_P2P_PORT=3003 iex -S mix`
- Wait the second node to become authorized node
- Stop the second node
- Restart the second node
Then we should not have error regarding election of nodes  …
=> Fix chunk authorized nodes issue

lib/archethic.ex, lib/archethic_web/graphql_schema.ex, lib/archethic_web/graphql_schema/page_type.ex, lib/archethic_web/graphql_schema/resolver.ex, test/archethic_web/controllers/api/transaction_controller_test.exs, test/archethic_web/graphql_schema_test.exs
Before this change, to get the specific page level transaction_chain, we are loading whole transactions and slicing them by the page size and retrieving the relevant page transactions. 
In this change, the `page` attribute which was `number` now converted to `pagingAddress` of type `string` is now the address of the last transaction in the page which act as a `paginate_state` for next page.
Here, we are loading specific `paging_state` based page size transactions only. 
Fixes #297 #296 
1. Select the address whose chain length is greater 10 for an …
=> 297 Pagination based on paging_state as last page last transaction address GraphQl API

lib/archethic/replication.ex, lib/archethic/self_repair/sync/beacon_summary_handler/transaction_handler.ex
An UTXO error was provided during self repair when encounter a transfer transaction which was the first transaction of the chain.
Reproduce it : 
- Launch a node and make a transaction from faucet
- Launch a second node, and `[error] Invalid unspent outputs` will raise during self repair
Run both nodes without error
- Any dependent changes …
=> Correct self repair utxo error

.iex.exs, rel/commands/regression_test, scripts/release.sh, test/archethic/governance/0001-CI-Pass.patch
Fix a bug of module name from ArchEthic to Archethic.
While using `mix dev.bench` to run benchmark with docker, it calls module ArchEthic... which do not exists
Launch command `mix dev.bench` and docker container run bench without error
=> Fix renaming of ArchEthic to Archethic

lib/archethic/db/embedded_impl/chain_index.ex, lib/archethic/db/embedded_impl/chain_reader.ex, lib/archethic/p2p/message.ex, lib/archethic/p2p/message/get_transaction_chain.ex, lib/archethic/reward.ex, test/archethic/db/embedded_impl_test.exs, test/archethic/p2p/messages_test.exs
Fix bugs during self repair.
- Updated transaction storage timestamp from second to millisecond
- Updated chain reader to get transaction chain up to the address passed in parameter
Fixes #320 
Run nodes as described in issue and do not get any error
=> Self repair on transfert transaction

lib/archethic/db/embedded_impl/chain_index.ex, lib/archethic/db/embedded_impl/chain_reader.ex, lib/archethic/db/embedded_impl/chain_writer.ex
Add telemetry at Methods under
- ChainWriter
- get_transaction
- get_transaction_chain
- Chain Reader
- index_transaction
- write_transacton
Resolves # (#327  )
- visit localhost/metrics to see exported telemetry
=> Resolves Add telemetry for embedded database#327

lib/archethic/beacon_chain/slot.ex
Beacon slots contain `involved_nodes` which was used before, but not anymore.
So in order to simplify understanding and encoding, we can remove it.
=> Remove involved nodes in beacon slots as unused

lib/archethic/beacon_chain.ex, lib/archethic/election.ex
Beacon summary address were generated no in the same way in the codebase
So now it's more unified and would prevent bug for that matter.
=> Make summary transaction address more consistent

lib/archethic/db/embedded_impl/chain_index.ex, lib/archethic/db/embedded_impl/chain_writer.ex, test/archethic/db/embedded_impl_test.exs
Fix the set last transaction address to target the genesis right away.
Instead to perform another lookup from the previous address, use directly the genesis address from the write transaction command to specify the genesis address from this new transaction address
- Any dependent changes have been …
=> Set last transaction address from the genesis in DB

lib/archethic/beacon_chain/summary_timer.ex
Retrieval of the previous summary date from another date didn't work as expected.
This PR fixes this.
=> Fix previous_summary from summary timer

lib/archethic/beacon_chain.ex, lib/archethic/beacon_chain/subset.ex
Add the transaction slot to the summary chain by giving the genesis address (from the previous summary date) to append the transaction to.
=> Write beacon slot to summary chain

lib/archethic_web/templates/explorer/index.html.leex
Remove TopTransactionLive component in the HTML as not used for now and causing some issues sometimes.
So it's just a cleanup
=> Remove TopTransactionLive as unused for now

lib/archethic/beacon_chain/slot.ex, lib/archethic/beacon_chain/subset.ex, lib/archethic/beacon_chain/summary_timer.ex, test/archethic/beacon_chain/summary_timer_test.exs, test/archethic/beacon_chain_test.exs
Ensure a transaction notification will be handled by the right slot at the right time
If the transaction timestamp conflicts with the slot time, then we can postpone the transaction with for the next slot
=> Postponed beacon chain replication attestations when conflicts on slot/tx's time

lib/archethic/crypto.ex, lib/archethic_web/live/chains/beacon_live.ex, lib/archethic_web/templates/explorer/beacon_chain_index.html.leex
Fix the transaction loading issue in the beacon chain from the first page.
It targets the transaction chain of the current day to retrieve the beacon slots transaction and aggregate them.
Related to #291 
When a transaction is submitted and stored on the beacon chain, when the next slot is sealed and send through a transaction, when you are refreshing the first page, you should be able to see the transaction and the previous ones. …
=> Fix beacon live transaction chain loading

assets/package-lock.json, lib/archethic/mining/fee.ex, test/archethic/mining/fee_test.exs, test/archethic_web/controllers/api/transaction_controller_test.exs
The transaction fee value for oracle transactions have been set with `0.01/uco_price_in_usd` 
Fixes #349 
=> Change transaction value fee to a fixed one (base fee)

config/config.exs, lib/archethic_web/controllers/api/schema/nft_ledger.ex, lib/archethic_web/controllers/api/schema/ownership.ex, lib/archethic_web/controllers/api/schema/transaction_data.ex, lib/archethic_web/controllers/api/schema/uco_ledger.ex, test/archethic_web/controllers/api/transaction_payload_test.exs
Additional Checks on Structure Changesets to validate proper lengths for following
- Ownerships
- ownership recipients
- UCOLedger transfers
- NFTLedger transfers
- recipients in a transaction
- Code Length (Fetched from the config)
Fixes #330 
Forces API to precheck the sizes which are supported by transaction encoding before serializing
- test "should return an error if the code length is more than 5 MB"
- test "should return an error if the uco ledger transfers are more than 256"
- test "should return an error if the nft ledger transfers are more than 256"
- test "should return an error if the recipients are more that 256"
- test "should return an error ownerships are more than 256."
- test "should return an error authorized …
=> Improve Transaction API validation

lib/archethic_web/templates/faucet/index.html.eex
The objective of this PR is to redirect users from Read Blog button on Faucet Page (https://testnet.archethic.net/faucet) directly to https://blog.archethic.net/introducing-archethic-testnet-faucet/ instead of https://blog.archethic.net/. 
- Change of link for **Read Blog** button.
The mentioned change has been tested manually on http://localhost:4000/faucet.
=> Fixed Read Blog link

lib/archethic_web/controllers/api/web_hosting_controller.ex
Fixes an error when uploading a single file, the file was not retrieve with the root url path.
Uploaded a single file, request the root url (without specifying the file name) and the file is returned
=> Fix single file error

config/dev.exs, config/prod.exs, config/test.exs, lib/archethic/contracts/worker.ex, lib/archethic/mining.ex, lib/archethic/oracle_chain/scheduler.ex, lib/archethic/shared_secrets/node_renewal.ex, lib/archethic/shared_secrets/node_renewal_scheduler.ex, lib/archethic/utils/detect_node_responsiveness.ex, test/archethic/utils/detect_node_responsiveness_test.exs
It detects the unresponsive nodes and resends the transaction to the next trigger next node.
Continuation of PR #376 
Fixes #338 
Test with 4 three nodes
`>ARCHETHIC_CRYPTO_SEED=node1 ARCHETHIC_P2P_PORT=3002 ARCHETHIC_HTTP_PORT=4000 iex -S mix`
`>ARCHETHIC_CRYPTO_SEED=node2 ARCHETHIC_P2P_PORT=3003 ARCHETHIC_HTTP_PORT=4001 iex -S mix`
`>ARCHETHIC_CRYPTO_SEED=node3 ARCHETHIC_P2P_PORT=3004 ARCHETHIC_HTTP_PORT=4002 iex -S mix`
`>ARCHETHIC_CRYPTO_SEED=node4 ARCHETHIC_P2P_PORT=3005 ARCHETHIC_HTTP_PORT=4003 iex -S mix`
If we stop the node1 the node shared secret transactions , oracle etc must be fall back to node2, node2 as trigger node and shall be validated.
But for me if a Node is removed …
=> Detection of unresponsive trigger node Contd of 376 

lib/archethic/db/embedded_impl/chain_reader.ex, test/archethic/db/embedded_impl_test.exs
If paging address does not exits, catch the error.
Fixes # (#398)
=> DB crashes when transaction chain not found #398

lib/archethic/beacon_chain/subset.ex, lib/archethic/p2p/message.ex, lib/archethic/pub_sub.ex, lib/archethic_web/live/chains/beacon_live.ex
we were using same pub sub for replication attestation during transaction validation which caused crash due to beacon explorer was also using the same. Now we added a separate PubSub for beacon explorer to get the transaction attestations and push it to UI 
Fixes #429 
Run 3 nodes and checked the logs, Now I don't get a lot of logger msg showing same info. And the transaction duplication is also fixed in beacon explorer
- I have …
=> Fixed multiple pub sub causing crash due to new replication attestations

lib/archethic/p2p/client.ex, lib/archethic/p2p/client/connection.ex, lib/archethic/p2p/client/default_impl.ex, lib/archethic/p2p/listener_protocol/broadway_pipeline.ex
Sometimes when a node disconnect and reconnect, the state of connection is not set to `:connected` before a node try to send message to it and so message falls in error because the node thinks that the other node is not connected.
Run 2 nodes, disconnect one and reconnect it just after, we should not see message `Cannot send message ...... :closed` after the node is reconnected
- New and existing …
=> Update client connection when receive a request

config/config.exs, lib/archethic/mining/distributed_workflow.ex, lib/archethic/mining/transaction_context.ex, lib/archethic/p2p.ex, lib/archethic/p2p/client/connection.ex, lib/archethic/p2p/message.ex, lib/archethic/replication.ex, lib/archethic/self_repair/sync.ex, lib/archethic/transaction_chain.ex, test/archethic/bootstrap/network_init_test.exs, test/archethic/bootstrap/sync_test.exs, test/archethic/bootstrap_test.exs, test/archethic/p2p/messages_test.exs, test/archethic/replication/transaction_context_test.exs, test/archethic/replication_test.exs, test/archethic/self_repair/sync/transaction_handler_test.exs, test/archethic/self_repair/sync_test.exs, test/archethic/transaction_chain_test.exs, test/archethic_test.exs, test/archethic_web/graphql_schema_test.exs
During mining process, there is several request to get a previous transaction or a the while tranaction chain.
Request and mining process have some timeout of 3sec.
But transactions can have a maximum size of 3MB and if the node connection is low (especially in upload), send 3MB can take more time than 3 sec
So to avoid te timeout behavior for low connection speed, we can dynamically adapt the timeout depending on the maximum request size expected.
Fixes poart of #425 
To simulate low connection, we can update the connection.ex file with this on line 299: 
```
time = trunc(byte_size(msg) / @floor_upload_speed * 1_000)
Process.send_after(from, {ref, {:ok, message}}, time)
```
and this in top of the file
```
@floor_upload_speed …
```
=> Improve P2P

lib/archethic/beacon_chain.ex, lib/archethic/beacon_chain/slot.ex, lib/archethic/beacon_chain/subset.ex, lib/archethic/beacon_chain/supervisor.ex, lib/archethic/beacon_chain/update.ex, lib/archethic/p2p/client/default_impl.ex, lib/archethic_web/live/chains/beacon_live.ex, test/archethic/beacon_chain/update_test.exs
Beacon explorer subscribe to other node and itself to be notified when a new replication attestation is emitted.
But the node is notified for each confirmation while it only needs one confirmation.
Beacon node also notify storage node for a transaction, storages nodes already know the transaction
Beacon explore ask for notification to a node even if it is already subscribed.
All these actions spam a lot the node and they can get overloaded.
This PR solves these issue.
Fixes part of #425 
Add some latency in connection.ex (`Process.sleep(200)`), run 3 nodes, open a beacon explorer and you should not have a lot of timeout after some time
Also added test files …
=> Improve beacon chain explorer

lib/archethic/p2p/listener_protocol/broadway_pipeline.ex
When the node receive a message, it is catched by a message producer and send to a worker. All workers can handle one message at a time, so if all workers are busy, the message producer will add new messages in a queue, waiting for worker to be freed.
The problem is that all workers process the message synchronously, and so if they are on a long processing time message, message in the queue can go on timeout.
The idea here it to create a new task that will process the message and so message workers just create this task and don't wait message processing time. They are quiclky freed to get another message
Added some log in the message producer queue.
Without modification, when the receive a lot of message, there is a lot if message in …
=> Set message processing asynchronous

lib/archethic.ex, lib/archethic/p2p/message.ex, lib/archethic/replication/transaction_context.ex, lib/archethic/transaction_chain.ex, test/archethic/beacon_chain/subset_test.exs, test/archethic/bootstrap/network_init_test.exs, test/archethic/bootstrap_test.exs, test/archethic/replication/transaction_context_test.exs, test/archethic/replication_test.exs, test/archethic/self_repair/sync/transaction_handler_test.exs, test/archethic/self_repair/sync_test.exs, test/archethic_test.exs, test/archethic_web/graphql_schema_test.exs
=> Replicate only missing transactions #443

config/prod.exs, lib/archethic/utils.ex
For production, we add a specific folder to store the database, by default to `~/aebot` instead of app dir
Fixes #461 
Runned a node with `MIX_ENV=prod iex -S mix`, `~/aebot/data` folder was created and fillled with datas
- Any dependent …
=> Update database folder for prod mode

lib/archethic/application.ex, lib/archethic/db/embedded_impl.ex, lib/archethic/p2p.ex, lib/archethic/p2p/listener_supervisor.ex, lib/archethic/p2p/supervisor.ex, lib/archethic/self_repair/scheduler.ex
This PR fixes 2 errors : 
- During replication, when retrieving the previous chain, Embedded_impl.write_transaction_chain is called, but this function do not retrieve the genesis chain if it exist to append the new transactions to the same file. And so mutuiple file was created for the same chain.
- If an authorized node disconnect and is globally unavailable, of it reconnect at the end of a cycle, it will send the en of node sync flag, but it will stay unavailable because it has not enough connection time in the cycle to be globally available. And so the synced flag stay to false.
Correction: 
- Retrieve the previous address to get the genesis addres if the chain
- Send the end of node sync flag until the node is available
Fixes #460  …
=> Fix self repair error

lib/archethic/p2p/client/connection.ex, lib/archethic/p2p/message.ex
During mining process we start a task that ping all nodes (for network transaction) but the timeout for a request start after the request has been sent. If a node is not available and the tcp request takes to much time to be sent, the connection timeout is never started and so the task falls in timeout
Fixes #469
Add latency for ping message -> we don't get the task timeout error anymore, but we have the warning that we cannot send a message to a node due to timeout
- I have …
=> Fix Task timeout error

lib/archethic/p2p/message.ex
Add a control before starting mining a transaction, to check if the transaction is not already in mining process
Fixes #459 
Added latency in mining process, and tryed to send 2 times the same request. It blocked well the second transaction
=> Add control for mining process before starting mining

lib/archethic/mining/pending_transaction_validation.ex, lib/archethic/mining/validation_context.ex, lib/archethic/reward.ex, lib/archethic/reward/scheduler.ex, lib/archethic/transaction_chain.ex, test/archethic/beacon_chain/subset_test.exs, test/archethic/reward/scheduler_test.exs, test/archethic/reward_test.exs
After the mint reward, we send to the node reward to all authorized nodes.
Fixes #382 
node reward transaction is sent after the mint reward one, or if there is no mint reward transaction to do the node reward tx is directly sent.
Add test in test files.
=> Schedule sending of reward tokens to the node reward address

lib/archethic/beacon_chain/slot_timer.ex, lib/archethic/oracle_chain/scheduler.ex, lib/archethic/reward/scheduler.ex, lib/archethic/shared_secrets/node_renewal_scheduler.ex
Problem : 
Process affected: Reward, Slot-Timer ,  Oracle Scheduler, Node_renewal_scheduler   
`-Whenever The node is  restarted and or doing a first time boot, There is a possibility that   
processes are not notified to by pub-sub :node_update message as they are not started yet,
and notification was there from P2P loading nodes.
Whenever the process crashes , during re-initialisation of the process , it must check for 
whether to schedule a :node_update message depending upon authorised or not.
It was not scheduled before
There was possibility that 
`
Fixes # (#478)
- Breaking change (fix or feature that would cause existing …
=> Schedule The Scheduler after a node boot or scheduler crash.

lib/archethic/account/mem_tables_loader.ex, lib/archethic/bootstrap/network_init.ex, lib/archethic/mining/distributed_workflow.ex, lib/archethic/mining/standalone_workflow.ex, lib/archethic/mining/validation_context.ex, lib/archethic/replication/transaction_validator.ex, lib/archethic/transaction_chain.ex, lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations.ex, lib/archethic_web/templates/explorer/transaction_details.html.leex, lib/archethic_web/views/explorer_view.ex, test/archethic/bootstrap/network_init_test.exs, test/archethic/mining/validation_context_test.exs, test/archethic/replication_test.exs, test/support/transaction_factory.ex
The fee burning has been removed from the transaction movements to remove confusion between manual token burn and the fee burning.
This allows also the display of all the transactions targeting the
burning address as included as input.
Fixes #474 
Any fee should be redirected to the burning address as input
As well, we can mention burning address as UCO transfers to burn explicitly more tokens.
- I have commented my …
=> Include UCO transfer towards burning address

lib/archethic/self_repair/notifier.ex, test/archethic/self_repair/notifier_test.exs
Trigger repair on the right P2P network change
Fixes #348 
When an authorized node is considered as unauthorized or globally offline, this means a topology change occurred, hence the notifier will repair transaction shards but proposing transactions to new storage nodes.
By disconnecting an authorized node the notifier should replicate all the transactions this node was in charge of.
Logs are also added to help to visualize the events. …
=> Correct self repair notifier

lib/archethic_web/graphql_schema/transaction_attestation.ex, lib/archethic_web/transaction_subscriber.ex
- Include New P2P message to deliver error to client.
- Include reporting of max nb of confirmations to the client
Fixes # (#456)
- Any …
=> Return fully validated transaction on Transaction Subscriber#456 #489

lib/archethic_web/transaction_subscriber.ex
Set the default max confirmations in case of the subscription happens after the transaction sending
Fixes #522 
=> Fix max confirmations

lib/archethic.ex, lib/archethic/db.ex, lib/archethic/db/embedded_impl.ex, lib/archethic/db/embedded_impl/chain_reader.ex, lib/archethic/transaction_chain.ex, test/archethic/db/embedded_impl_test.exs, test/archethic_test.exs, test/support/template.ex
Fix the transaction chain reading to make sure the chain is one expected, so bigger.
Since d244b1dad8562e8ec614c963527d3274529d24df, the chain was downloaded using a diff between local and remote fetch.
The problem being, if a local chain was bigger than the address of the chain requested (pointer) we would include more transaction than expected. And also we might cause database issues, because the pagination address was the latest one, which don't provide much transactions to load.
This fix makes sure we only download the right transactions until the desired transaction's address. …
=> Fix get transaction chain lookup

mix.exs
When we install the code repository for the first time, the priv/plts folder is not created.
Hence we should create it before to run `mix dialyzer`
Fixes #524 
Clone the repository and run `mix dialyzer`.
The `priv/plts` should be created and dialyzer run without error. …
=> Fix dialyzer plts folder creation

lib/archethic_web/graphql_schema/resolver.ex, lib/archethic_web/graphql_schema/transaction_type.ex
Provide an unique identification of a token for genesis address.
This make possible to host multiple tokens on the same chain while being able to identify them.
Fixes #503 
=> Get token id in the API

lib/archethic/beacon_chain.ex, lib/archethic/bootstrap.ex, lib/archethic/p2p/client.ex, lib/archethic/p2p/client/connection.ex, lib/archethic/p2p/client/default_impl.ex, lib/archethic/p2p/listener.ex, lib/archethic/p2p/listener_protocol.ex, test/archethic/bootstrap_test.exs
Fixe some error hapening on bootstrap :
- Start the tcp listener after the bootstrap to avoid connection and disconnection on the other nodes
- As now a node can send message but without starting the tcp listener, we remove the set_connected function as the node may not be connected
- Fix an error during self repair: if there is more dates to sync than CPU cores, some beacon summaries with different timestamp where aggregated together causing a crash on transaction loading
Launch a node and wait half an hour to let it generate more than 30 summaries.
Create some transfer transaction
Start a second node and the should load all the transaction sorted by timestamp …
=> Fix bootstrap issue

lib/archethic/oracle_chain.ex, lib/archethic/oracle_chain/mem_table.ex, lib/archethic/oracle_chain/mem_table_loader.ex, lib/archethic_web/graphql_schema.ex, lib/archethic_web/graphql_schema/datetime_type.ex, lib/archethic_web/graphql_schema/oracle_data.ex, test/archethic/oracle_chain/mem_table_loader_test.exs
Provide GraphQL API for oracles:
- Subscription of the latest changes (real time with ws)
- Get the latest value of the oracle data
- Get the oracle data at a given time
Fixes #451 
We can use the following query to get the last updates:
```graphql
subscription {
oracleUpdate {
services {
uco {
eur
}
}
}
}
```
We can get latest oracle data with:
```graphql
query {
oracleData {
timestamp
services {
uco {
eur
}
}
} 
}
```
To fetch for a given date
```graphql
query {
oracleData(timestamp: ....) {
services {
uco {
eur
}
}
} 
}
``` …
=> Add API to get last oracle value

lib/archethic_web/controllers/api/transaction_controller.ex
Feature Addition, Check on Transaction Existence before sending it for mining.
Fixes #502 
Manually Tested
=> Verify if transaction exists before validation #502

lib/archethic/bootstrap/network_init.ex, lib/archethic/oracle_chain.ex, lib/archethic/oracle_chain/scheduler.ex, lib/archethic/oracle_chain/supervisor.ex, lib/archethic/pub_sub.ex, lib/archethic/reward.ex, lib/archethic/reward/scheduler.ex, lib/archethic/shared_secrets.ex, lib/archethic/shared_secrets/node_renewal.ex, lib/archethic/shared_secrets/node_renewal_scheduler.ex, lib/archethic/transaction_chain/transaction.ex, lib/archethic/utils/regression/playbook.ex, test/archethic/oracle_chain/scheduler_test.exs, test/archethic/reward/scheduler_test.exs, test/archethic/shared_secrets/node_renewal_scheduler_test.exs, test/archethic/shared_secrets/node_renewal_test.exs
This should prevent scheduler to trigger transactions too fastly computed before the scheduling time.
Using FSM we are ensuring to enter in the state of scheduling only when the tx is replicated or after timeouts.
Fixes #420 
=> Prevent scheduling network tx

config/test.exs, lib/archethic/mining/pending_transaction_validation.ex, lib/archethic/oracle_chain.ex, lib/archethic/reward.ex, lib/archethic/shared_secrets.ex, test/archethic/mining/pending_transaction_validation_test.exs
Ensure network transactions which are scheduled to happen only once in their interval.
Fixes #421 
Start multiple nodes, at some point nodes will have different time synchronization.
Hence one might send a node shared secrets tx just after one have been already sent (until #420 is implemented)
The validation should catch it and the tx would not be validated.
- New and existing unit tests pass …
=> Verify scheduled transaction only happens once 

lib/archethic/transaction_chain/transaction/cross_validation_stamp.ex, lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations.ex, lib/archethic_web/controllers/api/transaction_controller.ex, lib/archethic_web/graphql_schema/transaction_type.ex, test/archethic/transaction_chain/transaction/cross_validation_stamp_test.exs, test/archethic_web/controllers/api/transaction_controller_test.exs
I remove Node movements object references
Commands ok:
```
mix test --trace
mix archethic.regression --playbook localhost
```
=> Clean Node movements references

lib/archethic_web/live/chains/beacon_live.ex
The beacon explorer fetches tx's locally if its not available then it fetches remote to avoid loadtime issues.
Fixes #458
Simulate latency and check the loading of tx's from local
`./comcast --device=lo --latency=200 --target-bw=1000 --packet-loss=10%
`
check device name in your machine using `ifconfig -a` and put the loopback device name in the above ci …
=> Improved beacon explorer loadtime

lib/archethic/beacon_chain.ex, lib/archethic/oracle_chain/scheduler.ex, lib/archethic/p2p/mem_table.ex, lib/archethic/reward/scheduler.ex, lib/archethic/shared_secrets/node_renewal_scheduler.ex, lib/archethic_web/controllers/api/transaction_controller.ex
Fixes some errors: 
- availability_history bit was reseted to 1 when updating avarage availability during self repair. Updated to reset the bt with it's last value
- during self repair, summaries were not downloaded if they already exists in DB, but in some case nodes don't have the same summaries and so some desynchronisation may happen. So downloading summary from all the node and doing an aggregate is a better way so all nodes have the same aggregate.
- some event sent to the scheduler were not handled causing scheduler crash.
- In transaction API, when quorum fail, no response were sent back to the user …
=> Fix availability error, local summaries download, scheduler handle event

lib/archethic/contracts.ex, lib/archethic/contracts/contract.ex, lib/archethic/contracts/interpreter.ex, lib/archethic/contracts/worker.ex, lib/archethic/utils.ex, test/archethic/contracts/worker_test.exs
Before when supplied with old Cron Specification, the extended mode was triggering SC with per seconds which is not the intended effect which is to send per minute
Fixes #540 
Manually Tested …
=> Archethic Node cron scheduler wrongly configured #540

lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations.ex
Fix a bug where the amount of token unspent outuput was not updated causing crash
Create 2 addresses and do a faucet on them
With address 1 : 
- Create a fungible token
- Send small amount of this token to address 2
- Send again small amount of this token to address 2
With address 2 : 
- Send UCO to any address, it should not crash anymore
- …
=> Fix unspent outputs amount

lib/archethic/beacon_chain/slot_timer.ex, lib/archethic/bootstrap.ex, lib/archethic/oracle_chain/scheduler.ex, lib/archethic/pub_sub.ex, lib/archethic/reward/scheduler.ex, lib/archethic/reward/supervisor.ex, lib/archethic/shared_secrets/node_renewal_scheduler.ex, mix.exs, test/archethic/beacon_chain/slot_timer_test.exs, test/archethic/beacon_chain/subset_test.exs, test/archethic/mining/pending_transaction_validation_test.exs, test/archethic/oracle_chain/scheduler_test.exs, test/archethic/reward/scheduler_test.exs, test/archethic/shared_secrets/node_renewal_scheduler_test.exs, test/archethic/utils/detect_node_responsiveness_test.exs
Scheduler must start only after post Bootstrap, So that no new next txn are sent during bootstrap .  
During crash scheduler must read arch-ethic_up  before starting.
Affected Schedulers
- Reward
- Oracle
- Node Renewal
- Slot timer
Fixes # (#543)
Logs were checked to ensure the scheduler started post Bootstrap Finished message.
explicitly killing a scheduler
Use Logs to confirm that schedulers started post bootstrap finished message.
- New and …
=> Start Schedulers Post Bootstrap  #543

lib/archethic/bootstrap.ex, test/archethic/bootstrap_test.exs, test/support/transaction_factory.ex
If there is quick disconnection and re-connection of a (authorised and available) node, it is a possibility that it will miss some oracle and node shared secrets transactions , which results in inconsistent node state.Post Bootstrap ,we must resync  nss and oracle txs so that current node state is same as other nodes state. So during validation it will not report invalid tx
Fixes # (#508 )
- Start 3 nodes, wait for all of them to get authorised.
- Shutdown one of the node.
- wait for other nodes for one or two cycle of (nss ,oc) txs.
- restart the node And look of enforced re-sync in logs.
- after quick restart of that node 
- I have …
=> Resovles:Enforce resync of last network transactions after bootstrap#508 

lib/archethic/utils/port_handler.ex
This fix reduce the memory footprint by pruning used messages when communicating with a port (external program)
=> Remove used messages tracking in the PortHandler

lib/archethic_web/controllers/faucet_controller.ex, lib/archethic_web/transaction_subscriber.ex, test/archethic_web/controllers/faucet_controller_test.exs
Fix the limitation of the faucet
Request funds more than 3 times on the same genesis address should be prevented
=> Fix faucet limitation

lib/archethic_web/graphl_context.ex, lib/archethic_web/graphql_schema.ex, lib/archethic_web/graphql_schema/p2p_type.ex, lib/archethic_web/graphql_schema/resolver.ex, lib/archethic_web/router.ex
Add GraphQL query to get the nearest list of nodes
=> Add nearest_endpoints GraphQL query

lib/archethic/beacon_chain/slot.ex, lib/archethic/beacon_chain/slot_timer.ex, lib/archethic/beacon_chain/subset.ex, lib/archethic/beacon_chain/subset/p2p_sampling.ex, lib/archethic/beacon_chain/summary.ex, lib/archethic/p2p/client.ex, lib/archethic/p2p/client/connection.ex, lib/archethic/p2p/client/default_impl.ex, lib/archethic/p2p/listener_protocol.ex, lib/archethic/utils.ex, test/archethic/beacon_chain/slot_timer_test.exs, test/archethic/beacon_chain/subset/p2p_sampling_test.exs, test/archethic/beacon_chain/subset/summary_cache_test.exs, test/archethic/beacon_chain/subset_test.exs, test/archethic/p2p/client/connection_test.exs
Implementation of the new system to calculate the availability of a node based of it's connection time
Fixes #569 
(breaking change because the first summary after the update will not work if there is already old version slot in this summary)
Tested with test files and some random deconnection / reconnection node
- I have added tests …
=> Improve node availability

.gitignore, lib/archethic/bootstrap.ex, lib/archethic/bootstrap/network_constraints.ex, lib/archethic/crypto.ex, lib/archethic/db.ex, lib/archethic/db/embedded_impl.ex, lib/archethic/db/embedded_impl/chain_index.ex, lib/archethic/mining/pending_transaction_validation.ex, lib/archethic/oracle_chain.ex, lib/archethic/reward.ex, lib/archethic/shared_secrets.ex, lib/archethic/transaction_chain.ex, lib/archethic_web/live/chains/reward_live.ex, lib/archethic_web/router.ex, lib/archethic_web/templates/explorer/beacon_chain_index.html.leex, lib/archethic_web/templates/explorer/oracle_chain_index.html.leex, lib/archethic_web/templates/explorer/reward_chain_index.html.leex, lib/archethic_web/templates/layout/root.html.eex, test/archethic/db/embedded_impl_test.exs, test/archethic_web/controllers/faucet_controller_test.exs, test/archethic_web/live/rewards_live_test.exs
It adds a Reward chain explorer to UI, which includes ```:node_rewards and``` ```:mint_rewards``` tx types in chronological order.
Fixes 
- Minor fix 
- Name change:  get_gen_addr : genesis_address , wherever applicable.
- Minor spec changes from number to non_negative_number for index.
- Correct typos.
- New Reward explorer Ui.
- New db method ```list_chain_addresses``` , takes genesis address and return a stream of address in old to recent order.
- This change requires a documentation update 
- Brief Reward chain desc was given under ```/explorer/chain/rewards```  UI.
- Review_changes
- Transactions appear in page w.r.t previous page time reference.
- Display pages according to nb …
=> [Feature] Node rewards chain explorer. Resolves [#413]

lib/archethic/metrics/poller.ex, lib/archethic/p2p/message.ex, lib/archethic_web/live/chains/oracle_live.ex
Fix some issue affecting explorer and API
- `%GetBalance` message: amount serialized in float instead of integer, it was returning number in scientific notation (3e8) but this notation is not handled in Absinthe serialization.
- Metric poller : when using upnp, some router do not open port for local request on public ip (public_ip:port does not work but local_ip:port does work). If not request metrics to iteself, changed ip to 127.0.0.1
- Oracle chain on explorer is firstly loaded in chronologic order, but when a new transaction comes, the transaction is prepended causing an inconsistencie in the transaction order
%GetBalance message return integer value correctly
Metric poller can fetch metric from local ip correclty
- My code follows …
=> Fix some display / API issue

lib/archethic/db/embedded_impl/chain_reader.ex
Fix a bug when requesting a chain to the DB with selected fields.
DB return transaction chain paginated by size of 10, if the chain has more than 10 transactions, DB return the paging address which is the transaction address of the last transaction read.
The problem is if we request specific fields without address, the transaction read have a nil address and so the paging address returned is nil. This beahavior leads to an infinite loop in some case.
Create a transaction chain with more than 10 transactions, request the chain with some specific fields without address (`TransactionChain.get(address, [data: [:content], validation_stamp: [:timestamp]])`) the return is `{chain, true, paging_address}`
with pagin address != nil
- My code …
=> Fix paging address with selected fields

lib/archethic/account/mem_tables/token_ledger.ex, lib/archethic/account/mem_tables/uco_ledger.ex, lib/archethic/db/embedded_impl/chain_index.ex, lib/archethic_web/graphql_schema/transaction_type.ex, test/archethic/db/embedded_impl_test.exs
Fixes an issue when a transaction send funds to itself. If a node try to do a self repair including this transaction, an invalid_transaction_movement appear.
Error is raised because the last transaction address at a specific date return the address if the timestamp is < or = and so the transaction is validated in first as the last address at this time is thre previous transaction of the chain, but during the self repair, the last transaction at this time is the transaction itself.
So to fix this, the last transaction address at specific date returns do not return timestamp == date
Also fix the spent? flag on UTXO when the transaction is already spent
Fixes #594 
Start a node -> faucet to an address
Send a transaction to itself
The …
=> Fix invalid movement when transactoin send funds to itself

lib/archethic/contracts/worker.ex, lib/archethic/oracle_chain/scheduler.ex, lib/archethic/reward.ex, lib/archethic/reward/scheduler.ex, lib/archethic/shared_secrets/node_renewal.ex, lib/archethic/shared_secrets/node_renewal_scheduler.ex, lib/archethic/utils/detect_node_responsiveness.ex, test/archethic/shared_secrets/node_renewal_test.exs, test/archethic/utils/detect_node_responsiveness_test.exs
Fixes #604 
To test hard timeout: 
- Run 3 nodes and wait them to be authorized
- Update the runtime of one node to change the price received by coingecko api, as so transactions will failed and node detection will be triggered until hard_timeout
in `lib/archethic/oracle_chain/services/uco_price/providers/coingecko.ex` replace the function fetch like this :
```
def fetch(pairs) when is_list(pairs) do
{:ok, %{"eur" => 10, "usd" => 10}}
end
```
- I have added tests that prove …
=> Improve node detection

lib/archethic/p2p/mem_table.ex
When a node goes globally unavailable, it's availability history goes to 0. But, for a node, there is no way to self increase it's availabilty hostory, so from the node itself it's local availability may be to 0.
As we changed previously the way we handle the availability history, decreasing availability when node goeas globally unavailable is not required anymore
Start 2 nodes
Wait them to be authorized
Stop 1 node and wait it to be globally unavailable
Restart it just before a beacon summary time
On the next self repair the node should be globally unavailable and locally available for itself
- I have commented my code, particularly …
=> Remove decrease availability history when node goes unavailable

Makefile, config/dev.exs, config/prod.exs, lib/archethic/crypto/keystore/node/origin.ex, lib/archethic/crypto/keystore/node/origin/software_impl.ex, lib/archethic/crypto/keystore/node/origin/tpm_impl.ex, lib/archethic/crypto/keystore/node/software_impl.ex, lib/archethic/crypto/keystore/node_supervisor.ex, src/c/crypto/tpm/keygen.c, src/c/crypto/tpm/lib.c, src/c/crypto/tpm/lib.h, src/c/crypto/tpm/port.c, test/archethic/crypto/keystore/node/origin/tpm_impl_test.exs, test/archethic/crypto/keystore/node/software_impl_test.exs, test/support/template.ex
Leverage TPM NV indexes to store the node seed generated by secure random generator from the TPM.
This allows to provide a secure backup for the node seed.
Fixes #589 
Start a node with TPM activated.
Then reboot and restart the app, the seed should remain the same.
- Any dependent changes …
=> Use NV indexes to store node's seed in TPM

lib/archethic/contracts/interpreter.ex, lib/archethic/contracts/interpreter/library.ex, test/archethic/contracts/interpreter_test.exs
Leverage standard hash algorithm output instead of specific one provided by addresses in Archethic.
Fixes #611 
=> Fix hash function in SC library

lib/archethic/contracts/worker.ex
Using SC datetime's trigger with UNIX timestamp from a pastime, causes the worker to crash.
Hence, this fix ensures the worker will only trigger date time UNIX timestamp in the future.
=> Fix datetime interval sc

lib/archethic/account/mem_tables/token_ledger.ex, lib/archethic/account/mem_tables/uco_ledger.ex, lib/archethic/account/mem_tables_loader.ex, lib/archethic/bootstrap/network_init.ex, lib/archethic/mining/validation_context.ex, lib/archethic/replication/transaction_validator.ex, lib/archethic/reward/scheduler.ex, lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations.ex, lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations/unspent_output.ex, lib/archethic_web/graphql_schema/transaction_type.ex, test/archethic/account/mem_tables_loader_test.exs, test/archethic/account_test.exs, test/archethic/bootstrap/network_init_test.exs, test/archethic/contracts/worker_test.exs, test/archethic/mining/standalone_workflow_test.exs, test/archethic/mining/transaction_context_test.exs, test/archethic/mining/validation_context_test.exs, test/archethic/p2p/messages_test.exs, test/archethic/replication/transaction_context_test.exs, test/archethic/replication/transaction_validator_test.exs, test/archethic/replication_test.exs, test/archethic/reward/mem_tables_loader_test.exs, test/archethic/reward/scheduler_test.exs, test/archethic/reward_test.exs, test/archethic/transaction_chain/transaction/validation_stamp_test.exs, test/archethic/transaction_chain_test.exs, test/archethic_web/controllers/faucet_controller_test.exs, test/support/transaction_factory.ex
Includes a new field in UnspentOutputs : timestamp.Timestamp is a DateTime field with precision of milliseconds. Serde is done through conversion into unix timestamp with milliseconds , and the no_negative_int  size is 8 bytes/ 64 bits.
There are 3 sources of UTXO timestamp generation:
-  In Network init , during self-validation.
-  In Memtable loaders for UCO / Token ledger, 
- Conversion of Transaction Movement to UTXO(with validation timestamp as UTXO timestamp)
- https://github.com/archethic-foundation/archethic-node/blob/b03f84d7bf85f7ba42eee6b58310922ded6328a8/lib/archethic/account/mem_tables_loader.ex#L105-L106
- In Validation Context.ex
- https://github.com/archethic-foundation/archethic-node/blob/b03f84d7bf85f7ba42eee6b58310922ded6328a8/lib/archethic/mining/validation_context.ex#L …
=> Add timestamp in the unspent outputs#564

lib/archethic/oracle_chain/scheduler.ex, lib/archethic/oracle_chain/services/uco_price/providers/coingecko.ex, lib/archethic/reward/scheduler.ex, lib/archethic/shared_secrets/node_renewal_scheduler.ex, test/archethic/reward/scheduler_test.exs
Fixes some bug on network transaction scheduler
- Add timeout on coingecko request to avoid node to not respond in time for transaction validation https://github.com/archethic-foundation/archethic-node/commit/8541abea62d3bfbfd8ef767016ed2211ca025649
- Fix Process.exit on node detection which was not working with `:normal` reason https://github.com/archethic-foundation/archethic-node/commit/930a0ea88e7561dd87988d24073034c641c7f684
- Fix reward scheduler when receiving mint reward transaction while in scheduled state, expected behavior is to send node reward transaction after https://github.com/archethic-foundation/archethic-node/commit/51a91de0fe6f63ac75b554c51644e9296884d6e0
- Rework handling of node detection process when they exit …
=> Fix scheduler bugs

.github/workflows/ci.yml, config/config.exs, mix.exs, mix.lock
Adds `sobelow` for static analysis of the code
Refer: https://github.com/nccgroup/sobelow
Fixes #593 
- Changes in dependencies
- mix task changes - `mix dev.checks` & `mix dev.pchecks`
- Git hook for pre_push will now run sobelow checks
- GitHub Actions run sobelow checks
Ran it locally and on the CI.
Sobelow checks are run and the report is shown. …
=> Adds sobelow for static analysis in dev and ci/cd

lib/archethic_web/transaction_subscriber.ex
Transaction subscriber return the maximum number of confirmation, but it was taking all authorized nodes instead of authorized and available nodes
=> Fix Transaction subscriber returning wrong number of max confirmations

config/prod.exs, lib/archethic_web/domain.ex
By default there is no certificate for https in prod config. But without certificate, the https endpoint is not launched and so we cannot resolve request for aeweb redirection with dnslink.
To enable this functionnality, a self signed certificate is configured by default so the https endpoint is started and the node can serve aeweb website with certificate and https encryption
- New and existing …
=> Add selfsigned certificate by default in prod config

lib/archethic/mining/pending_transaction_validation.ex, lib/archethic/shared_secrets.ex, lib/archethic_web/controllers/api/origin_key_controller.ex, test/archethic/mining/pending_transaction_validation_test.exs, test/archethic/shared_secrets_test.exs, test/archethic_web/controllers/api/origin_key_controller_test.exs
`/api/origin_key` -> Origin endpoint is leveraged to add origin public key and its corresponding certificate, An origin transaction is created, on post request, with content as origin_public_key and certificate, But there are no checks for to ensure that this origin public key has already been included in existing transaction. A  check is introduced leveraging the OriginKey store to check if the origin Public key already exists before creating/accepting the transaction.
Checks are done at two different location/Stages:
- In the `origin Api controller`, During post call
- In `Pending_transaction_validation.ex` in do_accept_tx(:origin), validation of tx
New error logging for both locations api call and during validation is introduced. 
##Fixes 
- Bug fix 
- Check for existing Origin Public …
=> Origin transaction should verify existing public key#583

lib/archethic/oracle_chain/mem_table_loader.ex
When a node restart, it loads the past oracle summary in memory, but it do not load the last oracle transaction.
In some case the next self repair after the bootstrap may failed caused by an invalid_transaction_fee error.
So, during init Oracle Mem Table Loader also load the last oracle chain transactions
To reproduce the error: 
- start 3 node and wait them to be authorized
- after an oracle summary, wait for the next oracle transaction (normally coming just after summary)
- stop a node
- send a transfer transaction
- restart the node after other set it as unavailable
On the next self repair, the restarted node should have a invalid transaction fee error.
With the fix the error do not happen anymore
- My code follows the style …
=> Fix last oracle chain loaded in mem table loader init

config/dev.exs, config/prod.exs, lib/archethic/networking/scheduler.ex, lib/archethic/p2p.ex, lib/archethic/p2p/client/connection.ex, lib/archethic/p2p/client/connection/supervisor.ex, lib/archethic/p2p/client/default_impl.ex, lib/archethic/p2p/client/transport/tcp_impl.ex, lib/archethic/p2p/listener_protocol.ex, lib/archethic/p2p/mem_table_loader.ex, test/archethic/p2p/client/connection_test.exs
Fixes some bug in connection between nodes:
- Add a timeout in tcp handle_connect. Default timeout is infinity so the process stay stuck in this function if the server is unreachable.
- If a node changes it's ip, the connection module associated to the node is not notified. Now whenever a node is updated, if the connection informations change (ip, port, transport), the connection process is killed and a new one is started with the new informations
- Run 3 nodes
- Stop one and restart it with other port parameter
Connection should be updated and nodes can contact each other
- I have commented my code, particularly in hard-to-understand …
=> Fix connection bugs

lib/archethic/contracts/contract/conditions.ex, lib/archethic/contracts/contract/constants.ex, lib/archethic/contracts/interpreter.ex, lib/archethic/contracts/interpreter/library.ex, lib/archethic/contracts/worker.ex, test/archethic/contracts/worker_test.exs
=> Add timestamp in sc

lib/archethic/self_repair/sync.ex
Fix download verification in self repair, based on the authorized node at the summary date.
Also avoid verification when node is authorized and when there is less than 3 authorized nodes in the network.
=> Ensure download of self repair on other locally available nodes

lib/archethic/db.ex, lib/archethic/db/embedded_impl.ex, lib/archethic/db/embedded_impl/chain_index.ex, lib/archethic/db/embedded_impl/chain_writer.ex, lib/archethic/p2p/mem_table.ex, lib/archethic/p2p/node.ex, lib/archethic/replication/transaction_validator.ex, lib/archethic/self_repair/sync.ex, test/archethic/beacon_chain_test.exs, test/archethic/bootstrap/sync_test.exs, test/archethic/p2p/mem_table_test.exs, test/support/template.ex
When a node bootstrap, it loads networks node with the latest informations about them. Then it launch it's self repair.
During the self repair, controls are done in the replication to check transaction validity. The valid election control is based on the last public key of a node, but it takes the current last public key of a node and not the one when the transaction was signed.
So if a node signed a transaction and then updating it's chain, the last public key is not the same and so the control fails which also fails the self repair.
To fix this we retrieve the last public key of a node at the transaction timestamp.
Other fixes are done when for some reason there is no summary for a date (all nodes off for example), the self repair was crashing. Now if a summary aggregate is not found, …
=> Fix self repair bugs

lib/archethic/oracle_chain/scheduler.ex
Prevent `poll` event to send when the oracle chain scheduler is rescheduling after an oracle summary transaction. 
=> Cancel oracle polling timer when a rescheduling is started

lib/archethic/p2p/mem_table.ex
Prevent update of node's availability history from the node listing in the bootstrap.
The availability history should only be changed locally by the connection itself.
=> Prevent update of node availability history during node update

lib/archethic/self_repair/sync.ex
This change ensures the self-repair will be halted if the transaction processing is failing
=> Stop self repair if transaction's processing failed

lib/archethic/beacon_chain/slot_timer.ex, lib/archethic/beacon_chain/subset.ex, lib/archethic/beacon_chain/summary_timer.ex, lib/archethic/mining/distributed_workflow.ex, lib/archethic/mining/pending_transaction_validation.ex, lib/archethic/mining/standalone_workflow.ex, lib/archethic/oracle_chain.ex, lib/archethic/oracle_chain/scheduler.ex, lib/archethic/reward.ex, lib/archethic/reward/scheduler.ex, lib/archethic/self_repair/sync.ex, lib/archethic/shared_secrets.ex, lib/archethic/shared_secrets/node_renewal_scheduler.ex, lib/archethic/utils.ex, test/archethic/crypto/keystore/shared_secrets/software_impl_test.exs
Fix invalid slot times causing drift of transaction timestamping on the beacon 
- Bug fix (non-breaking change which fixes an issue
=> Fix beacon date projections

lib/archethic/account/mem_tables_loader.ex, lib/archethic/p2p.ex, lib/archethic/p2p/mem_table.ex, lib/archethic/p2p/mem_table_loader.ex, lib/archethic/p2p/node.ex, lib/archethic/replication.ex, lib/archethic/replication/transaction_validator.ex, lib/archethic/self_repair/sync.ex, lib/archethic/self_repair/sync/transaction_handler.ex, lib/archethic/transaction_chain/mem_tables_loader.ex, lib/archethic_web/controllers/api/schema/ownership.ex, test/archethic/replication/transaction_validator_test.exs
Fixes multiple bugs: 
- Node transaction was not added in account mem table loader, causing error in replication when retrieving unspent outputs.
- Time condition to start self repair was not well handled, causing self repair to not start when it should.
- If a node has changed it's IP after some times, new nodes should always connect to the latest IP available even if they didn't synchronize all the node transactions
- Improve of synced? flag update
- Fix Ecto warning
- Fix error `DateTime.to_unix(nil, :second)` while loading transaction with code
- I …
=> Fix bootstraping bugs

lib/archethic_web/live/settings_live.ex
Node settings page on explorer is only available on local network. The filter to verify if client ip is local do not handle ipv6 address.
=> Handle ipv6 local ip in node settings page

lib/archethic/mining.ex
When a validation node has a replication error, the distributed workflow process is ended. But other replication node may send a `ReplicationError` message to this validation node. The validation node will search for the mining process and will return nil after 3 seconds. But the replication node will have a timeout on the response of the `ReplicationError` message.
To avoid it, the timeout to find the mining process is reduced to 1 second as the process should have been already started or closed after an error …
=> Add lower timeout for replication error notification

scripts/install.sh, scripts/release.sh
To ease installation on different system and to ensure upgrade of elixir and erlang version during a release, we now use asdf to manage elixir and erlang installation
=> Update installation and release scripts to use asdf

lib/archethic/mining/distributed_workflow.ex, lib/archethic/mining/standalone_workflow.ex, lib/archethic/p2p/message.ex, lib/archethic/p2p/message/notify_last_transaction_address.ex, lib/archethic/replication.ex, test/archethic/p2p/messages_test.exs, test/archethic/replication_test.exs
Prevent flooding of ack messages in transaction replication
=> Optimize ack of previous shards

config/prod.exs
Fix genesis pool allocation with right addresses and amounts according the new token economy.
Run the node in production mode
```sh
MIX_ENV=prod ARCHETHIC_CRYPTO_NODE_KEYSTORE_IMPL=SOFTWARE ARCHETHIC_NODE_ALLOWED_KEY_ORIGINS=SOFTWARE ARCHETHIC_NODE_IP_VALIDATION=false ARCHETHIC_P2P_BOOTSTRAPPING_SEEDS="127.0.0.1:3002:00011D967D71B2E135C84206DDD108B5925A2CD99C8EBC5AB5D8FD2EC9400CE3C98A:tcp" ARCHETHIC_CRYPTO_SEED="node1" ARCHETHIC_NETWORKING_PORT_FORWARDING=false ARCHETHIC_HTTP_PORT=4000 ARCHETHIC_P2P_PORT=3002 iex -S mix
```
The first transaction's transfer should handle the pool and amounts  …
=> Fix genesis pool amounts & addresses

lib/archethic/beacon_chain.ex, lib/archethic/replication.ex, lib/archethic/replication/transaction_context.ex, lib/archethic/self_repair/sync.ex, lib/archethic/self_repair/sync/transaction_handler.ex, lib/archethic_web/live/chains/beacon_live.ex, test/archethic/beacon_chain_test.exs, test/archethic/replication/transaction_context_test.exs, test/archethic/self_repair/sync/transaction_handler_test.exs, test/archethic/self_repair/sync_test.exs
When a node start for the first time, it has to download all the previous transaction by doing a bootstrap self repair.
Before doing it, the node get the last P2P view available to connect to all nodes.
But after synchronizing the first summary, the node update it's P2P view with it and so has only the first node as authorized and available, but this node may no longer be up. So the node may not be able to download transaction.
To solve this, we should use the latest P2P view to download the transaction in the self repair. We can pass the view in parameter for the self repair, and fetch the transaction using this view (all other controls for election are done on the current view of the node)
launched a self repair on the actual mainnet …
=> Use current node view for downloading while in self repair

lib/archethic/mining/validation_context.ex
This PR aims to resolve a bug introduced in 0aa05779dcca7455ffe1f3c688e541a10c2666f0.
Because node transaction doesn't leverage existing origin key for their first transaction. We have to use existing list origin key candidates to avoid code repetition.
=> Fix Proof of work existence for node transaction

lib/archethic.ex, test/archethic_test.exs
When retrieving the inputs of an address, we compare them to the inputs of the latest transaction of the address. 
If an input has a match (the same `(token, from)`) in the last transaction, that input is unspent. If there is no match for an input, it means it has been spent.
Fixes #627
- Bug fix
This has been tested via integration tests and with the following scenario on the explorer: 
1. Bastien creates a CC token
2. Bastien creates a DD token
3. Bastien transfers some DD token to Hamza
- I have added tests that prove my …
=> Query P2P in order to determine if an input is spent later on

lib/archethic/mining/distributed_workflow.ex, lib/archethic/mining/standalone_workflow.ex, lib/archethic/mining/validation_context.ex, lib/archethic/p2p/message.ex, lib/archethic/p2p/message/notify_last_transaction_address.ex, lib/archethic/p2p/message/notify_previous_chain.ex, lib/archethic/replication.ex, test/archethic/p2p/messages_test.exs, test/archethic/replication_test.exs
Fix infinite recursion of last address notification.
Before, the notification was done by each storage nodes of each previous transactions as recursion.
Now, to avoid infinite loop and improve performances, the storage nodes of the transaction will trigger and elect the right unique nodes to be notified. (because they know all the transaction of the last chain)
- New and existing unit tests pass …
=> Fix recursion of notify last address

lib/archethic/mining/distributed_workflow.ex, lib/archethic/oracle_chain/scheduler.ex, lib/archethic/p2p/client/connection.ex, lib/archethic/reward/scheduler.ex, lib/archethic/shared_secrets/node_renewal_scheduler.ex
During hot upgrades, GenServer handle default code_change,
however, GenStateMachine does not.
Hence, we have to add a default one to make the upgrade successful
- Enhancement
Using this script: `local_release.sh`
```sh
#!/bin/bash
UPGRADE=0
usage() {
echo "Usage:"
echo ""
echo " Release Archethic node binary"
echo ""
echo "  " local_release.sh" Install the release"
echo "  " local_release.sh -u "       Upgrade the release"
echo ""
}
while getopts :suhd: option
do
case "${option}"
in
u) UPGRADE=1;;
h)
usage
exit 0
;;
*)
usage
exit 1
;;
esac
done
shift $((OPTIND -1))
VERSION=$(grep 'version:' mix.exs | cut -d '"' -f2)
if [ $UPGRADE == 1 ]
then
mix distillery.release --upgrade
echo "Copy upgraded release into …
```
=> Add default `code_change/4` in GenStateMachine

lib/archethic/beacon_chain/replication_attestation.ex, lib/archethic/beacon_chain/slot/validation.ex, lib/archethic/beacon_chain/subset.ex, lib/archethic/beacon_chain/summary_aggregate.ex, lib/archethic/p2p/client/default_impl.ex, lib/archethic/p2p/listener_protocol.ex, lib/archethic/p2p/message.ex, lib/archethic/utils/regression.ex, test/archethic/beacon_chain_test.exs
=> Ensure destination of elected message

lib/archethic.ex, lib/archethic/bootstrap.ex, lib/archethic/mining/pending_transaction_validation.ex, lib/archethic/mining/transaction_context.ex, lib/archethic/p2p.ex, lib/archethic/replication/transaction_context.ex, lib/archethic/self_repair.ex, lib/archethic/self_repair/scheduler.ex, lib/archethic/self_repair/sync.ex, lib/archethic/self_repair/sync/transaction_handler.ex, lib/archethic/transaction_chain.ex, lib/archethic_web/controllers/api/transaction_controller.ex, lib/archethic_web/live/chains/beacon_live.ex, lib/archethic_web/live/top_transactions_component.ex, test/archethic/mining/pending_transaction_validation_test.exs, test/archethic/p2p_test.exs, test/archethic/self_repair/sync/transaction_handler_test.exs, test/archethic/self_repair/sync_test.exs, test/archethic/transaction_chain_test.exs
Trying to send the same transaction from the node should be prevented during transaction validation by checking the existence of the transaction
Fixes #678 
- Enhancement
If you send an existing transaction from the node an error should be triggered.
=> Check if transaction already exists during transaction validation

lib/archethic.ex, test/archethic_test.exs
When requesting balance we used to get the value from the first node, we need to do a quorum call and use the max value form the balance.
Fixes #692 
This is tested in get_balance/1 tests in test/archethic_test.exs, I modified the tests to have multiple nodes with multiple balance values and different tokens with different values. …
=> :bug: add quorum for requesting balance

lib/archethic/crypto/keystore/shared_secrets/software_impl.ex, test/archethic/crypto/keystore/shared_secrets/software_impl_test.exs
The daily keys (created by node shared secrets) are stored in an ets table, but we only use the current daily key and the previous one, so we don't need to store all the previous daily keys in the ets table
Fixes #697 
We add 3 entries in the ets table and we make sure that only the last 2 entries remain.
- New and existing unit tests pass locally …
=> :racehorse: remove old daily keys from ets table

lib/archethic_web/graphql_schema.ex, lib/archethic_web/graphql_schema/resolver.ex, lib/archethic_web/graphql_schema/version_type.ex, test/archethic_web/graphql_schema_test.exs
There is some use case to provide an API that returns versions running on a node.
The API could returns
code version (from mix.exs)
transaction version
protocol version
Fixes #701 
The graphql was tested by querying the system and making sure that the values returned match.
- Any dependent …
=> add graphql query to get version of running code, protocol and transaction

lib/archethic/db/embedded_impl/chain_index.ex, test/archethic/db/embedded_impl/chain_index_test.exs, test/archethic/db/embedded_impl_test.exs
Actually there is 2 way to set the last address for a chain
from the replication
from the notification of a last address
In both way, if the current last address in the DB has a greater timestamp than the one received, the last address is replaced by the new one. Which is not correct.
before setting the new last address, we should control that the new timestamp is greater than the one already stored
Fixes #712 
I tested 2 cases: 
- we should not update last transaction only if timestamp is lesser
- we should update last transaction if timestamp is greater …
=> Update last transaction address only if timestamp is greater

lib/archethic/reward.ex, lib/archethic/utils.ex
Actually the node_reward transaction is sent based on a configurable interval. n production this interval is set to 1 transaction per day.
In the reward calculation we get the number of days of the current month and divide 50 by this number. This fit well for production configuration but if the node_reward transaction are sent in a different interval than once a day, the reward calculation is not accurate.
We should divide the monthly reward amount (currently 50$) by the number of interval in the current month
Note: 
I saw that sometimes it can take a little bit of time to compute, so I decided to do he computation in compile time to not slow down the execution.
Fixes #693 
- New feature …
=> compute node reward based on scheduler time

lib/archethic_web/graphql_schema/resolver.ex, lib/archethic_web/graphql_schema/transaction_type.ex, test/archethic_web/graphql_schema_test.exs
Add the possibility to retrieve the token's ownerships. Similar to `transaction.data.ownerships`
Fix #714 
Tested on a local node
=> GraphQL: return token.ownerships

lib/archethic/mining/pending_transaction_validation.ex, test/archethic/mining/pending_transaction_validation_test.exs, test/archethic/shared_secrets/node_renewal_test.exs
Actually during the pending validation, we control if the new authorized nodes in the node shared secret transaction are part of the candidate, but we do not verify if the selected ones are the good ones.
We should not verify if the new authorized nodes are part of the candidate, but directly verify that all authorized nodes are the same as the return of the function NodeRenewal.next_authorized_node_public_keys()
Fixes #694 
we make sure that the authorized nodes in the transaction are exactly the same as the ones returned by 
next_authorized_node_public_keys function
- I have commented my …
=> Valid the authorized nodes in the node shared secret

config/dev.exs, config/prod.exs, config/test.exs, lib/archethic_web/controllers/aeweb_root_controller.ex, lib/archethic_web/controllers/api/web_hosting_controller.ex, lib/archethic_web/templates/dir_listing/index.html.heex, lib/archethic_web/views/dir_listing_view.ex, test/archethic_web/controllers/api/web_hosting_controller_test.exs
Display a directory listing when the user hits an endpoint that correspond to a directory and the directory does not contain a `index.html` file.
This should be performant because only 1 transaction is downloaded (the reference transaction). But, because of this we cannot determine the files' sizes. 
I used Firefox source as template.
Fixes #596
- New feature 
Tested with unit tests.
Tested with the `aewebcli` with the following structure [myaewebdir.zip](https://github.com/archethic-foundation/archethic-node/files/10056869/myaewebdir.zip)
- My changes generate no …
=> AEWeb - Directory listing

lib/archethic.ex, lib/archethic/transaction_chain.ex
This issue fix a bug on graphQL API when a user request a transaction chain, it was return more than 10 transactions
Create a chain with more than 10 transactions, the graphql request 
```
{
transactionChain(address: "last_chain_address") {
address
}
}
```
should return then 10 first transactions
- Any dependent changes have been merged and …
=> Fix GraphQL transaction_chain returning more than 10 tx

lib/archethic/db/embedded_impl/chain_index.ex, lib/archethic/p2p/message.ex, lib/archethic/replication.ex
`NotifyLastTransactionAddress` message is not sending the notification for the genesis address of a chain. But in multiple case we want to get the last address of a chain from it's genesis address.
- Added genesis address in the address list of the chain
- Updated the default timestamp when requesting last_address from a chain without transaction
- Run 5 nodes with updated sharding parameter (use patch in #671)
- Use faucet multiple time, it should work each time after the first transaction
- My changes generate …
=> Fix notify last address

lib/archethic/p2p/client/connection.ex, test/archethic/p2p/client/connection_test.exs
Reconnect workflow used to be synchronous, which meant all incoming messages were queued to be processed later, and the callers had to wait until eventually they receive a :timeout. 
This PR changed the reconnect workflow to be asynchronous, so the callers can get a :closed error message without delay.
**NOTE**: the first connection is still asynchronous to be able to keep existing code.
Fixes #710
- Bug fix
Case added to the unit tests
- New and …
=> Connection's reconnect is asynchronous

lib/archethic/mining/distributed_workflow.ex, lib/archethic/mining/validation_context.ex, lib/archethic/transaction_chain/transaction/validation_stamp.ex, test/archethic/mining/distributed_workflow_test.exs, test/archethic/mining/validation_context_test.exs
In the distributed workflow, if there is an error in the validation stamp or in the cross validation stamp, then do not send the replication messages to the storage nodes, and directly notify the error to the welcome node.
`notify_error` used to be an internal event but we had to change this to a function to be able to use it from the `replication.state_enter` callback.
Fixes #696 
**IMPORTANT NOTE:** The scenario `:insufficient_funds` is not checked in the distributed_workflow. This means a transaction from an address with insufficient funds will not mark the stamps as invalid and the transaction will be replicated to the storage nodes where they'll be discarded.
- Bug fix 
Tests added to the suite.
Scenario tested on the transaction builder (with 3 nodes): Creation of a token with an …
=> Skip replication if there is a (cross)validation error

lib/archethic.ex, lib/archethic/account.ex, lib/archethic/account/mem_tables_loader.ex, lib/archethic/contracts/loader.ex, lib/archethic/db.ex, lib/archethic/db/embedded_impl.ex, lib/archethic/db/embedded_impl/chain_index.ex, lib/archethic/db/embedded_impl/chain_reader.ex, lib/archethic/db/embedded_impl/chain_writer.ex, lib/archethic/oracle_chain/scheduler.ex, lib/archethic/replication.ex, lib/archethic/self_repair/sync.ex, lib/archethic/transaction_chain.ex, lib/archethic/utils/detect_node_responsiveness.ex, test/archethic/account/mem_tables_loader_test.exs, test/archethic/bootstrap/network_init_test.exs, test/archethic/bootstrap_test.exs, test/archethic/db/embedded_impl_test.exs, test/archethic/replication_test.exs, test/archethic/reward_test.exs, test/archethic/self_repair/repair_worker_test.exs, test/archethic/self_repair/sync/transaction_handler_test.exs, test/archethic/self_repair/sync_test.exs, test/archethic/utils/detect_node_responsiveness_test.exs, test/support/template.ex
For now IO transaction are used only for updating the inputs of a transaction. Therefor we don't want to update anything in the ChainIndex like the last address.
So the idea is to create 2 storage folder, one for io tx and one for chain tx, and do not update ChainIndex while writing an io transaction
- Unit tests
- Start 5 node with sharding properties updated
- Create some transactions, nodes should store io transaction in "io" folder
- Stop and restart a node, it should update the account mem table properly
- …
=> Separate chain and io transaction in DB storage

lib/archethic/bootstrap/network_init.ex, lib/archethic/crypto.ex, lib/archethic/mining/pending_transaction_validation.ex, lib/archethic_web/controllers/api/schema/origin_public_key.ex
=> Fix origin certs

lib/archethic/mining/validation_context.ex, lib/archethic/replication/transaction_validator.ex
Prevent race condition during transaction's validation to avoid read conflicts about the UCO price to calculate the transaction's fee.
=> Take older oracle chain uco price in tx validation

lib/archethic/bootstrap.ex, lib/archethic/mining/transaction_context.ex, lib/archethic/replication.ex, lib/archethic/transaction_chain.ex, test/archethic/bootstrap_test.exs
- Fix timeout on replication  so the task don't fall in timeout before the message timeout
- Update the timeout to 4s for fetch the context during mining validation (mining timeout for getting cross validation node context is 5sec)
- Remove the task in post_bootstrap while re syncing the network chain
- Any dependent changes have been merged …
=> Fix request timeout

lib/archethic/replication.ex
=> Prioritize local fetch of transaction in the replication

lib/archethic/oracle_chain/mem_table.ex, lib/archethic_web/controllers/api/transaction_controller.ex, test/archethic/oracle_chain/mem_table_loader_test.exs, test/archethic_web/controllers/api/transaction_controller_test.exs
Get the previous oracle chain data to avoid race condition
=> Get previous oracle chain data

lib/archethic/p2p/message.ex, lib/archethic/p2p/message/notify_last_transaction_address.ex, lib/archethic/replication.ex, lib/archethic/self_repair.ex, lib/archethic/self_repair/repair_worker.ex, test/archethic/p2p/messages_test.exs, test/archethic/replication_test.exs, test/archethic/self_repair/repair_worker_test.exs, test/archethic/self_repair/self_repair_test.exs
Fixes #713 
- Unit tests to do
- I have added tests that prove my fix is effective or …
=> request missing address while receiving new last address

lib/archethic_web/live/transaction_details_live.ex
Fixes #774 
-  Tested locally on the page
- I have added tests that prove my fix is …
=> fetch and assign async inputs and token details on transaction detail live

assets/css/variables.scss, lib/archethic.ex, lib/archethic/election.ex, lib/archethic_web/components/pagination.ex, lib/archethic_web/controllers/api/transaction_controller.ex, lib/archethic_web/controllers/explorer_controller.ex, lib/archethic_web/faucet_rate_limiter.ex, lib/archethic_web/live/chains/beacon_live.ex, lib/archethic_web/live/chains/node_shared_secrets_live.ex, lib/archethic_web/live/chains/oracle_live.ex, lib/archethic_web/live/chains/reward_live.ex, lib/archethic_web/live/top_transactions_component.ex, lib/archethic_web/templates/explorer/beacon_chain_index.html.heex, lib/archethic_web/templates/explorer/node_shared_secrets_chain_index.html.heex, lib/archethic_web/templates/explorer/oracle_chain_index.html.heex, lib/archethic_web/templates/explorer/origin_chain_index.html.heex, lib/archethic_web/templates/explorer/reward_chain_index.html.heex, test/archethic_web/live/rewards_live_test.exs
Fetch explorer's data from DB if it is available on current node. This avoid plenty of network requests.
**ALSO**: Refactored a bit the pagination to be consistent across all pages
Fixes #730
Tested the explorer 
=> Explorer optimizations (read DB before asking network when possible)

lib/archethic/transaction_chain/transaction.ex, lib/archethic_web/graphql_schema/transaction_type.ex, test/archethic_web/graphql_schema_test.exs
Fixes #795 
- adapted unit tests
- I have …
=> Add previous transaction address in GraphQl transaction schema

lib/archethic/db.ex, lib/archethic/db/embedded_impl.ex, lib/archethic/replication.ex, lib/archethic/transaction_chain.ex, test/archethic/bootstrap_test.exs, test/archethic/db/embedded_impl_test.exs, test/archethic/mining/pending_transaction_validation_test.exs, test/archethic/replication_test.exs, test/support/template.ex
There is some case where a node should replicate a transaction but it do not due to some latency or network issue. If there is a new transaction in this chain and the node is again storage node of this transaction, it will store the previous transaction without ingesting data as it should have been done.
This PR fix this problem by ingesting if needed the previous transaction of a chain
- New and …
=> Fix replication chain ingestion

lib/archethic.ex, lib/archethic_web/graphql_schema.ex, lib/archethic_web/graphql_schema/resolver.ex, lib/archethic_web/graphql_schema/transaction_type.ex, test/archethic_web/graphql_schema_test.exs
This Pr aims to add a `getGenesisAddress` query to graphql to make it easier to find the genesis address of a transaction.
Start a node, open the explorer, find a transaction and query the graphql endpoint to retrieve the genesis address.
=> Add getGenesisAddress query to graphql

lib/archethic.ex, lib/archethic/replication.ex, lib/archethic/replication/transaction_context.ex, lib/archethic/transaction_chain.ex, lib/archethic_web/faucet_rate_limiter.ex, lib/archethic_web/graphql_schema/resolver.ex, test/archethic/replication/transaction_context_test.exs, test/archethic/transaction_chain_test.exs
For the previous chain stream during replication, we don't fetch chain if the previous address of the transaction is the genesis address of the chain.
Also we stop the stream to the specified address to not crash during self repair
Fixes #835 
Updated unit test
Run 2 nodes, wait for some summaries
start a third node, the self repair should not crash for transaction_already_exists error
- New and …
=> Fix previous chain stream

lib/archethic_web/live/settings_live.ex
After the update of the Phoenix deps, a PR introduced a regression about the html button in the from of the settings page.
This PR fixes the HTML code.
- Start a node
- Go the the settings page: http://localhost:4000/settings
- Change the reward address
- Click on the button "Save"
- The update should be have been taken
- New and existing unit tests pass …
=> Fix submit button on the settings page

lib/archethic/db/embedded_impl/chain_reader.ex, test/archethic/db/embedded_impl_test.exs
DB will now fill the entire field if asked without specifiying nested fields. (See issue for example)
It should not break anything since we are more permissive than before.
Fixes #823
Unit tests added
=> DB: Nested fields behaviour change

lib/archethic_web/controllers/api/web_hosting_controller/directory_listing.ex, lib/archethic_web/templates/dir_listing/index.html.heex, test/archethic_web/controllers/api/web_hosting_controller_test.exs
Fixes #800
- Manual tests
with internal dir
- …
=> Display the size when listing the files of a directory

lib/archethic_web/components/pagination.ex, lib/archethic_web/live/chains/beacon_live.ex, lib/archethic_web/live/chains/node_shared_secrets_live.ex, lib/archethic_web/live/chains/oracle_live.ex, lib/archethic_web/live/chains/reward_live.ex
previous and next button breaks the liveview component in the pagination because the returned div didn't have any liveview action attached to it.
Fixes #818 
Tested manually
=> fix previous on first page and next on last page of pagination component

lib/archethic/application.ex, lib/archethic_web/supervisor.ex
Http port are forwarded while starting `ArchethicWeb.Supervisor` in init function.
While performing a hot reload, the supervisor init function are called to update the supervisor child and strategy. But because of the http forwarding in init function that can take some times, the hot reload may fall in timeout.
To avoid this, the http port forwarding are moved to application start.
- New and …
=> Forward http port at application startup

lib/archethic/contracts/interpreter/library.ex, lib/archethic/contracts/interpreter/utils.ex, lib/archethic/crypto.ex, test/archethic/contracts/interpreter/action_test.exs, test/archethic/contracts_test.exs
- This pr Updates the existing function in SC library `hash` to support multiple hash algos.
``` elixir
hash("data","sha256")
hash("data","sha512")   
hash("data","sha3_256")
hash("data","sha3_512")
hash("data","blake2b")
```
- Also introduces an unused aehash function for ae padding
- Unit Tests …
=> Specify the hash algorithm in the sc library functions #610

lib/archethic/p2p/message.ex, lib/archethic/p2p/message/message_id.ex
Fix missed 74b4125ea61cf2c124033c338813a338779e3c12 
See @tenmoves to complete it
=> Use metaprogramming to reduce boilerplate

lib/archethic/contracts/interpreter/condition.ex, lib/archethic/contracts/interpreter/library.ex, lib/archethic/contracts/interpreter/utils.ex, lib/archethic/p2p/message.ex, lib/archethic/p2p/message/first_transaction_address.ex, lib/archethic/p2p/message/get_first_transaction_address.ex, lib/archethic/p2p/message/message_id.ex, lib/archethic/transaction_chain.ex, test/archethic/contracts/interpreter/action_test.exs, test/archethic/contracts/interpreter/condition_test.exs, test/archethic/contracts/interpreter/library_test.exs, test/archethic/p2p/message/first_transaction_address_test.exs, test/archethic/p2p/message/get_first_transaction_address_test.exs, test/archethic/transaction_chain_test.exs
This pr introduces a support for a new function for SC  Library that is `get_tx_address` with new p2p message
`GetTxFirstAddress` .
- Need
-  Genesis address is not same as first tx address
- genesis address is the name of the file of the tx chain
- genesis_address = hash(genesis_public_key) i=0
- first_tx_address = hash( first public key) i= 1
Fixes 
- Unit Tests 
- Integrations tests …
=> Add get first address in smart contract library #740

lib/archethic/contracts/interpreter/action.ex, lib/archethic/contracts/interpreter/library.ex, lib/archethic/contracts/interpreter/transaction_statements.ex, lib/archethic/contracts/interpreter/utils.ex, lib/archethic/contracts/loader.ex, lib/archethic/db.ex, lib/archethic/db/embedded_impl.ex, lib/archethic/db/embedded_impl/chain_reader.ex, lib/archethic/transaction_chain.ex, test/archethic/bootstrap_test.exs, test/archethic/contracts/interpreter/action_test.exs, test/archethic/contracts/interpreter/library_test.exs, test/archethic/contracts/worker_test.exs, test/archethic/crypto/keystore/shared_secrets/software_impl_test.exs, test/archethic/mining/pending_transaction_validation_test.exs, test/archethic/oracle_chain/scheduler_test.exs, test/archethic/replication_test.exs, test/archethic/self_repair/self_repair_test.exs, test/archethic_web/live/rewards_live_test.exs, test/support/template.ex
This PR aims at adding a `get_calls/1` function to the smart contracts' actions. 
This function can be used to create aggregator contracts that do not do anything until some threshold.
I found few issues along the way that I will create and fix outside of this PR. 
Should the get_calls/1 be available outside the action block?
Fixes #512
I have tested with this contract: 
```
condition inherit: [
type: true,
content: true,
uco_transfers: true
]
condition transaction: [
uco_transfers: size() > 0
]
actions triggered_by: transaction do
transactions = get_calls(contract.address)
set_content size(transactions)
set_type transfer
add_uco_transfer to: "000030831178cd6a49fe446778455a7a980729a293bfa16b0a1d2743935db210da76", amount: 1337 …
```
=> SC: add get_calls/0  action

lib/archethic/contracts/interpreter/transaction_statements.ex, lib/archethic/contracts/worker.ex
Change default contract type from `transfer` to `contract`. We can now have contracts that don't necessarily have transfers. Plus added `data` & `contract` types as valid argument to the `set_type` action.
Fixes #844
Tested this scenario via the transaction builder: 
```
condition inherit: [
content: true
]
condition transaction: [
uco_transfers: size() > 0
]
actions triggered_by: transaction do
set_content "hello"
end
```
- I have added tests that prove my fix is effective …
=> SC: change default contract type 

lib/archethic/reward.ex, lib/archethic/utils.ex
Fixes #827 
- doctests
- manual
- I have added tests that prove my fix is effective or …
=> Reward month occurence should be dynamic

lib/archethic/contracts.ex, lib/archethic/contracts/loader.ex, lib/archethic/replication.ex, test/archethic/bootstrap_test.exs
=> SC: Worker should not be executed while replicating a transaction from self repair#852

lib/archethic/contracts/interpreter/action.ex, lib/archethic/contracts/worker.ex
This PRs allows smart contracts to end without a "next_transaction".
I know @Neylix wants to go one step further (allow contract to have a next transaction even when it ends on a non-transaction-statements) but I believe it should be done in a new issue. (CREATED: https://github.com/archethic-foundation/archethic-node/issues/870)
Tested with a smart contract that use this code:
```
actions triggered_by: interval, at: "0 * * * *" do	
calls = get_calls() 
if calls != [] do 
[...]
add_uco_transfers(transfers)
end
end
```
- I have made corresponding changes to the …
=> SC: ActionInterpreter.execute might return nil to not create a next tx

lib/archethic/contracts/interpreter/action.ex, lib/archethic/contracts/interpreter/transaction_statements.ex, test/archethic/contracts/interpreter/action_test.exs
Add TransactionStatements functions to work with lists.
Authorize Keyword lists in actions. I transformed the whitelist into a blacklist (whitelisting all keyword and blacklisted some keywords from some functions) 
Part of #826
Tests added and tested with the explorer
- Any dependent changes have been merged and published in …
=> SC: Add TransactionStatements functions to work with lists

lib/archethic/contracts/interpreter/condition.ex, lib/archethic/contracts/interpreter/library.ex, lib/archethic/contracts/interpreter/utils.ex, lib/archethic/utils.ex, lib/archethic_web/graphql_schema/resolver.ex, test/archethic/contracts/interpreter/library_test.exs
Fixes #640 
- unit tests 
- manual tests
- I have added tests that prove my fix …
=> added get_token_id function in smart contract library

lib/archethic/p2p.ex, lib/archethic/self_repair/repair_worker.ex, lib/archethic/self_repair/sync/transaction_handler.ex, lib/archethic/transaction_chain.ex, test/archethic/p2p_test.exs, test/archethic/self_repair/sync/transaction_handler_test.exs
During the self repair, we use the quorum read to fetch the missed transactions and the previous summary aggregate.
But if there is some synchronization error, the 3 requested node from the quorum may return that the transaction does not exist and so the self repair crashes.
If the transaction is in the beacon summary it means that it exists and so it should be fetched during self repair.
If the quorum read return an unexpected response (transaction does not exists, transaction invalid ...), we remove from the node list the previously requested nodes, and retry the quorum until we get the expected response or the node list is empty
Fixes #856 
Please describe the tests that you ran to verify your changes. Provide instructions so we can …
=> quorum during self repair should fetch from all nodes

lib/archethic_web/graphql_schema.ex, lib/archethic_web/graphql_schema/resolver.ex, test/archethic_web/graphql_schema_test.exs
Add the resolution of the last address in the get_balance api
Fixes #875 
- Enhancement
The API should fetch the balance from:
- a genesis address
- a transaction
- the latest transaction of a chain
=> Improve balance api

lib/release/transform_purge.ex, rel/config.exs
Create new module `Archethic.Release.TransformPurge`.
This module is called during the creation of an appup from distillery.
It is configured in `rel/config.exs`
Create a release on testnet branch using `./script/test-script.sh -i`
Switch to PR branch, change mix.exs version and generate an appup using `mix distillery.gen.appup --app archethic`
The generated appup should have brutal_purge and soft_purge in each load_module or update instructions.
Generate the upgrade release using `./script/test-release.sh -p` it should take the generated appup as it valid (not create a new one, visible in log) …
=> Create appup transform to set post_purge to soft

lib/archethic/p2p/message.ex, lib/archethic/p2p/message/message_id.ex, scripts/test-release.sh
Improve script `test-release.sh` to create 2 releases folder so we can run 2 nodes at the same time and launch the release on both.
Also refactor the messageId module, so distillery can correctly import the dependencies.
Update a version where some dependencies of `Message` module are update (`Ping` message for example).
Generate the appup using `distillery.gen.appup`, the generated appup has the `Message` module has the `Ping` module in dependency. …
=> Improve release

lib/archethic_web/controllers/api/web_hosting_controller/resources.ex
If there is no index.html in the root folder , we host website as a navigation, but if we go inside any folder and if we encounter a index.html we should host it/ render it instead of rendering as navigation/explorer.
Fixes 
- manual testing 
=> AEWeb: if url is a folder and there is an index.html inside, serve the index.html #874

lib/archethic/bootstrap.ex, lib/archethic/bootstrap/sync.ex, lib/archethic/mining/pending_transaction_validation.ex, lib/archethic/self_repair/sync/transaction_handler.ex, test/archethic/bootstrap_test.exs
Fix a bug when a node goes in first_initialization during bootstrap while the node already exists on the network. The node was not able to correctly retrieve it's index to create the new node transaction in the chain.
Also fix an bug in pending transaction validation while verifying if the transaction already exists
Start 2 nodes, stop 1 and delete it's DB, restart it
It should create a new node transaction in it's node chain.
Then wait for next self repair and try to update the node reward address (using endpoint/settings) and it should create a new transaction in the node chain. …
=> Fix bootstrap node index

lib/archethic/contracts/loader.ex, test/archethic/contracts/loader_test.exs
- Contract Loader: should be able to load a contract & trigger recipients at the same time#866
Fixes 
=> Contract Loader: should be able to load a contract & trigger recipients at the same time#866

config/config.exs, lib/archethic/db/embedded_impl/chain_index.ex, test/archethic/db/embedded_impl/chain_index_test.exs
This first PR addresses the first task : offload transaction index table.
Fixes #811 
- This change passes the current chain index tests.
- The LRU cache is tested by its own tests
=> Issue #811 offload transaction indexes memory tables

assets/js/app.js, lib/archethic_web/live/code_proposal_details_live.ex, lib/archethic_web/templates/code/proposal_details.html.heex, lib/archethic_web/templates/code/proposal_list.html.heex, lib/archethic_web/templates/layout/root.html.heex
=> fixed code proposals and code proposal details pages

lib/archethic/governance/code/CICD.ex, lib/archethic/governance/code/cicd/docker/cicd.ex, lib/archethic/governance/pools/mem_table.ex, lib/archethic/mining/pending_transaction_validation.ex, lib/archethic/replication.ex, lib/archethic/transaction_chain/mem_tables_loader.ex
code_approval transactions weren't put in the corresponding ETS table, and coudn't be loaded properly when we fetched code_proposal transactions (in UI for example).
Also the governance flow wasn't plugged.
=> plug governance flow with incoming transactions

lib/archethic/bootstrap.ex
This PR fetch the last reward address to include it into the new node transactions.
Fixes #909 
You need to start at least 2 or more nodes.
You need to alter the reward address located in the settings page: `/settings`
You have to stop the node, and wait the out of sync threshold to force a new transaction of the node's chain (ie. 1 min)
You can restart the node, and it should create a new transaction with the changed reward address.
- I have added tests that prove my fix is …
=> Take previous reward address in node bootstrap

lib/archethic/contracts.ex, lib/archethic/contracts/loader.ex, lib/archethic/replication.ex, test/archethic/contracts/loader_test.exs
Fix a bug where all the smart contract call where not reloaded when a node bootstrap.
Also start a Worker only if the node is storage node of the transaction
=> Load all contract transaction

config/config.exs, config/dev.exs, lib/archethic.ex, lib/archethic/bootstrap.ex, lib/archethic/bootstrap/transaction_handler.ex, lib/archethic/crypto.ex, lib/archethic/oracle_chain/scheduler.ex, lib/archethic/p2p.ex, lib/archethic/p2p/message/new_transaction.ex, lib/archethic/reward/scheduler.ex, lib/archethic/self_repair.ex, lib/archethic/self_repair/scheduler.ex, lib/archethic/self_repair/sync.ex, lib/archethic/shared_secrets.ex, lib/archethic_web/channels/user_socket.ex, mix.exs, test/archethic/bootstrap_test.exs, test/archethic/contracts/worker_test.exs, test/archethic/oracle_chain/scheduler_test.exs, test/archethic/p2p/messages_test.exs, test/archethic/reward/scheduler_test.exs, test/archethic/shared_secrets/node_renewal_scheduler_test.exs, test/archethic/shared_secrets_test.exs, test/archethic_test.exs, test/archethic_web/controllers/api/origin_key_controller_test.exs, test/archethic_web/controllers/faucet_controller_test.exs, test/archethic_web/graphql_schema_test.exs, test/support/template.ex
When it is the time for protocol to create a new node renewal transaction, there exist a time window where new transactions arrive and election results with anomaly due to missing latest Node shared secret transaction.
- Check for whether a node is synced for every transaction
- If not schedule a request for resync.
- Last nss transaction validation stamp and last scheduling date to determine node status.
Drawbacks
- NSS chain has to be checked for each transaction
Solution
- manual 
- My changes generate no new …
=> Welcome node should forward tx if not synced#872

lib/archethic/beacon_chain/replication_attestation.ex, lib/archethic/beacon_chain/subset.ex, lib/archethic/beacon_chain/summary.ex, lib/archethic/beacon_chain/summary_aggregate.ex, lib/archethic/self_repair/sync.ex, lib/archethic_web/graphql_schema/resolver.ex, lib/archethic_web/live/chains/beacon_live.ex, test/archethic/beacon_chain/replication_attestation_test.exs, test/archethic/beacon_chain/subset_test.exs, test/archethic/beacon_chain_test.exs, test/archethic/bootstrap/network_init_test.exs, test/archethic/self_repair/sync_test.exs
Actually, when it's the time for a new slot, the slot timer send a event to all the subset to process the slot creation.
But due to some latency for a slot node to receive the ReplicationAttestation message or simply the latency for a transaction to be replicated, the slot node may have build and sent the slot before receiving all the slot transaction.
For example:
To solve this problem, here is the new workflow: 
- We don't verify that a replication attestation is in the right slot time. Any attestation can be in any slot.
- When building the summary, we control that the number of confirmations of an attestation reach a certain threshold (35%) of the expected confirmations number. If it not reaches the threshold, the attestation is postponed to the next summary.
- As we can have …
=> Fix slot missing transaction

lib/archethic/contracts.ex, lib/archethic/contracts/interpreter/legacy.ex, lib/archethic/contracts/interpreter/legacy/action_interpreter.ex, lib/archethic/contracts/interpreter/legacy/utils_interpreter.ex, test/archethic/contracts/interpreter/legacy/action_interpreter_test.exs, test/archethic/contracts/interpreter/legacy_test.exs, test/archethic/contracts_test.exs
Remove these warnings by using Function.identify(scope): 
```
warning: variable "scope" is unused (there is a variable with the same name in the context, use the pin operator (^) to match on it or prefix this variable with underscore if it is not meant to be used)
nofile:5
```
**THE ONLY RELEVANT CHANGE IS `lib/archethic/contracts/interpreter/legacy/utils_interpreter.ex`.** The rest is to adapt the tests.
cleanup
unit tests  …
=> Remove warnings about scope not used

lib/archethic_web/endpoint.ex, lib/archethic_web/graphql_schema/resolver.ex, lib/archethic_web/plugs/remote_ip.ex, test/archethic_web/graphql_schema_test.exs, test/archethic_web/plugs/remote_ip_test.exs
Fixes
- manual test with insomnia
- I have added …
=> api_nearest_endpoints_return_node_list_in_reverse_order_#905

lib/archethic/mining/pending_transaction_validation.ex, test/archethic/mining/pending_transaction_validation_test.exs
We want to avoid ddos of keychain tx and keychain access due to being free.
image by @Neylix 
Fixes 
=> Enhance_validation_of_keychain_keychain_access_transaction_#882

lib/archethic/bootstrap.ex, lib/archethic/bootstrap/sync.ex, lib/archethic/p2p.ex, lib/archethic/p2p/mem_table.ex, lib/archethic/p2p/mem_table_loader.ex, lib/archethic/self_repair/sync.ex, test/archethic/bootstrap/sync_test.exs
Fix some errors when a node boostrap.
Sometimes it does not have the right P2P view and self repair fall in invalid election error
Start multiple nodes, disconnect some and reconnect them after.
Do the same thing but deleting database before reconnecting
=> Fix bootstrap node view

lib/archethic/bootstrap/transaction_handler.ex, lib/archethic/networking/scheduler.ex, lib/archethic/self_repair.ex, lib/archethic/utils.ex
If a node's IP address changes, a new transaction (TX) is generated, but an unusual problem arises: the node becomes invisible to other nodes due to the IP change. While the node with the new IP can create a node TX, it must wait for replication and load the last node public key, which fails because it cannot access the TX it created. The solution involves manually waiting for confirmation and initiating a self-repair process.
Fixes 
- My changes generate no new …
=> improve_synchronization_when_node_ip_changes_#887

lib/archethic/contracts/interpreter/legacy.ex, lib/archethic/contracts/interpreter/legacy/condition_interpreter.ex, test/archethic/contracts/interpreter/legacy/condition_interpreter_test.exs
`<`, `>` were not generating proper code.
Fixes #918
- 
add unit test
=> fix conditionInterpreter v0 comparaison

lib/archethic.ex, lib/archethic/contracts/interpreter.ex, lib/archethic_web/controllers/api/transaction_controller.ex, test/archethic/contracts/interpreter_test.exs, test/archethic/contracts/worker_test.exs, test/archethic/oracle_chain/scheduler_test.exs
Catch contract execution error, so the worker does not crash.
We can't provide a detailed error message to the user because it is an erlang error message based on the code we generated after AST manipulation. We might be able to get the line number, I'll create an issue (https://github.com/archethic-foundation/archethic-node/issues/964) about it.
**This PR is based on branch pr/netbox/802 which is the following PR: https://github.com/archethic-foundation/archethic-node/pull/802. Once it is merged, we will need to change the base branch.**
Fixes #919
tested with manual contract execution & added unit tests …
=> Catch the contract execution errors, and return an error msg to the user

.credo.exs, lib/archethic/oracle_chain/services/hydrating_cache.ex, lib/checks/at_vsn.ex
Add a credo rules to check for `@vsn` attributes on GenServer and GenStateMachine.
Example:
I find it add ~300ms run time on my computer 5.8s vs 5.5s.
=> add AtVsn credo rule

config/config.exs, lib/archethic/application.ex, lib/mix/tasks/migrate.ex, lib/release/call_migrate_script.ex, mix.exs, priv/migration_tasks/test/0.0.1-migration_test.exs, priv/migration_tasks/test/0.0.2-migration_test.exs, rel/config.exs, rel/pre_start/migrate.sh, test/mix/tasks/migrate_test.exs
This PR aim to initialize the migration workflow.
Each migration needed will be an elixir scripts in `priv/migration_tasks` according the name to `[version]-[description].exs`.
There is 2 times when the migration is called:
- before starting the application
- during the execution of an upgrade thanks to the appup file. Migrate function call is automatically added at the end of appup
The migration file in DB always contains the last version the node runned the migrate tool, even if there is no migration to execute
- Unit tests
- Create a new migration script that create a file somewhere. Build a release, start the node, run a hot reload, …
=> Initialize migration workflow

lib/archethic/contracts/contract/constants.ex, lib/archethic/contracts/interpreter/action_interpreter.ex, lib/archethic/contracts/interpreter/ast_helper.ex, lib/archethic/contracts/interpreter/common_interpreter.ex, lib/archethic/contracts/interpreter/condition_validator.ex, lib/archethic/contracts/interpreter/legacy/condition_interpreter.ex, lib/archethic/contracts/interpreter/library/common/json.ex, lib/archethic/contracts/interpreter/library/common/list.ex, lib/archethic/contracts/interpreter/library/common/string.ex, lib/archethic/contracts/interpreter/library/contract.ex, lib/archethic/utils.ex, mix.exs, test/archethic/contracts/interpreter/action_interpreter_test.exs, test/archethic/contracts/interpreter/condition_interpreter_test.exs, test/archethic/contracts/interpreter/library/common/list_test.exs, test/archethic/contracts/interpreter/library/common/string_test.exs, test/archethic/contracts/interpreter/library/contract_test.exs, test/archethic/contracts_test.exs
**This PR is based on https://github.com/archethic-foundation/archethic-node/pull/967. To be rebased as soon as it is merged.**
1. User may now code `Contract.add_uco_transfer to: "...", amount: 1` to transfer 1 UCO (before he/she had to specify amount: 100000000 to send 1 UCO. Makes the language friendlier. 
1. Floating points mathematics are now done in BigInt so there is no floating point precision issue.
1. Since we use BigInt for maths, we loose the types of the numbers (1 + 1 == 2.0). To address this inconvenience, I updated the library to have `String.from_number/1` and `String.to_number/1` instead of `String.from_float/1`, `String.from_int/1`, `String.to_float/1`, `String.to_int/1`.
Fixes #893
_ps: I suggest to ignore `test/archethic/contracts/interpreter/condition_interpreter_test …
=> Smart Contracts: Safe floating point maths + automatic amount conversion to 10^8

lib/archethic.ex, lib/archethic/contracts/interpreter.ex, lib/archethic/contracts/interpreter/action_interpreter.ex, lib/archethic/contracts/interpreter/condition_interpreter.ex, lib/archethic/contracts/interpreter/legacy/action_interpreter.ex, lib/archethic/contracts/interpreter/legacy/library.ex, lib/archethic/contracts/interpreter/library/contract.ex, lib/archethic/contracts/worker.ex, lib/archethic/p2p/message/get_contract_calls.ex, lib/archethic/p2p/message/message_id.ex, lib/archethic/transaction_chain.ex, lib/archethic_web/controllers/api/transaction_controller.ex, test/archethic/contracts/interpreter/legacy/action_interpreter_test.exs, test/archethic/contracts/interpreter/library/contract_test.exs, test/archethic/contracts/interpreter_test.exs, test/archethic/contracts/worker_test.exs, test/archethic/p2p/message/get_contract_calls_test.exs
Create a `GetContractCalls` message. Then refactor the `Interpreter.execute/3` to have the calls as a parameter instead of doing some I/O from within the contract execution. 
The `Contract.get_calls()` is actually not really necessary anymore and we could tell the users there is a `calls` global variable available. 
I entirely removed the `get_calls` function from Legacy interpreter since it did not work at all anyway.
I also only added it for the `action` blocks since there are no use case to handle it in `condition` block.
**This PR is based on the branch https://github.com/archethic-foundation/archethic-node/pull/963. We need to rebase it after the merge**
Fixes #926
Unit tests :heavy_check_mark: 
Manual test (faucet smart contract): …
=> SmartContracts: Pass the calls to Interpreter.execute/3 & create corresponding message

lib/archethic/contracts/interpreter/ast_helper.ex, test/archethic/contracts/interpreter/action_interpreter_test.exs
Some SC were not parsing such as the one I added in the test suite. 
This happened because there was a pattern match `[_]` on alias. This is wrong, an alias can be of any size (e.g. `[:Archethic, :Contracts, :Interpreter, :Library, :Contract]`)
Test added.
=> Smart Contract: `is_function_call?` bug

lib/archethic/contracts/interpreter.ex, lib/archethic/contracts/interpreter/action_interpreter.ex, lib/archethic/contracts/interpreter/common_interpreter.ex, test/archethic/contracts/interpreter_test.exs
Add a case to the `format_error_reason/2` to better print the AST of `M.F(A, A, A)`. 
This used to return message like this: 
```
"invalid arguments for function List.empty? - {:atom, \"List\"} . :atom => \"empty?\"(12) - L8"
```
Tests added to the suite
=> Smart Contract: Better error printing

lib/archethic/contracts/interpreter/library/common/json.ex, test/archethic/contracts/interpreter/library/common/json_test.exs
This PR adds a Json.parse/1 function to the smart contract interpreter, in link with issue #989 
Tested with similar tests as Json.path_extract 
=> Add json parse smart contracts

lib/archethic/contracts/interpreter/ast_helper.ex, test/archethic/contracts/interpreter/library/common/list_test.exs
An empty list should not be transformed to an empty map. Empty map should be create with the `Map.new()` function call.
Fixes #996
Test added to the suite.
=> Smart Contracts: empty list should not be transformed to an empty map

lib/archethic/beacon_chain/subset/summary_cache.ex, lib/archethic/db.ex, lib/archethic/db/embedded_impl.ex, lib/archethic/db/embedded_impl/p2p_view.ex
This PR adds a function `code_change` in the P2PView genserver to update the backup file with the new serialization
Also fix the backward compatibility when deserializing SummaryCache backup file
- Create a release from master branch
- Switch to this PR branch and create a new release
- Apply the release at the beginning of a summary
- Stop the node and restart it, it should restart without error with the good P2P view and with the summary cache filled with all slots
- I …
=> Fix p2p view upgrade

lib/archethic/p2p/message_envelop.ex, lib/mix/tasks/regression.ex
Fixes error while running P2P benchmark:
- message decryption failure (due to bad deserialization)
- telemetry application not started
Run benchmark command `mix archethic.regression --bench localhost`
=> Fix P2P benchmark

lib/archethic/contracts/interpreter.ex, test/archethic/contracts/interpreter_test.exs
When a smart contract was using non elixir-valid syntax, an error was raised and the start_mining process crashed without return an error to the end user. 
Following log happened when omitting a space in a keyword list: `triggered_by:transaction`
```
2023-05-03 12:45:48.137 [error] GenServer #PID<0.9153.0> terminating
** (ArgumentError) errors were found at the given arguments:
* 1st argument: not an atom
:erlang.atom_to_list({:atom, "triggered_by"})
(elixir 1.14.1) src/elixir_tokenizer.erl:669: :elixir_tokenizer.tokenize/5
(elixir 1.14.1) src/elixir.erl:371: :elixir.string_to_tokens/5
(elixir 1.14.1) lib/code.ex:965: Code.string_to_quoted/2
(archethic 1.0.8-rc1) lib/archethic/contracts/interpreter.ex:32: Archethic.Contracts.Interpreter.parse/1
(archethic 1.0.8-rc1) …
```
=> Smart Contracts: Catch the invalid elixir syntax error in smart contracts

lib/archethic/contracts/contract.ex, lib/archethic/contracts/interpreter.ex, lib/archethic/transaction_chain/mem_tables_loader.ex, test/archethic/contracts/interpreter_test.exs, test/archethic/contracts_test.exs, test/archethic/transaction_chain/mem_tables_loader_test.exs
The `condition inherit` always were mandatory, but there was a bug in the code. 
This resulted in the ability to create smart contracts without the block but the contracts were unable to produce any next_tx because they would all fail the inherit constraints. (empty condition inherit block ==> refusing all transactions).
ps: the `condition inherit` block will become optional in a later release.
Manual test 
+ Unit test added
- I have added tests that prove my fix is …
=> Smart Contracts: Make the 'condition inherit' block mandatory

lib/archethic/contracts/contract/constants.ex, test/archethic/contracts/contract/constants_test.exs
An issue I found while playing with the SC constants.
Unit test added
=> Smart Contracts: Cast to atom the transaction.type

lib/archethic/oracle_chain/services.ex, lib/archethic/oracle_chain/services/uco_price.ex, test/archethic/oracle_chain/services/uco_price_test.exs, test/archethic/oracle_chain/services_test.exs
There is a issue when any service return a value, the scheduler request for the new datas and the services return a map `%{"uco" => %{}}`
So the oracle scheduler create a new transaction with no data for a service which lead to multiple errors afterward.
This PR fixes it, when a service don't have any value, it return an error and this service is not added to the final map of all the services. Then if all services return an error, the oracle scheduler receive an empty map, so no transaction is created
Unit test …
=> Fix service error when not data is fetched

lib/archethic/contracts/worker.ex
This is required for #929. I extracted it from there. 
Currently, when there is one interval trigger that ticks at the same time at as datetime trigger. They both run concurrently but only 1 can actually create the transaction. The other will get a `transaction already mining` issue. 
This PR fix this by not scheduling an interval tick if there is a datetime tick.
Manual test with this contract: 
```
@version 1
condition inherit: [ content: true ] 
actions triggered_by: interval, at: "* * * * *" do 
Contract.set_content("interval")
end
actions triggered_by: datetime, at: 1683272596 do 
Contract.set_content("datetime")
end
```
- I have …
=> Smart Contracts: Do not schedule an interval tick if there is a datetime tick at the same time

lib/archethic/contracts/interpreter.ex, lib/archethic/contracts/interpreter/action_interpreter.ex, lib/archethic/contracts/interpreter/legacy.ex, test/archethic/contracts/interpreter/action_interpreter_test.exs, test/archethic/contracts/interpreter/library/common/chain_test.exs, test/archethic/contracts/interpreter/library/common/crypto_test.exs, test/archethic/contracts/interpreter/library/common/json_test.exs, test/archethic/contracts/interpreter/library/common/list_test.exs, test/archethic/contracts/interpreter/library/common/map_test.exs, test/archethic/contracts/interpreter/library/common/regex_test.exs, test/archethic/contracts/interpreter/library/common/string_test.exs, test/archethic/contracts/interpreter/library/common/time_test.exs, test/archethic/contracts/interpreter/library/common/token_test.exs, test/archethic/contracts/interpreter/library/contract_test.exs, test/support/contract_factory.ex, test/support/template.ex, test/support/transaction_factory.ex
This is required for #929. I extracted this PR from there. 
**Before:**
We used to initialize the `next_tx` with an empty Transaction. Then at the end of contract execution, we check if the `next_tx` was different than at the initialization. This was not good because we could not detect someone that wanted to clear the code: `Contract.set_code("")`. 
**After:**
We added a boolean flag to detect the user used a function that would modify the `next_tx`. We also initialize the `next_tx` with current contract `code` & `ownerships` (instead of setting these after contract execution).  The change does not impact the legacy interpreter.
Manual tests & unit tests pass …
=> Smart Contracts: Refactor the next_tx changes detection to be able to clear the code

lib/archethic/self_repair/network_view.ex
The network view is not updated when a new node is available after a self repair. So it was causing error as if a node restarts, it doesn't have the same view as the one that didn't restarted.
To fix this we have a new function `NetworkView.update_p2p_view` which is called at the end of a summary repair.
Also in the state of the network view we can have 2 hashes, a current one and a next one that will replace the current one once the threashold time (availability update) is passed. 
Unit test
Start 2 nodes, wait them to be authorized and available.
Restart one, the view should be the same on both nodes …
=> Handle p2p update from self repair in network view

config/test.exs, lib/archethic/bootstrap.ex, lib/archethic/bootstrap/transaction_handler.ex, lib/archethic/p2p/mem_table_loader.ex, lib/archethic/self_repair.ex, lib/archethic/utils.ex, test/archethic/bootstrap/transaction_handler_test.exs, test/archethic/bootstrap_test.exs, test/archethic/self_repair/self_repair_test.exs
There is an issue when multiple nodes are running authorized and available.
If we quickly restart one, its P2P view is not good as the new date stored for last sync date is the summary time and not the time of the self repair.
Fixes it using a new function `SelfRepair.missed_sync?`
Also fix an issue where sometime a node does not add itself in the P2P memtable.
Start 2 nodes and wait to be authorized and available.
Restart one, it should have the right P2P view (before there where error on beacon slot and election)
- I have made corresponding changes to the …
=> Fix p2p view on bootstrap

lib/archethic/beacon_chain/subset/summary_cache.ex, test/archethic/beacon_chain/subset/summary_cache_test.exs
Fixes an issue where the slot created on the same time of a summary where not deleted from the ets table
Fixes #1027 
Unit test
=> Fix slot on summary time to be deleted

lib/archethic/beacon_chain/subset/summary_cache.ex, test/archethic/beacon_chain/subset/summary_cache_test.exs
When nodes are not started on the time of the first slot of the current summary, the backup slot file are never cleared.
Now we delete all backup slot file except the one of the current summary.
Also fix a bug where the last slot of the day was not appended to the right backup file
Fixes #1026
Unit test
- Any dependent changes have been …
=> Fix backup slots not cleared

lib/archethic/db/embedded_impl/chain_index.ex, lib/archethic/db/embedded_impl/supervisor.ex, lib/archethic_cache/lru.ex, test/archethic/db/embedded_impl/chain_index_test.exs, test/archethic_cache/lru_disk_test.exs, test/archethic_cache/lru_test.exs
Improve read concurrency on LRU cache. It now directly read the ets table instead of requesting it to the LRU GenServer. The GenServer is only used to manage the LRU workflow (monitor cache size, add value in ets table and remove old value when max size is reached).
Also move the ChainIndex LRU to be started in Embedded Supervisor instead of being linked to ChainIndex 
Unit test + manual test on lot of datas
- I have added tests that prove my fix is effective or that my …
=> Improve lru read concurrency

lib/archethic/election/hypergeometric_distribution.ex
This PR aims to load hypergeometric distribution C program at runtime instead of compilation, which is creating some issue with docker and snap deployment
=> Hypergeometric distribution executable runtime

Dockerfile, Makefile, README.md, lib/archethic/networking/ip_lookup/nat_discovery/miniupnp.ex
This PR aims to make miniupnp as externalize dependency
=> Require upnpc as external executable

lib/archethic/crypto/keystore/shared_secrets/software_impl.ex
Fixes an issue happening when an authorized node restart between a node_shared_secret transaction and it's application date (between xx:xx:40 and xx:xx:00 on dev / 23:55:00 and 00:00:00 on prod)
The implementation was filling the ets table with only the last node shared secret transaction, so after the node restart it cannot retrieve the daily nonce for the current day as it only filled the one of the next day
Restart a node after a node shared secret and ask for a faucet, the transaction is now validated  without error
- I have made corresponding changes to the …
=> Fill 2 previous daily nonce on boostrap

lib/archethic/bootstrap.ex, lib/archethic/bootstrap/transaction_handler.ex, lib/archethic/replication.ex, test/archethic/bootstrap/transaction_handler_test.exs, test/archethic/bootstrap_test.exs
Fixes an issue when a node loose its DB and then restart. It was replicating the new node transaction sent without replicating the previous chain. This was creating a lot of issue afterward
Start 3 nodes, wait authorized
Stop one and delete it's data
Restart it, it should restart without error and continue to validate transaction
- Any …
=> Fix bootstrap replication

lib/archethic/contracts/interpreter.ex, lib/archethic/contracts/interpreter/action_interpreter.ex, lib/archethic/contracts/interpreter/library/common/time.ex, lib/archethic/transaction_chain/transaction/validation_stamp.ex, lib/archethic/utils.ex, lib/archethic_web/controllers/api/transaction_controller.ex, test/archethic/contracts/interpreter/library/common/time_test.exs, test/archethic/contracts/interpreter_test.exs, test/archethic/utils_test.exs
Make the `Time.now()` function determinist. We need it because in #925 we will run the contracts on many nodes and we will compare the resulting transaction. 
Fixes #921 
Tests added
=> Smart Contracts: determinist Time.now()

lib/archethic/contracts/contract/constants.ex, test/archethic/contracts/contract/constants_test.exs, test/support/transaction_factory.ex
Add resolved address for the uco and token transfers in the smart contract interpreter's constants
Fixes #741 
- Enhancements
=> Add resovled uco and token movements in the contract's constants

lib/archethic/beacon_chain/network_coordinates.ex, lib/archethic/beacon_chain/subset.ex, lib/archethic/beacon_chain/subset/stats_collector.ex, lib/archethic/self_repair.ex, lib/archethic/self_repair/scheduler.ex, lib/archethic/telemetry.ex, test/archethic/beacon_chain/subset_test.exs
This PR catches the beacon chain coordinates timeouts
Fixes #1081
=> Handle timeout network coordinates

lib/archethic/bootstrap.ex, lib/archethic/bootstrap/sync.ex, lib/archethic/bootstrap/transaction_handler.ex, lib/archethic/p2p.ex, lib/archethic/p2p/mem_table_loader.ex, lib/archethic/p2p/message/bootstrapping_nodes.ex, lib/archethic/p2p/message/get_bootstraping_nodes.ex, lib/archethic/p2p/message/list_nodes.ex, lib/archethic/self_repair.ex, lib/archethic/self_repair/network_chain.ex, lib/archethic/self_repair/scheduler.ex, lib/archethic/self_repair/sync.ex, test/archethic/bootstrap/sync_test.exs, test/archethic/bootstrap/transaction_handler_test.exs, test/archethic/bootstrap_test.exs, test/archethic/p2p/messages_test.exs, test/archethic/self_repair/sync_test.exs
Improve the way a node load the nodes into the memtable.
Currently when a node bootstraps, it request the node view from the bootstrapping nodes and add this view into the memtable. But if the node needs to do a bootstrap sync to repair the missed beacon summaries, this view may not be the good one and the self repair verification crashes. Also the node may have into its memtable some nodes that doesn't exists according to the last beacon summaries the node has synchronized.
To fix this I assumed that a node or its informations should be in the memtable only if the according transaction has been replicated. So when a node bootstrap it now request the current node view to be able to download what it needs, but only connect to these node but doesn't add them into the memtable. The only …
=> Fix bootsrap p2p view

lib/archethic/bootstrap.ex, lib/archethic/p2p.ex, lib/archethic/p2p/client.ex, lib/archethic/p2p/client/connection/supervisor.ex, lib/archethic/p2p/client/default_impl.ex, lib/archethic/p2p/mem_table.ex, lib/archethic/p2p/mem_table_loader.ex, lib/archethic/self_repair.ex, test/archethic/p2p/client/default_impl_test.exs
This issue fixes an problem when a node replicate an old node transaction with old connection informations (ip port, transport).
If this happen the active connection that may be good is killed and a new one is created with the old informations. So the node lose a good connection and may be stuck to download rest of summaries / transactions.
To fix this, there is a new control: if the connection status is connected we don't overwrite the current connection.
Also improve the connection when the node start, it was creating a new connection when loading all transaction in MemTableLoader init. Instead, we now wait for all synchronization to finish and then connect with the latest informations available
Unit test
Start nodes, stop one and …
=> Fix connection infos overwrite

lib/archethic/contracts/interpreter/action_interpreter.ex, test/archethic/contracts/interpreter/action_interpreter_test.exs, test/archethic/contracts/interpreter/library/common/time_test.exs, test/archethic/contracts/interpreter_test.exs
With datetime trigger there is a possibility for a contract to run every second. This PR force the datetime to be on a minute.
Documentation included in https://github.com/archethic-foundation/archethic-docs/pull/43
Fixes #992
Unit tests added.
=> Smart Contracts: datetime must be rounded to the minute

lib/archethic/mining.ex, lib/archethic/p2p/message/add_mining_context.ex
There is some possibility due to high network latency that a coordinator node receive a start mining message after the timeout of  processing the context received from cross validation nodes.
In this case the coordinator wait for the context it'll never receive and the cross validation node wait for the validation stamp they'll never receive.
The coordinator fall in timeout due to no context received and notify the welcome node of transaction failure. While the cross validation nodes elect a new coordinator node and continue the validation.
This PR fixes it by increasing the add mining context processing to the maximum time before changing the coordinator node …
=> Increase add mining context timeout to max_timeout

.github/workflows/ci.yml
Since we use release branch there is no ci that  runs on these branch.
I propose to name the release branch as `release/[version]` so we can add this pattern in the ci.yml
=> Add release/* branch in Github action ci

lib/archethic/application.ex, lib/archethic/db.ex, lib/archethic/db/embedded_impl.ex, lib/archethic/db/embedded_impl/chain_index.ex, lib/archethic/db/embedded_impl/chain_reader.ex, lib/archethic/db/embedded_impl/chain_writer.ex, lib/archethic/p2p/mem_table.ex, lib/archethic/transaction_chain.ex, mix.exs, priv/migration_tasks/prod/1.1.3@create_last_stored_index.exs, test/archethic/db/embedded_impl/chain_index_test.exs, test/archethic/p2p/mem_table_test.exs, test/archethic/replication/transaction_context_test.exs, test/support/template.ex
Add a new index on the last stored address for a chain.
Also move the migration execution before starting Archethic.Supervisor
No appup is needed, only migration script
Migration script has been tested on using mainnet DB. One chain (the faucet one) takes about 7 sec so I put a task timeout of 20 sec
tested locally with hot reload and without hot reload (stopped node -> install 1.1.3 -> restart node) …
=> Release 1.1.3

lib/release/restart_telemetry.ex, rel/config.exs
When we update the telemetry metrics, we need to restart the telemetry process to update metrics with the updated ones.
To solve this I added an appup transform to restart the prometheus metrics started by supervisor Archethic.Telemetry
Update project version, create a new appup with `mix distillery.gen.appup --app archethic`
instructions are just before the migration script
- New and …
=> Add appup transform to restart telemetry

Dockerfile
required since the application do not build it itsef anymore
```
2023-06-20 07:49:46.360 [notice] Application archethic exited: exited in: Archethic.Application.start(:normal, [])
** (EXIT) an exception was raised:
** (ErlangError) Erlang error: :enoent
(elixir 1.14.1) lib/system.ex:1060: System.cmd("upnpc", ["-s"], [])
(archethic 1.1.2) lib/archethic/networking/ip_lookup/nat_discovery/miniupnp.ex:32: Archethic.Networking.IPLookup.NATDiscovery.MiniUPNP.get_local_ip/0
(archethic 1.1.2) lib/archethic/networking/ip_lookup/nat_discovery/miniupnp.ex:25: Archethic.Networking.IPLookup.NATDiscovery.MiniUPNP.open_port/1
(archethic 1.1.2) lib/archethic/networking/port_forwarding.ex:21: Archethic.Networking.PortForwarding.try_open_port/2
(archethic 1.1.2) lib/archethic/application.ex:63: …
```
=> Add miniupnpc to the Dockerfile

Dockerfile
Seems because app folder is copied over the built assets.
Looks like COPYing the app folder once is sufficient to be able to build everything after
(Rebased over today's develop branch)
=> Bugfix : CSS assets are not available in the docker image

lib/archethic/bootstrap.ex, lib/archethic/self_repair.ex
There is an issue in the bootstrap sync restart strategy.
Currently when a repair crash we restart it until 10 tries, but we restart it with the last sync date received in parameter but not the one the failed repair succeeded to reach. 
Fixes it by restarting from the last sync date stored in memory
Also fixes an issue where the function bootstrap_sync do not return the expected :error atom
- New …
=> Fix bootstrap sync restart

lib/archethic/p2p.ex
Fixes an issue happening when the quorum needs to resend a request (acceptance resolver not passed or network issue on first nodes). The parameters consistency_level and timeout was inverted in the function call, resulting to timeout of 3ms.
=> Fix invalid parameter in quorum

lib/archethic/contracts/contract.ex, lib/archethic/p2p/message/validate_smart_contract_call.ex, test/archethic/p2p/message/validate_smart_contract_call_test.exs
Due to the verification of the recipients introduced in v1.2, it is now impossible to send calls to a contract that does not have a `trigger transaction`. This PR change the logic to: A contract must have a `condition transaction` to receive a call.
- Regression 
Unit tested & tested with playbook "Faucet" 
=> Smart Contracts: Allow a contract without trigger:transaction to receive calls

lib/archethic/p2p.ex, lib/archethic/p2p/mem_table.ex, lib/archethic/p2p/mem_table_loader.ex, test/archethic/p2p/mem_table_loader_test.exs
This PR fixes an issue when a node starts, it load the previous P2P view from DB but it does not set the availability_update field of a node with the latest value when the node was marked as unavailable.
This then lead to issue in self repair, mainly while verifying the replication attestation confirmations
Unit test
- Any dependent changes …
=> Fix P2P availability_update on bootstrap

lib/archethic_web/controllers/api/web_hosting_controller.ex, lib/archethic_web/controllers/api/web_hosting_controller/reference_transaction.ex, priv/json-schemas/aeweb.json, test/archethic_web/controllers/api/web_hosting_controller_test.exs
Add `publicationStatus` to hosting transactions
Fixes #1063
Unit tests + normal scenario
=> AEWeb: Handle publicationStatus in hosting tx

lib/archethic/db/embedded_impl/stats_info.ex, priv/migration_tasks/prod/1.2.2@stats_info.exs
Serialize nb_transaction & burned_fees on 64 bits instead of 32 bits.
Fixes #1059 
- Tested with data from mainnet
- Tested with hotreload after a benchmark
=> Change stats serialization

lib/archethic/beacon_chain/slot_timer.ex
Fixes an issue where the slot timer could have 2 timer in the same time
=> Cancel slot timer before creating a new one

lib/archethic/beacon_chain.ex, lib/archethic/self_repair/sync.ex
Decrease the concurrency while downloading the summary aggregate in self repair.
As they are processed one by one, there is no need to download more than 2 in a row
=> Reduce concurrency while downloading aggregate

lib/archethic.ex, lib/archethic/contracts/worker.ex, lib/archethic/mining.ex, lib/archethic/networking/scheduler.ex, lib/archethic/p2p/message/new_transaction.ex, lib/archethic_web/controllers/api/origin_key_controller.ex, lib/archethic_web/controllers/api/transaction_controller.ex, lib/archethic_web/controllers/faucet_controller.ex, lib/archethic_web/live/settings_live.ex, test/archethic_test.exs
Fixes an issue where a transaction which is forwarded because validation nodes are not responding or returns an synchronization, can create a loop of death between node if this transaction is also catched by node responsivness.
Now all transaction created by GenServer that also spawn a node responsivness, are not forwarded since node responsivness will do it
Fixes #1134 
Unit test
- New and existing …
=> Add new option to forward transaction

lib/archethic/db/embedded_impl/chain_index.ex
Fix pattern matching when retrieving genesis public key from last_address_index ets table
=> Fix ChainIndex get_genesis_address

lib/archethic/db/embedded_impl/stats_info.ex, priv/migration_tasks/prod/1.2.4@stats_info.ex
Fixes a problem where is was possible that the stats add several times the same beacon summary.
Also enhance the stats file, since only the last summary stats are used we don't need to store each sats for each summary
=> Fix stats adding multiple times same summary

lib/archethic/self_repair/sync.ex, test/archethic/self_repair/sync_test.exs
Fixes an issue in self repair where a node which is bootstrapping from start run the election based on the P2P view of the latest summary repaired while it should be on the current P2P view of the network (from the latest summary available)
Unit test
=> Run election on current node view in self repair

lib/archethic/self_repair/sync.ex, test/archethic/self_repair/sync_test.exs
There is some possibilities that the network patch in a beacon summary aggregate is nil.
In that case, when doing the self repair,  we add a default network patch with the node geo patch
Fixes #1136 
Unit test
Also add logs in function `update_p2p_availabilities` when running a single node (it create an aggregate with empty network patch list
- New and existing unit tests pass locally with my …
=> Add geo patch as default network patch

Makefile, shell.nix
This file allow people that use the [nix package manager](https://nixos.org/) to open a shell with all dependencies installed.
I use it on my env. I figured that may be useful to commit it?
=> Proposition: add shell.nix

lib/archethic/bootstrap/sync.ex
Fixes an issue where the availability update of the first enrolled node wasn't the good one when a node bootstraps
=> Fix p2p node info on first enrolled node

config/config.exs, lib/archethic/beacon_chain/network_coordinates.ex, test/archethic/beacon_chain/network_coordinates_test.exs
Update config to set Nx default backend to EXLA.
This speed up network patch calculation by 2 - 3 times
Getting mainnet network patch matrix :
[test.txt](https://github.com/archethic-foundation/archethic-node/files/11957075/test.txt)
Run these command with and without the conf : 
```elixir
nx = File.read!("/home/neylix/Archethic/archethic-node/test.txt") |> :erlang.binary_to_term()
start = System.monotonic_time(:millisecond)
Archethic.BeaconChain.NetworkCoordinates.get_patch_from_latencies(nx)
System.monotonic_time(:millisecond) - start
```
result on my computer is 2800ms without config and 800ms with the new config
- I …
=> Set Nx backend to EXLA

lib/archethic/utils/regression/playbook.ex
The goal of this PR is to fix calls to the testnet (and probably mainnet too) made from the playground, because the protocol isn't passed to all the function (so the default `:http` value is used, and it should be `:https` on testnet for example)
Locally
=> fix playbook: pass proto params to functions

lib/archethic/beacon_chain.ex, lib/archethic/beacon_chain/network_coordinates.ex, lib/archethic/beacon_chain/slot/validation.ex, lib/archethic/beacon_chain/summary_aggregate.ex, test/archethic/beacon_chain/network_coordinates_test.exs, test/archethic/beacon_chain/slot/validation_test.exs, test/archethic/beacon_chain/summary_aggregate_test.exs, test/archethic/beacon_chain_test.exs
Add verification when working on p2p view on beacon chain.
Add control as described in issue
Fixes #1042 
Added Unit tests
=> Fix p2 p view validation

lib/archethic/beacon_chain/slot_timer.ex, lib/archethic/beacon_chain/subset.ex, test/archethic/beacon_chain/slot_timer_test.exs, test/archethic/beacon_chain/subset_test.exs
Fixes an issue where a node keeps in Subset state the last slot it created before going down (event node_down), and send this slot after going up (event node_up).
This slot was then added to the beacon summary even if the data are from the previous summary
Run 2 nodes, create a transaction and send to one a node_down event before a the end of slot and send a node_up after the summary, a log warning informs that the slot was from a previous date and the first page of beacon summary does not contains the transaction of the previous summary …
=> Fix invalid slot time

priv/json-schemas/aeweb.json, test/archethic/mining/pending_transaction_validation_test.exs
Schema is more strict (additionalProperties set to false)
Use subschemas for readability
Add a few tests
Unit tests
=> AEWeb: schema is more strict

lib/archethic/contracts.ex, lib/archethic/contracts/contract.ex, lib/archethic/contracts/interpreter.ex, lib/archethic/contracts/interpreter/action_interpreter.ex, lib/archethic/contracts/interpreter/common_interpreter.ex, lib/archethic/contracts/interpreter/condition_interpreter.ex, lib/archethic/contracts/interpreter/function_interpreter.ex, lib/archethic/contracts/interpreter/scope.ex, test/archethic/contracts/interpreter/action_interpreter_test.exs, test/archethic/contracts/interpreter/condition_interpreter_test.exs, test/archethic/contracts/interpreter/function_interpreter_test.exs, test/archethic/contracts/interpreter_test.exs, test/support/template.ex
Add possibility to create and use custom functions in Smart contracts.
However, I have a failing test which is not concerned by anything i changed:
```
doctest Archethic.Crypto.sign/2 (28) (CryptoTest)
test/archethic/crypto_test.exs:15
```
Multiple tests on :
- FunctionInterpreter
- ActionInterpreter
- ConditionInterpreter
- Interpreter
- New and …
=> Smart contract functions without args

lib/archethic/db/embedded_impl/bootstrap_info.ex, mix.exs
though its not user-data , but still.
=> use PlugCrypto binary to term in bootstrap.info

lib/archethic/contracts/interpreter/common_interpreter.ex
Fixes the SC `log` function so we can still use it for dev purpose
Used log function in playground, it works well
=> Fix SC log function

lib/archethic/contracts/interpreter.ex, lib/archethic/contracts/interpreter/legacy.ex
Remove `String.trim` on code before parsing to avoid incoherence in line number
=> Remove String.trim before parsing code

lib/archethic/contracts/interpreter/library/common/chain.ex, lib/archethic/contracts/interpreter/library/common/chain_impl.ex, test/archethic/contracts/interpreter/library/common/chain_test.exs
Implement `Chain.get_transaction/1`
Fixes #1167
Unit tested
=> Add Chain.get_transaction/1

lib/archethic/contracts/interpreter/action_interpreter.ex, lib/archethic/contracts/interpreter/common_interpreter.ex, lib/archethic/contracts/interpreter/condition_validator.ex, lib/archethic/contracts/interpreter/function_interpreter.ex, lib/archethic/contracts/interpreter/scope.ex, test/archethic/contracts/interpreter/scope_test.exs
This pr refactores the Scope module so that the scope is entirely handled by it. 
non-breaking change
New tests for the scope module have been added
=> Scope refactor

lib/archethic/contracts/interpreter.ex, lib/archethic/contracts/interpreter/condition_validator.ex, lib/archethic/contracts/interpreter/library.ex, lib/archethic/contracts/interpreter/library/common/code.ex, test/archethic/contracts/interpreter/library/common/code_test.exs
In some case we need to compare code inside a smart contract. Instead of comparing strings, we can tokenize the code and ensure the two codes behave the same even if strings are not literally the same.
To do it I updated the sanitize code function to remove the metadata about code (such as line, colum ...) as it only the AST instructions can be compared
Unit tests and SC playground
- New and …
=> Add new Code module in SC library

priv/json-schemas/aeweb.json
AEWeb schema is missing attribute `hashFunction`.
- 
Used AEWeb cli and AEWeb front app, both works well
=> Fix aeweb schema, add hashFunction

lib/archethic/contracts/interpreter/library/common/string.ex, test/archethic/contracts/interpreter/library/common/string_test.exs
To not allow developer to interact with binaries, we can let them convert any string in hexadecimal format and concatenate hex representation of string.
Fixes #1160 
Unit tests
=> String.to_hex now encode any string in hex

lib/archethic/contracts/interpreter.ex, lib/archethic/contracts/interpreter/action_interpreter.ex, lib/archethic/contracts/interpreter/common_interpreter.ex, lib/archethic/contracts/interpreter/condition_interpreter.ex, lib/archethic/contracts/interpreter/function_interpreter.ex, lib/archethic/contracts/interpreter/library.ex, lib/archethic/contracts/interpreter/library/common/chain_impl.ex, lib/archethic/contracts/interpreter/library/common/code.ex, lib/archethic/contracts/interpreter/library/common/contract.ex, lib/archethic/contracts/interpreter/library/common/crypto.ex, lib/archethic/contracts/interpreter/library/common/http_impl.ex, lib/archethic/contracts/interpreter/library/common/json.ex, lib/archethic/contracts/interpreter/library/common/list.ex, lib/archethic/contracts/interpreter/library/common/map.ex, lib/archethic/contracts/interpreter/library/common/regex.ex, lib/archethic/contracts/interpreter/library/common/string.ex, lib/archethic/contracts/interpreter/library/common/time.ex, lib/archethic/contracts/interpreter/library/common/token_impl.ex, lib/archethic/contracts/interpreter/library/contract.ex, lib/tag.ex, test/archethic/contracts/interpreter/action_interpreter_test.exs, test/archethic/contracts/interpreter/condition_interpreter_test.exs, test/archethic/contracts/interpreter/function_interpreter_test.exs, test/archethic/contracts/interpreter/library/contract_test.exs, test/archethic/contracts/interpreter_test.exs, test/archethic_web/api/jsonrpc/methods/call_contract_function_test.exs, test/tag_test.exs
=> restrict smart contract functions

lib/archethic/mining/pending_transaction_validation.ex, lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations.ex, priv/json-schemas/token-core.json, priv/json-schemas/token-resupply.json, test/archethic/mining/pending_transaction_validation_test.exs
Implement AEIP-18: token resupply
Fixes #1174 
Manual scenario:
- create a fungible token
- create a resupply transaction
- utxos should have the same token_address
plus a few unit tests
=> AEIP-18 token resupply implementation

lib/archethic/bootstrap/network_init.ex, lib/archethic/mining/fee.ex, lib/archethic/mining/pending_transaction_validation.ex, lib/archethic/mining/standalone_workflow.ex, lib/archethic/mining/validation_context.ex, lib/archethic/replication/transaction_validator.ex, lib/archethic/transaction_chain/transaction.ex, lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations.ex, priv/json-schemas/token-core.json, priv/json-schemas/token-resupply.json, test/archethic/mining/distributed_workflow_test.exs, test/archethic/mining/fee_test.exs, test/archethic/mining/pending_transaction_validation_test.exs, test/archethic/mining/validation_context_test.exs, test/archethic/replication_test.exs, test/archethic/transaction_chain/transaction/validation_stamp/ledger_operations_test.exs, test/archethic/transaction_chain/transaction_test.exs, test/support/transaction_factory.ex
/!\ Base branch 1174-token-resupply (AEIP-18) 
This is AEIP-19 implementation. This adds a `recipients` field in the token transactions. Minted tokens can be sent to recipients in the same transaction.
Fixes #1175 
Scenario 1: Create a token with recipients
```yaml
transaction_type: token
content: |
{
"supply": 10000000000,
"type": "fungible",
"decimals": 8,
"name": "COINCOIN",
"allow_mint": true,
"recipients": [
{"to": "00002223bbd4ec3d64ae597696c7d7ade1cee65c639d885450ad2d7b75592ac76afa", "amount": 333}
],
"aeip": [2, 18]
}
```
```
go run main.go send-transaction --config newtoken.yaml --access-seed bastien --index 0
```
- Check the movements in resulting
Scenario 2: 
- Create a resupply with recipients
```yaml …
```
=> AEIP-19 token recipients

lib/archethic_web/api/ecto_schemas/transaction_payload.ex, lib/archethic_web/api/jsonrpc/method.ex, lib/archethic_web/api/jsonrpc/methods/add_origin_key.ex, lib/archethic_web/api/jsonrpc/methods/call_contract_function.ex, lib/archethic_web/api/jsonrpc/methods/estimate_transaction_fee.ex, lib/archethic_web/api/jsonrpc/methods/send_transaction.ex, lib/archethic_web/api/jsonrpc/methods/simulate_contract_execution.ex, lib/archethic_web/api/rest/controllers/transaction_controller.ex, test/archethic_web/api/ecto_schemas/transaction_payload_test.exs, test/archethic_web/api/jsonrpc/controllers/jsonrpc_controller_test.exs, test/archethic_web/api/jsonrpc/methods/estimate_transaction_fee_test.exs, test/archethic_web/api/jsonrpc/methods/send_transaction_test.exs, test/archethic_web/api/jsonrpc/methods/simulate_contract_execution_test.exs
Wrap the transaction payload inside a "transaction" object for these 3 methods: `SimulateContractExecution`, `EstimateTransactionFee` and `SendTransaction`.
Fixes #1225
**This require the 3 SDKs to be updated.**
Unit tested …
=> JSON RPC methods that used transaction as payload now only takes 1 param

lib/archethic/contracts/interpreter/library/common/map.ex, test/archethic/contracts/interpreter/library/common/map_test.exs
Add new `Map.delete/2` function in SC library
Unit test
=> Add Map.delete function in SC

lib/archethic/mining.ex, lib/archethic/mining/fee.ex, lib/archethic/mining/validation_context.ex, test/archethic/mining/distributed_workflow_test.exs, test/archethic/mining/fee_test.exs, test/archethic/mining/validation_context_test.exs, test/archethic/replication_test.exs, test/archethic_web/api/rest/controllers/transaction_controller_test.exs, test/support/transaction_factory.ex
The idea is to ensure a bulk transaction to be more cost efficient than multiple transactions. 
Indeed, the validation is done one time versus multiple times.
The cost is then determined as logarithmic according to the number of recipients
Fixes #1041 
- Unit tests
- Multiple recipients sending with CLI
=> Adapt the fee for multi recipients transactions

lib/archethic/contracts.ex, lib/archethic/contracts/contract.ex, lib/archethic/contracts/contract/conditions.ex, lib/archethic/contracts/interpreter.ex, lib/archethic/contracts/interpreter/action_interpreter.ex, lib/archethic/contracts/interpreter/condition_interpreter.ex, lib/archethic/contracts/interpreter/condition_validator.ex, lib/archethic/contracts/interpreter/legacy.ex, lib/archethic/contracts/interpreter/legacy/condition_interpreter.ex, lib/archethic/contracts/worker.ex, lib/archethic/mining/proof_of_work.ex, lib/archethic/p2p/message/validate_smart_contract_call.ex, lib/archethic_web/api/jsonrpc/methods/simulate_contract_execution.ex, test/archethic/contracts/contract_test.exs, test/archethic/contracts/interpreter/condition_interpreter_test.exs, test/archethic/contracts/interpreter/legacy/condition_interpreter_test.exs, test/archethic/contracts/interpreter_test.exs, test/archethic/contracts_test.exs
Fixes an issue where condition code was not found if the name of args in a named condition are not the same as the one in the named action
Unit test + manuel testing
=> Refactor named action to use arity as key

lib/archethic/contracts.ex, lib/archethic/contracts/interpreter.ex, lib/archethic/contracts/interpreter/function_interpreter.ex, lib/archethic_web/api/jsonrpc/error.ex, lib/archethic_web/api/jsonrpc/methods/call_contract_function.ex, test/archethic/contracts/interpreter/function_interpreter_test.exs, test/archethic/contracts_test.exs
Add a timeout for the execution of public functions.
Fixes #1231
Unit test + API call
=> Smart Contracts: Limit public function execution to 500ms

lib/archethic/oracle_chain/services/hydrating_cache.ex, test/archethic/oracle_chain/services/hydrating_cache_test.exs
Fix a bug in the HydratingCache: 
When the hydrate function took more than 5s, the task was shutdown and the timer was not resetted, resulting in a genserver waiting forever.
Fixes #1154 
Unit tested
=> HydratingCache now properly handles a timeout of the hydrate function

config/config.exs, lib/archethic/transaction_chain/transaction/data/recipient.ex, lib/archethic/utils.ex, lib/archethic_web/api/jsonrpc/methods/estimate_transaction_fee.ex, lib/archethic_web/api/jsonrpc/methods/send_transaction.ex, lib/archethic_web/api/jsonrpc/methods/simulate_contract_execution.ex, lib/archethic_web/api/jsonrpc/schemas/transaction.ex, priv/json-schemas/schemas/base/address.json, priv/json-schemas/schemas/base/hexadecimal.json, priv/json-schemas/schemas/base/public_key.json, priv/json-schemas/schemas/list/authorized_keys.json, priv/json-schemas/schemas/list/ownerships.json, priv/json-schemas/schemas/list/recipients.json, priv/json-schemas/schemas/list/token_transfers.json, priv/json-schemas/schemas/list/uco_transfers.json, priv/json-schemas/schemas/object/authorized_key.json, priv/json-schemas/schemas/object/ledger.json, priv/json-schemas/schemas/object/ownership.json, priv/json-schemas/schemas/object/recipient.json, priv/json-schemas/schemas/object/token_transfer.json, priv/json-schemas/schemas/object/transaction_data.json, priv/json-schemas/schemas/object/uco_transfer.json, priv/json-schemas/transaction.json, test/archethic_web/api/jsonrpc/controllers/jsonrpc_controller_test.exs, test/archethic_web/api/jsonrpc/methods/estimate_transaction_fee_test.exs, test/archethic_web/api/jsonrpc/methods/send_transaction_test.exs, test/archethic_web/api/jsonrpc/methods/simulate_contract_execution_test.exs, test/archethic_web/api/jsonrpc/schemas/transaction_test.exs
Remove the base16 format for the transaction content.
Created new Json Schema validation method.
Fixes #1234
Unit tests
=> Json RPC endpoint does not require content to be base16

lib/archethic/contracts/interpreter/library/common/http_impl.ex, test/archethic/contracts/interpreter/library/common/http_impl_test.exs
limit Http module to 1 call per SC
Fixes #1186
Unit tested 
=> Smart Contracts: limit Http module to 1 call per SC

lib/archethic_cache/lru.ex, test/archethic/db/embedded_impl/chain_index_test.exs
This remove the need to have a list of all values
and have to implement costly move key to front or eviction.
The implementation will leverage mainly key value & atomic counter operations.
Fixes #1089
- Enhancements
=> Transform the LRU cache to use ETS with pointer to head/tail

lib/archethic/contracts.ex, lib/archethic/contracts/interpreter/legacy/utils_interpreter.ex, lib/archethic/contracts/interpreter/library/common/contract.ex, test/archethic/contracts/interpreter/library/common/contract_test.exs
Add a new function in Contract module in SC library to allow user to call a public function from a contract
Unit test
Manuel testing with those contract
```elixir
@version 1
export fun add(x, y) do
x + y
end
```
```elixir
@version 1
condition transaction: []
actions triggered_by: transaction do
address = 0x0000c32fd6b33c9ff557ad8826f516c1c81d0242524be10891a009b77c50e252bcc5
res = Contract.call_function(address, "add", [1, 2])
Contract.set_content res
end
```
triggered second contract and result transaction contained 3 in content …
=> Add Contract.call_function in SC language

lib/archethic/contracts/interpreter.ex, lib/archethic/contracts/interpreter/condition_interpreter.ex, test/archethic/contracts/interpreter/condition_interpreter_test.exs, test/archethic/contracts/interpreter/condition_validator_test.exs, test/archethic/contracts/interpreter/library/common/code_test.exs, test/archethic/contracts/interpreter/library/common/time_test.exs, test/archethic/contracts/interpreter_test.exs, test/archethic/contracts/worker_test.exs, test/archethic/contracts_test.exs, test/archethic/p2p/message/validate_smart_contract_call_test.exs, test/archethic_web/api/jsonrpc/methods/call_contract_function_test.exs, test/archethic_web/api/jsonrpc/methods/simulate_contract_execution_test.exs, test/support/contract_factory.ex
New syntax: `condition triggered_by: transaction, as: []`
Legacy `condition transaction: []` is kept
Unit tested
=>  Smart Contracts: new syntax for condition block

lib/archethic/contracts/interpreter/library/common/contract.ex, test/archethic/contracts/interpreter/library/common/contract_test.exs, test/support/transaction_factory.ex
Currenty ownerships are chainned when creating a new smart contract transaction.
This create problem when we want to use them mainly to remove one or update one.
To have a quick fix waiting a proper solution I created a function `Contract.clear_ownerships` to clear all the ownerships (expect the contract seed) from the next transaction
Unit tested
- New and existing unit tests pass locally …
=> Add function Contract.clear_ownerships in SC

lib/archethic/contracts.ex, lib/archethic/contracts/interpreter.ex
Remove the logs of 2 scenarios:
- Incorrect smart contract's code
- Incorrect public function call
We don't want to see that in the logs.
Example of logs that are removed:
```
2023-09-07 12:32:23.479 [error] Task #PID<0.4837.0> started from #PID<0.4780.0> terminating
** (Protocol.UndefinedError) protocol String.Chars not implemented for %{"address" => 1} of type Map
(elixir 1.14.1) lib/string/chars.ex:3: String.Chars.impl_for!/1
(elixir 1.14.1) lib/string/chars.ex:22: String.Chars.to_string/1
nofile:8: (file)
(elixir 1.14.1) src/elixir.erl:298: anonymous fn/4 in :elixir.eval_external_handler/1
(stdlib 4.1.1) erl_eval.erl:748: :erl_eval.do_apply/7
(stdlib 4.1.1) eval_bits.erl:106: :eval_bits.eval_field/5
(stdlib 4.1.1) eval_bits.erl:71: :eval_bits.expr_grp1/6
(stdlib 4.1.1) …
```
=> Smart Contracts: remove error logs that are coming from a user error

lib/archethic/contracts/interpreter/scope.ex, test/archethic/contracts/interpreter/scope_test.exs
To avoid having them available as "global variables".
=> Smart Contracts: Use atoms instead of strings for scope_hierarchy & context_list

lib/archethic/contracts/interpreter/library/common/contract.ex, lib/archethic/contracts/interpreter/library/common/contract_impl.ex
We need to be able to mock it in the playground
- Refactor
Manual test via playground
=> Smart Contracts: Contract.call_function/3 mockable

lib/archethic/contracts.ex, lib/archethic/contracts/interpreter.ex, lib/archethic/contracts/interpreter/common_interpreter.ex, lib/archethic/contracts/interpreter/library/common/http_impl.ex, lib/archethic_web/api/jsonrpc/error.ex, lib/archethic_web/api/jsonrpc/methods/simulate_contract_execution.ex, lib/archethic_web/api/rest/controllers/transaction_controller.ex, test/archethic/contracts/interpreter_test.exs, test/archethic_web/api/jsonrpc/error_test.exs
Contract execution error used to return always the same error. No more.
This is a first step in direction of #1197
Unit tests + Playground
=> Contract execution return explicit errors instead of contract_failure

lib/archethic/contracts/interpreter.ex, lib/archethic/mining/validation_context.ex, test/archethic/contracts/interpreter_test.exs
In the transaction, the user can put many recipients with named actions.
In the validation stamp, the list of resolved address for the recipient was not sorted in the same order. This was causing error in the contract loader triggering a contract with the wrong named action
Also fix a bug where the error formatter fail if a parameter is a map
Created a transaction with 2 recipient for different contract with different named action.
The contracts are called with the right parameters
- My changes generate no new …
=> Fix validation stamp resolved recipient order

lib/archethic/contracts/interpreter/ast_helper.ex, test/archethic/contracts/interpreter/function_interpreter_test.exs
This PR improve the return of an arithmetic expression in SC language.
Now the function return an integer of both operands are integer (if result does not contains decimals), if one operand is a float, expression returns a float
Doctests
=> Fix arithmetic with float

lib/archethic/contracts/interpreter/library/common/crypto.ex, test/archethic/contracts/interpreter/library/common/crypto_test.exs
Add new Crypto function to perform HMAC.
This function takes 3 parameters:
- data => the data to be hashed
- algo => the algo to use (sha256, sha512, sha3_256, sha3_512), default sha256
- key => the secret key, default is the sha256 hash of the storage nonce <> seed of contract
Unit test
- Any dependent changes have been merged and …
=> Add new SC function Crypto.hmac/2

lib/archethic/contracts/interpreter/library/common/chain.ex, lib/archethic/contracts/interpreter/library/common/chain_impl.ex, test/archethic/contracts/interpreter/library/common/chain_test.exs
Add new functions in Chain module:
- get_previous_address => return the previous address from previous public key or a transaction
- get_balance => return a map containing the balance of uco and tokens
- get_uco_balance => return the amount of uco
- get_token_balance => return the amount of token
- get_tokens_balance => return a map of token as for the get_balance but only with selected tokens
balance returns a map as 
```elixir
[
uco: 1234,
tokens: [
[token_address: "1234", token_id: 0]: 1234,
[token_address: "123456", token_id: 1]: 1,
]
]
```
It can be used like this 
```elixir
balance = Chain.get_balance(previous_address)
token = [
token_address: 0x000123...,
token_id: 0
]
token_balance = Map.get(balance.tokens, token, 0)
token_balance >= amount
```
- New feature (non-breaking change …
=> SC new Chain functions

lib/archethic/contracts/interpreter/library/common/chain.ex, lib/archethic/contracts/interpreter/library/common/chain_impl.ex, test/archethic/contracts/interpreter/library/common/chain_test.exs
Add new functions in SC Chain module:
- `get_last_address(address)` => return the last address of a chain
- `get_last_transaction(address)` => return the last transaction of chain or nil
Unit tests
=> Add new Chain functions get_last_transaction and get_last_address

lib/archethic/contracts/contract.ex, lib/archethic/crypto.ex, lib/archethic/transaction_chain/transaction.ex, test/archethic/transaction_chain/transaction_test.exs
This PR fixes a bug when a Worker create a transaction for a contract where the previous public key of the contract is not the default origin `:software`.
This create the transaction with another previous public and so the previous address is different than the real previous address. So the validation retrieve a previous transaction nil and cannot validate the transaction.
To fix this, the function `Transaction.new` now take the origin in parameters …
=> Worker uses origin from previous public key

lib/archethic_web/api/jsonrpc/methods/estimate_transaction_fee.ex
Since this PR https://github.com/archethic-foundation/archethic-node/pull/1288, users have to pay fees for the smart contract they trigger in the recipients. This fee calculation was not added to the estimate transaction fee API.
This PR fixes it by adding the same behavior in the estimation than in the validation context
Tested manually with JSON RPC request
- New and existing unit tests pass …
=> Recipient fees calculation on estimate transaction fee

lib/archethic/self_repair.ex
Because the load_missed_transactions can exit, it does not retry as expected. I added the catch so it does retry properly.
Fixes #1294
=> Catch the exit of the load_missed_transactions function

lib/archethic/contracts/worker.ex, lib/archethic/mining.ex, lib/archethic/mining/fee.ex, lib/archethic/mining/validation_context.ex, lib/archethic/replication/transaction_validator.ex, lib/archethic_web/api/jsonrpc/methods/estimate_transaction_fee.ex, test/archethic/mining/distributed_workflow_test.exs, test/archethic/mining/fee_test.exs, test/archethic/mining/validation_context_test.exs, test/archethic/p2p/message/validate_smart_contract_call_test.exs, test/support/transaction_factory.ex
Since the user pay the fee for a contract trigger in recipient, the control in the Worker to ensure the contract has the minimum fees is not relevant anymore so it is delete.
Also if a contract call another contract it's transaction was free but we added after the recipient fee which was not logical since the user should pay the fee for this as well
Tested with a contract that call another contract (bridge workflow) the contract has no fund but the transaction is still passing
- My changes generate no new …
=> Update recipient fee calculation

lib/archethic_web/explorer/templates/explorer/chain.html.heex, lib/archethic_web/explorer/templates/explorer/transaction_details.html.heex, lib/archethic_web/web_utils.ex, test/archethic_web/web_utils_test.exs
Fix a round issue in UI.
with the number 18446744073709500000, the displayed result was wrong:
BEFORE
AFTER
+ unit test
=> Fix WebUtils.to_float precision issue and rename it to from_bigint

lib/archethic/contracts/interpreter/library/common/evm.ex, lib/archethic/mining.ex, lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations.ex, lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations/unspent_output.ex, test/archethic/p2p/message/validate_smart_contract_call_test.exs
This PR handle the unspent outputs with an amount over 2^64 - 1. 
Now the amount of an utxo is encoded using VarInt
Fixes #1276
Using blockchain and explorer normally.
Also started a node without the change, stopped the node, restarted it with the change.
Everything still work for old and new utxo serialization
- Any dependent changes have …
=> Handle inputs amount overflow over 2^64

lib/archethic/contracts/interpreter/library/common/evm.ex
Some modifications regarding Evm library:
- Fix a bug where the check_type of `abi_decode` was not set
- `abi_encode` returns the hex string with "0x"
=> Fixes SC Evm library

lib/archethic_web/explorer/controllers/explorer_root_controller.ex
Fixes an issue where aeweb do not correctly retrieve the aeweb reference address on the referer header.
Error was caused by an incorrect Regex pattern when the url does not end with a slash after the address.
Also added "aeweb" endpoint in referer Regex pattern and use this new endpoint as default redirection.
Tested with archethic website
- …
=> Fix aeweb referer

lib/archethic.ex, lib/archethic/p2p.ex, lib/archethic/self_repair/network_chain.ex, lib/archethic/transaction_chain.ex, test/archethic/p2p_test.exs, test/archethic/self_repair/network_chain_test.exs, test/archethic/transaction_chain_test.exs, test/archethic_test.exs
We were only asking the 3 closest nodes, but that's a mistake. For example, if multiple close nodes are desynchronized, they will never be able to be synchronized since they all ask each other.
Fixes #1320
Unit test
=> NetworkSync.validate_address ask more nodes about the latest address

config/config.exs, lib/archethic/oracle_chain/services/uco_price/providers/coin_marketcap_archethic.ex, lib/archethic/oracle_chain/services/uco_price/providers/coin_marketcap_uniris.ex, test/archethic/oracle_chain/services/uco_price/coin_marketcap_test.exs
The CoinMarketCap url will soon change from `/uniris` to `/archethic`.
This PR handles both so the transition is smooth
Fixes #1328
Tested the release upgrade, the 2 new providers take over the old one.
=> Coinmarketcap provider duplication

lib/archethic_web/api/jsonrpc/controllers/jsonrpc_controller.ex
Default timeout set to 30s instead of 5s
Fixes #1336
not tested 👼 
=> Default RPC Timeout to 30s

lib/archethic/mining/validation_context.ex, test/archethic/mining/validation_context_test.exs
Fix concensus error but using the `validation_time` instead of the `cross_validation_time` for the fees calculations
Fixes #1344
Unit tests
=> Consensus error due to wrong timestamp used

lib/archethic/mining/distributed_workflow.ex, lib/archethic/mining/standalone_workflow.ex, lib/archethic/mining/validation_context.ex, lib/archethic/p2p/message/replicate_transaction.ex, lib/archethic/replication/transaction_validator.ex, lib/archethic/transaction_chain.ex, lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations/transaction_movement.ex, lib/archethic_web/api/jsonrpc/methods/estimate_transaction_fee.ex, test/archethic/mining/validation_context_test.exs, test/archethic/transaction_chain/transaction/validation_stamp/ledger_operations/transaction_movement_test.exs, test/archethic/transaction_chain/transaction/validation_stamp/ledger_operations_test.exs, test/archethic/transaction_chain/transaction_test.exs
Fix a edge case on movements
Fixes #1334
Unit tested
=> Fix issue when resolving addresses and there were multiple movements with the same address

config/test.exs, lib/archethic/p2p/message/get_unspent_outputs.ex, test/archethic/p2p/message/get_unspent_outputs_test.exs, test/archethic/p2p/messages_test.exs
Fixes #1316 
Refactor
Unit tested
=> GetUnspentOutputs optimization

lib/archethic/election.ex
This PR aims to resolve the problem of concentration in the validation node election due to an invalid statement in the election algorithm refinement (when there is not enough nodes to validate the constraints)
Fixes #1353  …
=> Fix sort of nodes during election's refinement

lib/archethic/beacon_chain/slot_timer.ex, lib/archethic/beacon_chain/summary_timer.ex, lib/archethic/contracts/worker.ex, lib/archethic/networking/scheduler.ex, lib/archethic/oracle_chain.ex, lib/archethic/oracle_chain/scheduler.ex, lib/archethic/oracle_chain/services/hydrating_cache.ex, lib/archethic/reward/scheduler.ex, lib/archethic/self_repair.ex, lib/archethic/self_repair/scheduler.ex, lib/archethic/shared_secrets/node_renewal_scheduler.ex, lib/archethic/utils.ex
Fixes an issue where the function `Utils.time_offset` returned the offset in second, but this was creating scheduler to be non really accurate because of milliseconds 
Alos refactored `Utils.next_date` to be more friendly to use
=> Utils.time_offset is more accurate

config/test.exs, lib/archethic/application.ex, lib/archethic/beacon_chain/network_coordinates.ex, lib/archethic/beacon_chain/subset.ex, lib/archethic/beacon_chain/subset/stats_collector.ex, lib/archethic/beacon_chain/subset/summary_cache.ex, lib/archethic/beacon_chain/subset/supervisor.ex, lib/archethic/p2p/message/get_network_stats.ex, lib/archethic/pub_sub.ex, lib/archethic/self_repair/scheduler.ex, lib/archethic/utils/job_cache.ex, test/archethic/beacon_chain/network_coordinates_test.exs, test/archethic/beacon_chain/subset/stats_collector_test.exs, test/archethic/beacon_chain/subset/summary_cache_test.exs, test/archethic/beacon_chain/subset_test.exs, test/archethic/p2p/message/get_network_stats_test.exs, test/archethic/utils/job_cache_test.exs
The GetNetworkStats message is called by many nodes at the same time, the computation it does is heavy. I added a JobCache so the computation is only done once (cache reset after 30s). 
I also added a 5s timer which is bigger than the 3s default.
Fixes #1325
This can only be tested in stress condition. I'll setup some test environment tomorrow.
- New and existing unit tests pass locally with my …
=> GetNetworkStats improvment: timeout & caching

lib/archethic/db/embedded_impl/chain_reader.ex, test/archethic/db/embedded_impl_test.exs
When exploring a chain that have a multiple of ten transactions, the last page could not load and crashed.
Unit-tests and manual testing
=> Fix bug when there are 10 txs in last page

lib/archethic_web/api/graphql/schema/transaction_type.ex
Since AEIP-14 smart contracts have the possibility to create a state stored in a new UTXO.
However this new UTXO content was not accessible through graphql API.
This PR update the unspent_outputs graphql schemas to add the state.
Created a smart contract using state and request it's state using graphql
- Any dependent changes have …
=> Add state unspent outputs in graphql

lib/archethic/transaction_chain.ex
Sometimes, there may be multiple times the same address in movements/recipients. No need to resolve the duplicates, so I added a `.uniq`.
- optimization
unit tests still passes
=> Resolve distinct addresses

lib/archethic/mining/validation_context.ex, test/archethic/mining/validation_context_test.exs
The message for `NotifyPreviousChain` uses an index to specify the node. The index was based on `authorized_and_available_nodes` on sender and on the `chain_storage_nodes` on the receiver end.
Fixes #1331 
Unit tested
=> Fix issue in Notify workflow

lib/archethic/p2p/listener_protocol.ex
- Handle messages that are atoms 
- Handle messages that does not decode 
=> ListenerProtocol catch errors

lib/archethic/account/mem_tables_loader.ex, lib/archethic/bootstrap/network_init.ex, lib/archethic/mining.ex, lib/archethic/mining/validation_context.ex, lib/archethic/replication/transaction_validator.ex, lib/archethic/transaction_chain/transaction.ex, lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations.ex, lib/archethic_web/explorer/components/amount.ex, lib/archethic_web/explorer/live/transaction_details_live.ex, lib/archethic_web/explorer/live/transaction_details_live.html.heex, test/archethic/contracts/constants_test.exs, test/archethic/contracts/interpreter/action_interpreter_test.exs, test/archethic/contracts/interpreter/condition_validator_test.exs, test/archethic/mining/distributed_workflow_test.exs, test/archethic/mining/validation_context_test.exs, test/archethic/transaction_chain/transaction/validation_stamp/ledger_operations_test.exs, test/archethic/transaction_chain/transaction_test.exs, test/support/transaction_factory.ex
This PR update the behavior of converting MUCO to UCO. The conversion is now done during the validation in the movements.
Updated the explorer view to display the conversion
Fixes #1368
- Unit tests
- Update the reward address of a node (localhost:4000/settings)
Using the chain of the new reward address, send the MUCO to another address, in the validation stamp the movement is UCO.
- Also created a transfer of MUCO before applying this PR, then applied the PR with new explorer behavior, it works as it was previously (just display MUCO) …
=> MUCO to UCO in transaction movements

lib/archethic.ex, lib/archethic/db.ex, lib/archethic/db/embedded_impl.ex, lib/archethic/db/embedded_impl/chain_reader.ex, lib/archethic/p2p/message/get_transaction_chain.ex, lib/archethic/p2p/message/transaction_list.ex, lib/archethic/replication/transaction_context.ex, lib/archethic/transaction_chain.ex, lib/archethic_web/api/graphql/schema.ex, lib/archethic_web/api/graphql/schema/datetime_type.ex, lib/archethic_web/api/graphql/schema/resolver.ex, lib/archethic_web/explorer/live/chains/transaction_chain_live.ex, test/archethic/bootstrap/network_init_test.exs, test/archethic/db/embedded_impl_test.exs, test/archethic/p2p/messages_test.exs, test/archethic/transaction_chain_test.exs
This PR adds a new filter "from" in `transaction_chain` graphql request. This filter is a timestamp allow user to request the transaction from a specific date.
Unit tests + playing with graphiql interface to request multiple date and order on a chain
=> Graphql transaction_chain from filter

lib/archethic/contracts/interpreter/scope.ex, test/archethic/contracts/interpreter/scope_test.exs
Fixes an issue in smart contract language where it could be possible for a user to have an atom in a variable.
When assigning a value to a variable, we call `Scope.write_cascade`, this function was returning `:ok`. The problem was that we could create a function where the last statement is a assignation, and so the function returns `:ok`
```elixir
action ... do
my_var = bad_return()
log(my_var) 
end
fun bad_return() do
var = "toto"
end
```
The fix is to have the same behavior than elixir, the assignation return the assigned value
Create a simple contract with a function that assign a value in it's last statement
- I have commented my …
=> Scope assignation returns assigned value

lib/archethic_web/explorer/live/transaction_details_live.html.heex
Fix a regression I introduced with rebranding.
Liveview was crashing when trying to display a "KO" transaction
=> Fix regression on the explorer with invalid transactions

lib/archethic_web/explorer/live/chains/oracle_chain_live.ex, lib/archethic_web/explorer/live/chains/oracle_chain_live.html.heex
Before the page loads Oracle's data from transaction itself and decoded it, while it could be retrieved directly from the memory tables.
- Enhancement
=> fix 🐛 (explorer): Use memory values for Oracle's explorer page

lib/archethic/beacon_chain/network_coordinates.ex, lib/archethic/beacon_chain/subset.ex, lib/archethic/beacon_chain/subset/stats_collector.ex, lib/archethic/p2p/message/get_network_stats.ex, test/archethic/beacon_chain/network_coordinates_test.exs, test/archethic/beacon_chain/subset/stats_collector_test.exs
The network patch calculation takes up to 15seconds in testnet. The timeout values were too low. 
This PR calculate the timeout based on the next SelfRepair tick. 
In practice, we're setting the timeout to 4m30s instead of 5s.
locally with 3 nodes
=> Use the same timeout on all tasks related to network patches

lib/archethic_web/explorer/components/transactions_list.ex
Fix a regression introduced on the explorer rebranding. It tries to load transaction for the infinite scrolling on some page that does not support this.
locally
=> Fix regression introduced with rebranding explorer

lib/archethic/mining.ex, lib/archethic/mining/distributed_workflow.ex, lib/archethic/mining/validation_context.ex, lib/archethic/p2p.ex, lib/archethic/telemetry.ex, test/archethic/transaction_chain_test.exs
Fixes some bugs and improve little things
- Fixed telemetry error => buckets expected nb of summaries that was never calculated
- Delete unused functions
- Add max concurrency to a task async as all the response in the workflow should be retrieved fast
- Fix a flaky test
- Update function `P2P.broadcast_message` as this function should be used as "fire and forget" but it was waiting for all message to be sent and to receive the response.
- I have added tests that prove my …
=> Improvements

lib/archethic.ex, lib/archethic/mining.ex, lib/archethic/mining/chain_lock.ex, lib/archethic/mining/distributed_workflow.ex, lib/archethic/mining/standalone_workflow.ex, lib/archethic/mining/supervisor.ex, lib/archethic/p2p/message.ex, lib/archethic/p2p/message/error.ex, lib/archethic/p2p/message/message_id.ex, lib/archethic/p2p/message/request_chain_lock.ex, lib/archethic/p2p/message/start_mining.ex, lib/archethic/p2p/message/unlock_chain.ex, test/archethic/mining/chain_lock_test.exs, test/archethic/mining/distributed_workflow_test.exs, test/archethic/mining_test.exs, test/archethic/p2p/message/request_chain_lock_test.exs, test/archethic/p2p/message/unlock_chain_test.exs, test/archethic_test.exs
This PR adds a new security layer before to start mining a transaction.
When receiving the StartMining message for a transaction, validation nodes request the storage nodes of this transaction to lock the address. If the address is already locked for the same address but with a different transaction data, the lock is refused and the validation node does not start the mining.
This PR does not handle malicious node which could still start the transaction mining even with no lock. And so ask the replication to storage nodes.
To handle this, the storage nodes could sign the lock request, and so the storage nodes will replication the transaction only if they have the proof of the request lock being signed by all storage nodes.
Fixes #1373 
- New feature (non-breaking change which adds …
=> Lock chain before start mining

lib/archethic/bootstrap/network_init.ex, lib/archethic/db/embedded_impl/encoding.ex, lib/archethic/mining.ex, lib/archethic/mining/pending_transaction_validation.ex, lib/archethic/transaction_chain.ex, lib/archethic/transaction_chain/transaction/data.ex, lib/archethic/utils/regression/api.ex, lib/archethic_web/api/ecto_schemas/schema/transaction_data.ex, lib/archethic_web/api/jsonrpc/schemas/transaction.ex, lib/archethic_web/explorer/live/transaction_details_live.html.heex, priv/json-schemas/schemas/object/transaction_data.json, test/archethic/contracts/contract_test.exs, test/archethic/mining/pending_transaction_validation_test.exs, test/archethic/transaction_chain/transaction_test.exs, test/archethic_web/api/ecto_schemas/transaction_payload_test.exs, test/archethic_web/api/jsonrpc/schemas/transaction_test.exs, test/support/template.ex
- Compress code when serializing it (network & db)
- Check code size on compressed code 
Fixes #1299 
Tested with following scenarios: 
- an existing contract is triggered in the newer version
- a new contract is triggered
- explorer can read transactions with zipped or unzipped code
- Any dependent changes have been merged and …
=> Compress the transaction code on serialization

lib/archethic_web/api/ecto_schemas/function_call_payload.ex, lib/archethic_web/api/jsonrpc/methods/call_contract_function.ex, test/archethic_web/api/jsonrpc/methods/call_contract_function_test.exs
Add a new flag `resolve_last` to the json rpc function `call_function` allowing user to execute the contract to it's last version/time or to the version/time of the requested address.
`request_last` is a boolean, default to true
Created a contract with a public function returning a State and an action updating the state. I was able to retrieve state of the selected address.
```elixir
@version 1
actions triggered_by: interval, at: "*/5 * * * * *" do
counter = State.get("counter", 0)
State.set("counter", counter + 1)
end
export fun get_counter() do
State.get("counter", 0)
end
``` …
=> Add new flag resolve_last to rpc call function

lib/archethic.ex, lib/archethic/p2p/message/get_unspent_outputs.ex, lib/archethic/transaction_chain.ex, lib/archethic_web/explorer/components/unspent_outputs_list.ex, lib/archethic_web/explorer/live/transaction_details_live.ex, lib/archethic_web/explorer/live/transaction_details_live.html.heex
Update the explorer transaction details page with the new consumed inputs field.
Also display the genesis inputs of the chain.
Those fields are currently not visible by default until phase 2 of AEIP 21 is deployed. To access those field you have to put an argument `?debug` at the end of the url.
To display the genesis input of the chain, the message `GetUnspentOutput` is modified with a new `genesis?` flag. Once phase 2 deployed this flag could be removed if not used anymore
Fixes part of #1245 
Tested with mutiple kinf of transaction
- I have made …
=> Add consumed input explorer

lib/archethic/self_repair/sync/transaction_handler.ex, lib/archethic/transaction_chain.ex, test/archethic/self_repair/sync/transaction_handler_test.exs, test/archethic/transaction_chain_test.exs
- `download_transaction` check for the tx's integrity directly in the acceptance_resolver
- `fetch_transaction`'s conflict_resolver was naive and accepted the first non-error result
Unit tests 
=> Better conflict/acceptance resolver

lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations.ex, lib/archethic/utxo/memory_ledger.ex, test/archethic/transaction_chain/transaction/validation_stamp/ledger_operations_test.exs
Update unspent output to match consumed inputs during AEIP 21 phase 1 (do not recreate an utxo if it is the same a an previous one)
Optimize consumed inputs to not consume an UTXO that would be consolidated alone
Unit test
=> Improve consumed input

lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations.ex, lib/archethic/utxo/loader.ex, lib/archethic/utxo/memory_ledger.ex, test/archethic/transaction_chain/transaction/validation_stamp/ledger_operations_test.exs
This PR improves the UTXO model for the AEIP21 consumed inputs logic.
- Enhancements
=> Enhance utxo with consumed inputs

lib/archethic/utxo.ex, test/archethic/utxo_test.exs
Add the contract call UTXO on UTXO Ledger.
Unit test
Created a contract allowing to send a call to the contract but not creating a transaction to see the call in the genesis inputs on the explorer (using ?debug flag)
```elixir
@version 1
condition triggered_by: transaction, on: vote(), as: []
actions triggered_by: transaction, on: vote() do
if Map.size(transaction.uco_movements) == 0 do
Contract.set_content("ok")
else
1/0
end
end
```
- I have added tests that prove …
=> Add call utxo in UTXO Ledger

lib/archethic/mining/pending_transaction_validation.ex, lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations.ex, lib/archethic_web/explorer/components/amount.ex, test/archethic/mining/pending_transaction_validation_test.exs
Currently there is the possibility for a use to send fraction of a NFT token which should not be possible.
This PR adds a new control in the pending transaction validation to allow user to send NFT token only by unit (1e8).
Create a NFT token and try to send it by fraction. It is refused (same case using token mint recipient as well).
- Any …
=> Forbid user do send fraction of non fungible token

lib/archethic/db/embedded_impl/chain_reader.ex, test/archethic/db/embedded_impl_test.exs
When a file is corrupted (plenty of 0 written at the end, probably due to prealloc), to avoid an infinite recursion.
Unit test
=> Prevent infinite loop on corrupted file

lib/archethic/self_repair/notifier.ex
Avoid this error: 
```
** (ArgumentError) :max_concurrency must be an integer greater than zero
(elixir 1.14.1) lib/task/supervised.ex:181: Task.Supervised.stream/7
(elixir 1.14.1) lib/stream.ex:1811: Enumerable.Stream.do_each/4
(elixir 1.14.1) lib/stream.ex:942: Stream.do_transform/5
(elixir 1.14.1) lib/enum.ex:4307: anonymous fn/3 in Enum.concat_enum/1
(elixir 1.14.1) lib/enum.ex:2468: Enum."-concat_enum/1-lists^foldl/2-1-"/3
(elixir 1.14.1) lib/enum.ex:2468: Enum.concat_enum/1
(archethic 1.4.7) lib/archethic/self_repair/notifier.ex:185: Archethic.SelfRepair.Notifier.get_previous_election/3
```
=> Set a minimum concurrency so it is never 0

lib/archethic/p2p/message/replicate_transaction.ex, lib/archethic/p2p/message/shard_repair.ex, lib/archethic/self_repair/sync/transaction_handler.ex, lib/archethic/utxo.ex, priv/migration_tasks/prod/1.4.8@aeip_21-1.exs, test/archethic/self_repair/sync/transaction_handler_test.exs, test/archethic/self_repair/sync_test.exs, test/archethic/utxo_test.exs
This PR adds a new behavior for a genesis node of a chain.
- Now a genesis node will store the transaction as a chain and not as IO transaction. This will help to ensure having consolidated utxo view.
- When a genesis node adds an input for a chain, it will ensure this input has not been already consumed in a future transaction. This can happen during self repair or notifier.
Unit test
- Any …
=> Genesis do not load spent utxo

lib/archethic/replication.ex, lib/archethic/self_repair.ex, lib/archethic/self_repair/sync.ex, lib/archethic/self_repair/sync/transaction_handler.ex, lib/archethic/transaction_chain/transaction_summary.ex, lib/archethic/utxo.ex, test/archethic/self_repair/sync/transaction_handler_test.exs
Improve Self repair so it is faster and return proper error in case of failure.
- New `SelfRepair.Error` exception
- Function `adjust_attestation` is more clever and parallelizes requests
- Retrieve resolved genesis address map in before replication so UTXO does not need to resolve again
- Add trap exit flag to have better self repair retry
Self repair using testnet bootstrap …
=> Improve self repair

config/dev.exs, config/prod.exs, lib/archethic/contracts/loader.ex
Deactivate the TransactionChain.MemTableLoader and PendingLedger as they are not used yet and still do a lot of computation when starting a node
=> Speedup node start by deactivating unused feature

lib/archethic/mining.ex, lib/archethic/mining/distributed_workflow.ex, lib/archethic/mining/standalone_workflow.ex, lib/archethic/replication/transaction_validator.ex, lib/archethic/transaction_chain.ex, lib/archethic/transaction_chain/transaction_summary.ex, lib/archethic_web/api/jsonrpc/methods/estimate_transaction_fee.ex, lib/archethic_web/explorer/live/transaction_details_live.ex, test/archethic/replication/transaction_validator_test.exs, test/archethic/transaction_chain_test.exs, test/archethic/utxo_test.exs
Resolve the genesis instead of the last address
Resolve might raise on network_issue instead of providing a potentially erronous default
Fixes #1405
Unit tests
=> AEIP21-P2: Resolve genesis addresses

lib/archethic/mining/distributed_workflow.ex, lib/archethic/mining/standalone_workflow.ex, lib/archethic/p2p/message/get_unspent_outputs.ex, lib/archethic/p2p/message/replicate_transaction.ex, lib/archethic/replication.ex, lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations.ex, lib/archethic/utxo.ex, test/archethic/replication_test.exs
Fixes an issue where utxo of type state can have a nil timestamp, and this crashes a DateTime.compare
=> Fix utxo sort on state without timestamp

lib/archethic.ex, lib/archethic/mining/distributed_workflow.ex, lib/archethic/mining/standalone_workflow.ex, lib/archethic/mining/transaction_context.ex, lib/archethic/mining/validation_context.ex, lib/archethic/p2p/message/get_unspent_outputs.ex, lib/archethic/replication.ex, lib/archethic/replication/transaction_context.ex, lib/archethic/replication/transaction_validator.ex, lib/archethic/transaction_chain.ex, lib/archethic/transaction_chain/transaction/cross_validation_stamp.ex, lib/archethic/utxo/db_ledger/file_impl.ex, lib/archethic_web/explorer/live/transaction_details_live.ex, test/archethic/mining/transaction_context_test.exs, test/archethic/mining/validation_context_test.exs, test/archethic/replication/transaction_context_test.exs, test/archethic/replication/transaction_validator_test.exs, test/archethic/replication_test.exs
This PR modifies the Validation workflow to fetch the UTXOs from genesis nodes.
This PR is based on #1414
Fixes #1408
Unit tests & manual integration tests
=> AEIP21-P2: Use genesis unspent outputs during transaction's validation

lib/archethic/mining/pending_transaction_validation.ex, test/archethic/mining/pending_transaction_validation_test.exs
Fixes an issue where a user could create a transaction with the previous public key as the next public, breaking the chain as the previous transaction address is the current transaction address
Unit test
=> Add previous public key pending validation

lib/archethic/contracts.ex, lib/archethic/contracts/contract.ex, lib/archethic/mining/smart_contract_validation.ex, lib/archethic/p2p/message/smart_contract_call_validation.ex, lib/archethic/p2p/message/validate_smart_contract_call.ex, test/archethic/mining/pending_transaction_validation_test.exs, test/archethic/mining/smart_contract_validation_test.exs, test/archethic/p2p/message/validate_smart_contract_call_test.exs, test/archethic/replication/transaction_validator_test.exs
The `SmartContractCallValidation` struct in the `Archethic.Contracts` module has been updated to replace the `valid?` field with a `status` field. The `status` field can have the values `:ok`, `{:error, :transaction_not_exists}`, or `{:error, :invalid_execution}`. This change allows for more descriptive and meaningful status reporting in smart contract call validations.
This change also introduces priorization of the status
Fixes #1423
=> feat: update SmartContractCallValidation struct to use status field instead of valid? field

lib/archethic/transaction_chain/transaction_input.ex
Fix comparison with inputs which have different timestamp due to different serialization
=> Fix TransactionInput.set_spent to compare only using from and type

lib/archethic/utxo.ex, lib/archethic/utxo/memory_ledger.ex, test/archethic/utxo/loader_test.exs, test/archethic/utxo/memory_ledger_test.exs, test/archethic/utxo_test.exs
Improve performance of UTXO lookup using ets lookup instead of select match
Enhancements
=> Improve UTXO streamning using :ets.lookup for memory UTXOs retrieval

lib/archethic_web/explorer/live/chains/transaction_chain_live.ex
Fix get balance with amount == nil on the transaction chain page on the exploreer
=> Fix get balance when amount is nil on the chain page

lib/archethic/p2p/message/validate_smart_contract_call.ex, lib/archethic/utils/job_cache.ex, test/archethic/p2p/message/validate_smart_contract_call_test.exs
This changes adds the usage of JobCache during SmartContractCallValidation processing.
=> feat ✨: Cache smart contract call validation

lib/archethic/contracts/loader.ex, lib/archethic/contracts/worker.ex, test/archethic/contracts/loader_test.exs, test/archethic/contracts/worker_test.exs, test/support/template.ex
Refactor Worker to use GenStateMachine over GenServer
Adds a new behavior to invalidate smart contract call to not block worker.
=> Refactor Worker as GenStateMachine, add Invalid call management

lib/archethic/utxo.ex, test/archethic/contracts/worker_test.exs
Add control to ensure a call has not been already consumed in UTXO
=> Add consumed_utxo control also for recipient

lib/archethic/contracts.ex, lib/archethic/contracts/interpreter.ex, test/archethic/beacon_chain/subset/stats_collector_test.exs, test/archethic/contracts/interpreter/library/common/crypto_test.exs, test/archethic/contracts_test.exs, test/support/contract_factory.ex, test/support/template.ex
Fix smart contract execution to be run inside a task to avoid intepreter's process limitations
This way the code's execution is isolated and multiple run from condition, actions and after contract renewal will be independent of 
the worker being or not in the same process. …
=> Wrap interpreter execution in a task to isolate calls

lib/archethic.ex, lib/archethic/contracts/loader.ex, lib/archethic/crypto.ex, lib/archethic/p2p/message/get_unspent_outputs.ex, lib/archethic/p2p/message/unspent_output_list.ex, lib/archethic/p2p/message/validate_smart_contract_call.ex, lib/archethic/transaction_chain.ex, lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations.ex, lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations/unspent_output.ex, lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations/versioned_unspent_output.ex, lib/archethic_web/api/graphql/schema.ex, lib/archethic_web/api/graphql/schema/beacon_chain_summary_type.ex, lib/archethic_web/api/graphql/schema/hash_type.ex, lib/archethic_web/api/graphql/schema/resolver.ex, lib/archethic_web/api/graphql/schema/transaction_type.ex, test/archethic/p2p/message/get_unspent_outputs_test.exs, test/archethic/p2p/messages_test.exs, test/archethic/transaction_chain_test.exs
Add new chain_sync_date field for conflict resolver and update offset mechanism
Running playbook as it also use graphql query `chainUnspentOuputs`
=> Refactor GetUnspentOutput message

lib/archethic/db.ex, lib/archethic/db/embedded_impl.ex, lib/archethic/db/embedded_impl/chain_index.ex, lib/archethic/transaction_chain.ex, test/archethic/contracts/interpreter/legacy/library_test.exs, test/archethic/contracts/interpreter/library/common/token_test.exs, test/archethic/transaction_chain_test.exs, test/archethic/utxo_test.exs, test/support/template.ex
Created a new function `DB.find_genesis_address` returning a tuple instead of a default value
This function is used in `TransactionChain.fetch_genesis_address` to improve performance when the requested address is already a genesis address that can be found in local DB
=> Improve fetch genesis address

lib/archethic/contracts/contract/context.ex, lib/archethic/contracts/worker.ex, lib/archethic/mining/smart_contract_validation.ex, lib/archethic/mining/validation_context.ex, lib/archethic/replication/transaction_validator.ex, lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations.ex, lib/archethic/utils/regression/playbooks/smart_contract/deterministic_balance.ex, lib/archethic/utxo.ex, lib/archethic/utxo/db_ledger.ex, lib/archethic/utxo/db_ledger/file_impl.ex, lib/archethic/utxo/loader.ex, test/archethic/contracts/loader_test.exs, test/archethic/mining/smart_contract_validation_test.exs, test/archethic/mining/validation_context_test.exs, test/archethic/replication/transaction_validator_test.exs, test/archethic/utxo_test.exs, test/support/template.ex
Filter inputs from calls in contract execution
- Enhancements
=> Filter inputs from calls in contract execution

scripts/release.sh, scripts/test-release.sh
Added a new argument `-v [version]` to the release and test-release command to select the version to up from. Argument used in by `mix distillery.release --upgrafe --upfrom [version]`
Local release
=> Add new arg for upfrom version in release scripts

lib/archethic/contracts/interpreter.ex, lib/archethic/crypto.ex, lib/archethic/governance/code/proposal/parser.ex, lib/archethic/mining/smart_contract_validation.ex, lib/archethic/p2p/message/smart_contract_call_validation.ex, lib/archethic/p2p/message/validate_smart_contract_call.ex, test/archethic/p2p/message/validate_smart_contract_call_test.exs
This PR aims to fix an issue to accept a smart contract call if the contract doesn't have funds for the transaction triggered by the contract based on the movements.
- Enhancements
Create a smart contract which send UCO once a trigger transaction is received.
Do not funds the contract with the UCO to send in the action;
If a client call the contract it should be rejected.
Fund more the contract to satisfy the UCO to send in the action
Resent the transaction from the client to call the contract, the contract's transaction should be validated and emitted.
- I have made …
=> Ensure enough funds during smart contract call validation

lib/archethic/contracts/interpreter/condition_interpreter.ex, lib/archethic/contracts/interpreter/condition_validator.ex, test/archethic/contracts/interpreter/condition_interpreter_test.exs, test/archethic/contracts/interpreter/condition_validator_test.exs
Add the new `do..end` syntax for conditions:
```
condition inherit do 
...
end
condition triggered_by: oracle do 
...
end
condition triggered_by: transaction do 
...
end
condition triggered_by: transaction, on: vote(x) do 
...
end
```
Unit tested
=> Smart Contracts: Add the `do..end` syntax for condition blocks

lib/archethic/mining/smart_contract_validation.ex, lib/archethic/p2p/message/smart_contract_call_validation.ex, lib/archethic/p2p/message/validate_smart_contract_call.ex, test/archethic/mining/smart_contract_validation_test.exs, test/archethic/p2p/message/smart_contract_call_validation_test.exs, test/archethic/p2p/message/validate_smart_contract_call_test.exs, test/archethic/replication/transaction_validator_test.exs
Take into account the `latest_validation_time` when resolving conflicts on contract calls execution.
I based this PR on #1343. Please ignore all commits but last 3.
Fixes #1485
- Enhancement
unit-tested
=> ValidateSmartContractCall better conflict resolution

config/test.exs, lib/archethic/mining/smart_contract_validation.ex, lib/archethic/p2p/message/smart_contract_call_validation.ex, lib/archethic/p2p/message/validate_smart_contract_call.ex, test/archethic/p2p/message/validate_smart_contract_call_test.exs
Branch is based on https://github.com/archethic-foundation/archethic-node/pull/1498. 
Please check only the last commit.
Fixes #1487
Unit tested
=> ValidateSmartContractCall timeout

config/config.exs, config/test.exs, lib/archethic.ex, lib/archethic/mining.ex, lib/archethic/mining/distributed_workflow.ex, lib/archethic/p2p/message/start_mining.ex, test/archethic/mining/distributed_workflow_test.exs, test/archethic/p2p/messages_test.exs
Improve mining timeout with a reference timeout. As it all the nodes will have the timeout at the same time.
Also placed prior validation after building context
Also updated the mining timeout with new values based on new smart contract validation
Started 3 nodes, launched some benchmark, it worked well.
Stopped one and did some faucet, it worked well after coordinator or context timeout
- …
=> Improve mining timeout

lib/archethic/db/embedded_impl/chain_reader.ex, test/archethic/db/embedded_impl_test.exs, test/archethic/transaction_chain_test.exs
When querying a chain with paging_state = genesis we should act as if paging_state is nil
Example of broken behaviour (testnet data)
```
query {
transactionChain(
address: "00006AF4C3AE64D435DA162B27918D6BE3AF8610494E3021148709BBE11A5520334C",
pagingAddress: "00006AF4C3AE64D435DA162B27918D6BE3AF8610494E3021148709BBE11A5520334C"
) {
address
}
}
```
This should reply the same thing as the following query
```
query {
transactionChain(
address: "00006AF4C3AE64D435DA162B27918D6BE3AF8610494E3021148709BBE11A5520334C"
) {
address
}
}
```
It currently return empty (instead of 2 txs)
Unit test + manual test …
=> API: fix transaction_chain when the paging_address == genesis_address

lib/archethic/contracts.ex, lib/archethic/telemetry.ex
Add a metric to count the number of calls in the workers queues. 
- New feature
Manually tested
=> Add a metric for the sum of all the calls queued for the workers

test/archethic/oracle_chain/services/uco_price_test.exs, test/archethic/self_repair/repair_worker_test.exs
It's always because the Registry is not updated synchronously.
=> Fix flaky tests on uco_price and repair_worker

lib/archethic/contracts/interpreter/ast_helper.ex, lib/archethic/contracts/interpreter/library/common/http.ex, lib/archethic/contracts/interpreter/library/common/http_impl.ex, lib/archethic/mining/smart_contract_validation.ex, test/archethic/contracts/interpreter/library/common/http_impl_test.exs
Add a new `throw_on_error` flag that can be specified to handle the HTTP errors in the contracts.
Fixes #1381 
Unit tests & local test with contract such as: 
```
@version 1
actions triggered_by: interval, at: "* * * * *" do
responses = Http.request_many([
[url: "https://fakerapi.it/api/v1/users?_quantity=1&_gender=male&_seed=cucumber", method: "GET"],
[url: "https://fakerapi.it/api/v1/users?_quantity=1&_gender=male&_seed=cucumber", method: "GET"],
[url: "https://fakerapi.it/api/v1/users?_quantity=1&_gender=female&_seed=tomato", method: "GET"],
[url: "https://fakerapi.it/api/v1/users?_quantity=1&_gender=female&_seed=tomato", method: "GET"],
[url: "http://fakerapi.it/api/v1/users?_quantity=1&_gender=female&_seed=tomato", method: …
```
=> Smart Contracts: `Http.request/5` and `Http.request_many/2`

lib/archethic/self_repair.ex, lib/archethic/self_repair/sync.ex, test/archethic/self_repair/self_repair_test.exs, test/archethic/self_repair/sync_test.exs
Based on the branch of PR #1494  (only 2 commits for this one)
Fixes #1501
Unit tests
- start a new node 
- after self repair, check with graphql that the inputs of transactions made before are present on the new node
=> Also fetch the inputs when fetching the transactions

config/prod.exs, lib/archethic/crypto/keystore/node/origin/software_impl.ex, lib/archethic_web/explorer/live/settings_live.ex, lib/archethic_web/explorer/live/settings_live.html.heex
I added a "no-op" node transaction button that is used to send a node transaction that is similar to previous one (except for the certificate). We probably will remove this in the future.
I also removed 2 env variable because I believe they are not necessary : 
1. ARCHETHIC_CRYPTO_ROOT_CA_SOFTWARE_PUBKEY
2. ARCHETHIC_CRYPTO_ROOT_CA_TPM_PUBKEY
(because it's a `compile_env` configuration anyway)
=> Change mainnet certificates, add ORIGIN_SEED optional env

lib/archethic/mining/fee.ex, lib/archethic/mining/validation_context.ex, lib/archethic/replication/transaction_validator.ex, test/archethic/mining/fee_test.exs, test/archethic/mining/validation_context_test.exs
Add splipage acceptance for tx's fee validation of 3%
Unit test
=> Add slippage acceptance for fee's validation

lib/archethic/contracts/interpreter/library/common/crypto.ex, lib/archethic/crypto.ex, test/archethic/contracts/interpreter/library/common/crypto_test.exs
Add `Crypto.decrypt_with_storage_nonce/1` in the Interpreter's library.
This feature allows node to decrypt secrets during the contract's execution.
- Unit tests
- Integration test with the following code:
```elixir
@version 1
actions triggered_by: interval, at: "* * * * * *" do
cleartext = Crypto.decrypt_with_storage_nonce(0x...)
Contract.set_content(cleartext)
end
```
The ciphertext is generated using the `Crypto.ec_encrypt("data to encrypt", Crypto.storage_nonce_public_key())`
- My changes generate no …
=> Add Crypto.decrypt_with_storage_nonce/1 in Interpreter's library

lib/archethic/contracts.ex
This does not concern the node directly but applications that depends on it (playground).
The cache key was using the validation_time but it should use the :time_now because that's what the interpreter actually use. 
ALSO: **Make the cache optional**
via the playground + run the tests
- Any dependent changes have been merged and published in …
=> Smart Contracts: change cache key

lib/archethic/contracts.ex, test/archethic/contracts_test.exs
made a mistake on https://github.com/archethic-foundation/archethic-node/pull/1521. The errors on conditions were not properly transformed in the %Failure{} struct when cache? was false.
I added the tests this time.
=> Fix the execution's errors when cache? is false

lib/archethic/p2p.ex, lib/archethic/telemetry.ex
Add a metric to count the number of nodes currently connected. 
This will be useful to detect splits or nodes that are not connected to anyone but still accept incoming connections (so they appear available, but in the end they cannot request anything outside of its shard resulting in wrong replies)
=> Metrics: add P2P.nodes_connected

lib/archethic/contracts/contract/state.ex, lib/archethic_web/api/graphql/schema/transaction_type.ex, lib/archethic_web/explorer/live/transaction_details_live.ex, test/archethic/contracts/state_test.exs
Use inspect instead of Json.encode to handle map with non-string keys
Fixes #1523
Manual test
=> Fix explorer issue when displaying a state with maps that cannot be transformed to json

lib/archethic/contracts/interpreter/library/common/list.ex
=> Smart Contracts: Add List.sort_by/2,uniq/1,delete_at/2,set_at/2

lib/archethic/contracts/contract/context.ex
Fixes an issue when a contract has no utxos, the contract input validation was returning false while it is normal that the contract inputs list is empty
Doc test
=> Fix contract inputs validation with empty list

lib/archethic/contracts/interpreter/library/common/math.ex, test/archethic/contracts/interpreter/library/common/math_test.exs
Add `Math.bigint` in smart contract, converting a number into its bigint representation for a given number of decimals
The use case has been tested with the bridge to set EVM big int
=> Add `Math.bigint` in SC

lib/archethic/p2p/message/shard_repair.ex, lib/archethic/self_repair/notifier.ex, test/archethic/p2p/messages_test.exs, test/archethic/self_repair/notifier_test.exs
Fixes an issue where the notifier sent the wrong genesis address in the message ShardRepair. This result a node to store the UTXO of a chain to the wrong genesis address and not consuming UTXO.
=> Fix notifier genesis_address in ShardRepair msg

lib/archethic/contracts/worker.ex
When a resulting contract's transaction fails to be validated, we reschedule it.
Fixes #1547
Scenario:
- start 2 nodes
- create a contract that will create a failing transaction 
```
@version 1
actions triggered_by: datetime, at: 1848657600 do
Contract.set_content "that's all folks"
end
actions triggered_by: interval, at: "* * * * *" do
Contract.add_uco_transfer to: "00000000000000000000000000000000000000000000000000000000000000000000", amount: 1_000_000_000
end
```
- the contract should run every minute even if the transaction cannot be validated (Insufficient funds).
- I have commented my code, particularly in hard-to-understand …
=> Smart Contracts: reschedule triggers on node responsiveness timeout

lib/mix/tasks/migrate.ex
Fixes an issue where a version is for example "1.5.10" and a migration task is created for version "1.5.9".
The Migrate module compare version as string and 1.5.9 > 1.5.10 while it should not be.
Used the Elixir `Version` module to fix it
On current version (1.5.10) run a node, stop it and restart it, without the fix it will try to run the migration for 1.5.9 that fail.
It does not run the migration after the fix
- I have added tests that prove my fix is effective or that my …
=> Use Elixir Version module on migrate version compare

lib/archethic/replication/transaction_context.ex, test/archethic/replication/transaction_context_test.exs
During replication, if a node has to sync previous transactions of a chain, when it downloads them it ensure all transactions are fetched from the paging address to the limit address.
It ensure all transactions using there previous address which should be the address of the previous transaction fetched.
Fixes #1563 
- Any dependent changes …
=> Replicate previous chain raise on missed tx

lib/archethic/self_repair/network_chain.ex, test/archethic/transaction_chain_test.exs
Issue found by @Neylix, because the datetime comparaison was done by comparing strings instead of datetime, the acceptance resolver of the networkchain resync was broken.
Manually tested
=> Fix acceptance_resolver when syncing network chains

lib/archethic/beacon_chain/summary_aggregate.ex, test/archethic/beacon_chain/summary_aggregate_test.exs
In some case this is possible that a node start it's self repair but as missed a new node transaction and so doesn't know this node.
Before starting the synchronize the missed transactions, the node aggregate the P2P view and ensure the p2p view of each summary has the same size of the expected node to sample for the summary subset. But since don't know all the node, the size comparison will fail and will make the p2p view empty
To fix this, instead of ensuring the p2p view size with local data, during aggregation the node will take the most frequent size across all summaries.
Starts 3 nodes at the same time, after the first summary, the 3rd node will have a wrong p2p view compared to others
- My code follows the style guidelines of …
=> Filter p2p view size on during aggregation of summaries

lib/archethic/utxo.ex, test/archethic/utxo_test.exs
Currently when a node is not genesis node of a transaction, it does not consume or update the UTXO of the genesis address of the chain.
But in some case, it is possible that a node is genesis node for a chain and store its UTXO, then the election change and it is not genesis node anymore but still store some transaction of the chain as storage node.
Then is become genesis node again, but since it already stored the transaction of this chain it will node re ingest the transaction and consume the inputs. So we encounter an issue where a the node keeps already spent UTXO in its view.
To fix it, even if the node is not genesis node of a chain, it consume the inputs and update the utxo of the genesis.
- My code follows the style guidelines …
=> Consume inputs even if not genesis node

lib/archethic/transaction_chain/transaction/data/ownership.ex
To ensure serialization of the ownership is the same between node and sdk, ownership's authoized key map is sorted as done by sdk.
This will not be the case by default when upgrading to erlang 26
=> Sort ownership authorized keys in serialization

lib/archethic/mining/smart_contract_validation.ex, lib/archethic/mining/transaction_context.ex, lib/archethic/replication.ex, lib/archethic/replication/transaction_context.ex, lib/archethic/self_repair.ex, lib/archethic/self_repair/sync.ex, lib/archethic/transaction_chain.ex, test/archethic/mining/distributed_workflow_test.exs, test/archethic/mining/standalone_workflow_test.exs, test/archethic/replication/transaction_context_test.exs
There are cases where we know for sure that we are querying data that exists, in these cases we add an acceptance_resolver to keep asking the data until we find it.
unit test on the transaction_context 
=> Use the acceptance_resolver more often

lib/archethic/bootstrap/network_init.ex, lib/archethic/mining/ledger_validation.ex, lib/archethic/mining/validation_context.ex, lib/archethic/p2p/message/validate_smart_contract_call.ex, test/archethic/mining/distributed_workflow_test.exs, test/archethic/mining/ledger_validation_test.exs, test/archethic/mining/validation_context_test.exs, test/support/transaction_factory.ex
A bug was introduced in 1.5.11's refactor where the UCO were consumed instead of the MUCO. This is an incorrect behaviour and people with MUCO were consuming UCO instead of MUCO when transferring MUCO.
This fix the issue by resolving MUCO only after the consume step.
Added a unit test
- Any dependent changes have been merged and published in …
=> Consume the MUCO correctly

lib/archethic.ex, lib/archethic/election.ex, lib/archethic/mining.ex, lib/archethic/mining/distributed_workflow.ex, lib/archethic/mining/validation_context.ex, lib/archethic/p2p/message/start_mining.ex, test/archethic/election_test.exs, test/archethic/mining/validation_context_test.exs, test/support/transaction_factory.ex
This pull request addresses an issue with the validation node election process. Currently, the election is based on transaction data and a daily nonce seed, which causes repeated selection of the same validation nodes for identical transactions throughout the day. If one of the validation nodes, especially the coordinator, has an incorrect state or is unable to retrieve required data, the transaction will fail validation for the entire day.
The solution implemented here introduces a timestamp into the election process to ensure that the elected nodes vary with each transaction attempt. The timestamp used is from the StartMining message, sent by the welcome node, which serves as a reference timestamp to diversify node election.
Fixes #1564
- New …
=> Add timestamp in node validation election

lib/archethic/bootstrap/network_init.ex, lib/archethic/db/embedded_impl/chain_reader.ex, lib/archethic/db/embedded_impl/chain_writer.ex, lib/archethic/db/embedded_impl/encoding.ex, lib/archethic/mining.ex, lib/archethic/mining/distributed_workflow.ex, lib/archethic/mining/validation_context.ex, lib/archethic/transaction_chain/transaction/cross_validation_stamp.ex, lib/archethic/transaction_chain/transaction/validation_stamp.ex, lib/archethic_web/api/graphql/schema/transaction_type.ex, lib/archethic_web/explorer/components/transactions_list.ex, lib/archethic_web/explorer/live/chains/node_shared_secrets_chain_live.ex, lib/archethic_web/explorer/live/chains/oracle_chain_live.ex, lib/archethic_web/explorer/live/chains/origin_chain_live.ex, lib/archethic_web/explorer/live/chains/reward_chain_live.ex, lib/archethic_web/explorer/live/transaction_details_live.html.heex, priv/migration_tasks/prod/1.6.0@genesis.exs, test/archethic/db/embedded_impl_test.exs, test/archethic/mining/distributed_workflow_test.exs, test/archethic/mining/validation_context_test.exs, test/archethic/p2p/messages_test.exs, test/archethic/transaction_chain/transaction/cross_validation_stamp_test.exs, test/archethic/transaction_chain/transaction/validation_stamp_test.exs, test/archethic/transaction_chain/transaction_test.exs, test/support/transaction_factory.ex
Added the genesis_address in the validation_stamp. It's written on disk only on IO transaction, because the chain storage is written in a file named by the genesis, so there's no point to duplicate the data there.
There's a migration script to run on all legacy IOs
Fixes #1562
Updated the code to store every tx also as IO then run a release upgrade on 4 nodes.
Chain & IO storage both returned the genesis address on legacy and new transactions
- I have added tests …
=> Add the genesis address in the validation_stamp

lib/archethic/db/embedded_impl/chain_writer.ex, lib/archethic/utxo/loader.ex
Add infinity timeout on DB write through Genserver.call
Fixes #1617 
=> Add infinity timeout on Genserver DB call

lib/archethic/self_repair/sync.ex, lib/archethic/transaction_chain.ex, test/archethic/bootstrap/network_init_test.exs, test/archethic/bootstrap_test.exs
Fixes an issue where a node cannot fetch the genesis address of a recipient while consolidating it in self repair.
=> Fix self repair recipient consolidation

lib/archethic/contracts.ex, lib/archethic/contracts/wasm/contract.ex, lib/archethic/contracts/wasm/spec.ex, lib/archethic/mining/pending_transaction_validation.ex, lib/archethic/mining/proof_of_work.ex, test/archethic/mining/pending_transaction_validation_test.exs
Improve validation of wasm smart contract in the pending validation 
- Enhancement
- Unit test
- Smart contract deployment through ae-contract-test
=> Add more validation for smart contract wasm

lib/archethic/self_repair/sync.ex
Fixes an issue where a transaction address is the same as its genesis address. This was not properly handled in self repair.
PS: this is not possible anymore since we added a control in pending validation. But old transaction may be wrong so we need to handle this case …
=> Handle acceptance_failed in adjust attestation

scripts/install.sh
Since last version of asdf, the command `asdf update` is deprecated and return an exit code 1 which stop the install.sh script
I just ignored the exit code so the script don't stop
=> Ignore asdf upstate exit code

lib/archethic/p2p.ex, lib/archethic/p2p/message.ex, lib/archethic/p2p/message/message_id.ex, lib/archethic/p2p/message/update_last_address.ex, lib/archethic/self_repair.ex, lib/archethic/transaction_chain.ex, test/archethic/p2p/message/update_last_address_test.exs, test/archethic/transaction_chain_test.exs
It's often possible to trigger some repair when looking at the quorum results. 
This PR will stay in draft until #1562 #1588 is done.
unit tests
=> Add some repair messages in the TransactionChain

README.md
Explain MacOS specific setups to get a working dev environment.
=> docs: :memo: Explain MacOS specific setups for developers.

.gitignore, lib/archethic.ex, lib/archethic/contracts.ex, lib/archethic/contracts/contract/state.ex, lib/archethic/contracts/interpreter/contract.ex, lib/archethic/contracts/wasm/contract.ex, lib/archethic/mining.ex, lib/archethic/transaction_chain/transaction/validation_stamp.ex, lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations.ex, lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations/unspent_output.ex, lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations/versioned_unspent_output.ex, lib/archethic/transaction_chain/transaction_input.ex, lib/archethic/transaction_chain/versioned_transaction_input.ex, lib/archethic_web/api/graphql/schema/resolver.ex, lib/archethic_web/explorer/live/transaction_details_live.ex, lib/archethic_web/explorer/live/transaction_details_live.html.heex, test/archethic/contracts/state_test.exs, test/archethic/contracts_test.exs
Smart contracts state is compressed using  `zlib`.
Fixes #1615
=> Use ZIP to reduce smart contract state size

lib/archethic/beacon_chain/subset/summary_cache.ex
Add infinity timeout on the Genserver.call when adding slot into summary cache
=> Fix timeout when writing slot in summary cache

lib/archethic/db.ex, lib/archethic/db/embedded_impl.ex, lib/archethic/db/embedded_impl/chain_writer.ex, lib/archethic/replication.ex, lib/archethic/transaction_chain.ex, test/archethic/db/embedded_impl_test.exs
When replicating transactions, checks if Tx is already present before writing it.
Check is performed in `ChainWriter.write` to ensure they are sequentials.
Fixes #1650
=> Tx replication sometimes fails. #1650

lib/archethic_web/api/jsonrpc/controllers/jsonrpc_controller.ex
Fixes an issue on JSON RPC endpoint while user send a batch of 1 request, the node respond with a non batch response.
Also improved concurrency when processing requests
=> Fix jsonrpc

lib/archethic/utxo/loader.ex
Ensure no UTXO are stored in multiple occurrence in UTXO file DB
=> Add uniq filter on UTXO list while DB write

lib/archethic/beacon_chain/subset.ex, lib/archethic/beacon_chain/subset/p2p_sampling.ex, lib/archethic/contracts/wasm/contract.ex, lib/archethic/p2p/client/connection.ex, test/archethic/beacon_chain/subset/p2p_sampling_test.exs, test/archethic/beacon_chain/subset_test.exs
- Removed useless p2p view request while adding new attestation in subset
- Refactor p2p view creation
- Create slot and summary inside async Task to not block the subset Genserver
- Also fixes an old issue to send beacon slot even if not beacon slot node
Fixes #981  …
=> Fix timeout issue in subset making genserver crash + refactor

lib/archethic/reward.ex, test/archethic/reward/scheduler_test.exs, test/archethic/reward_test.exs
Fixes an issue when validating the node_rewards transaction. The UTXO used to calculate the transfers are retrieved locally therefore if a node missed the last mint_reward transaction, its UTXO will not be the same and so the transaction will fail.
Fixed it by fetching UTXO instead to get them locally.
Also sorted the nodes to ensure all nodes has the same transfer order …
=> Fix node rewards issue

.gitignore, lib/archethic.ex, lib/archethic/election.ex, lib/archethic/election/constraints/validation.ex, lib/archethic/mining.ex, lib/archethic/mining/distributed_workflow.ex, lib/archethic/mining/standalone_workflow.ex, lib/archethic/mining/validation_context.ex, lib/archethic/p2p/message/start_mining.ex, lib/archethic/replication.ex, test/archethic/election/constraints/validation_test.exs, test/archethic/election_test.exs, test/archethic/mining/distributed_workflow_test.exs, test/archethic/mining/validation_context_test.exs, test/archethic/p2p/messages_test.exs, test/archethic_test.exs
- Update validation node election algorithm so the number of validation nodes is the number returned by the hypergeometric distribution.
- During election, authorized nodes are now sorted by their first public key instead of the last.
- Created a new `synchronization_nodes` function to select some nodes of the validation nodes to be the synchronization nodes. It selects nodes from different geo patch priorize geo patch with the most number of validation nodes.
- For now until BLS proofs are implemented, distributed workflow take the synchronization nodes as the entire validation node to not change the validation process
- Update the validation context and distributed workflow to use the first node public key to identify nodes instead of the last
Fixes #1607 
- New feature (non-breaking …
=> Validation election new algo

config/prod.exs, lib/archethic/crypto.ex
This will allow to configure mainnet to support new nodes which doesn't need Uniris CA key certification
=> chore: Remove root CA public key configuration
