archethic-foundation/archethic-node

lib/archethic/crypto/ed25519/libsodium_port.ex

Leverage the PortHandler helper for ports handling instead to roll a custom one.

Use PortHandler for the libsodium port

---

lib/archethic/contracts/worker.ex
lib/archethic/oracle_chain.ex
lib/archethic/pub_sub.ex
lib/archethic_web/live/chains/oracle_live.ex
lib/archethic_web/templates/explorer/oracle_chain_index.html.leex
mix.exs
test/archethic/pub_sub_test.exs

Oracle live realtime feed

---

lib/archethic_web/live/chains/oracle_live.ex
lib/archethic_web/templates/explorer/oracle_chain_index.html.leex
mix.exs

Fix pagination

---

Makefile
lib/archethic/crypto/keystore/node/tpm_impl.ex
mix.exs

Using ETS to avoid bottleneck of TPM implementation genserver

---

assets/css/app.scss
config/config.exs
config/dev.exs
config/prod.exs
lib/archethic_web/controllers/faucet_controller.ex
lib/archethic_web/router.ex
lib/archethic_web/templates/faucet/index.html.eex
lib/archethic_web/templates/layout/root.html.eex
lib/archethic_web/views/faucet_view.ex

Added faucet for dev and prod (testnet).
Fixed #64 PR suggestions.
Added custom logger level for dev config.

Add testnet faucet

---

lib/archethic/oracle_chain/scheduler.ex
mix.exs

Prevent OracleSummary transaction to be submitted twice 

---

lib/archethic/contracts/interpreter.ex
lib/archethic_web/controllers/explorer_controller.ex
lib/archethic_web/templates/explorer/chain.html.eex
lib/archethic_web/templates/explorer/transaction_details.html.leex

Fix transaction's fee formatting with the new systems of decimals
Fix Balance fetching on the transaction chain screen

Fix UI displays

---

lib/archethic_web/controllers/explorer_controller.ex

Fix  page state with invalid parameters

---

lib/archethic/self_repair/sync.ex
lib/archethic/self_repair/sync/beacon_summary_handler.ex
mix.exs
mix.lock

Fix reducing of the flow during self-repair
Time windows were not great departitioned using the reduce, so the self-repair was broken.
Closes #128

Fix Flow selfrepair

---

lib/archethic_web/graphql_schema/transaction_type.ex

Fix typo in GraphQL schema

---

lib/archethic_web/graphql_schema.ex
lib/archethic_web/graphql_schema/content_type.ex
lib/archethic_web/graphql_schema/p2p_type.ex
lib/archethic_web/graphql_schema/resolver.ex
lib/archethic_web/graphql_schema/transaction_type.ex

Add Network transactions list in the API

---

lib/archethic_web/controllers/explorer_controller.ex
lib/archethic_web/live/transaction_details_live.ex
lib/archethic_web/templates/explorer/chain.html.eex
lib/archethic_web/templates/explorer/transaction_details.html.leex
lib/archethic_web/views/layout_helpers.ex

Solve #226
Add USD price near UCO amount in those views : 
- Transaction chain (current USD price)
- Transaction details (at transaction time USD price and current USD price)

Indicate usd price near of uco amounts #226

---

lib/archethic/beacon_chain.ex
lib/archethic_web/live/chains/beacon_live.ex
lib/archethic_web/live/chains/cache.ex
lib/archethic_web/supervisor.ex

The current issues are mentioned in the issues desc and need to fixed with improving the beacon explorer with various methods like caching, Cache which is ETS table stores date/page as key and transactions are the value and the cache limit is yet to think upon.
Not Yet …

Add cache to the beacon explorer

---

lib/archethic/db.ex
lib/archethic/db/embedded_impl.ex
lib/archethic/transaction_chain.ex

Allow to write a transaction to given genesis address

Write transaction to specific genesis address

---

.tool-versions
assets/package-lock.json
lib/archethic/account/mem_tables_loader.ex
lib/archethic/bootstrap/network_init.ex
lib/archethic/bootstrap/sync.ex
lib/archethic/mining/pending_transaction_validation.ex
lib/archethic/shared_secrets/mem_tables_loader.ex
lib/archethic/transaction_chain/mem_tables_loader.ex
lib/archethic/transaction_chain/transaction.ex
lib/archethic_web/controllers/api/origin_key_controller.ex
lib/archethic_web/views/explorer_view.ex
test/archethic/bootstrap/network_init_test.exs
test/archethic/mining/pending_transaction_validation_test.exs
test/archethic/shared_secrets/mem_tables_loader_test.exs
test/archethic_web/controllers/api/origin_key_controller_test.exs

Simplification of Origin key management with public_key and certificate
Fixes #326 

Simplification of Origin key management

---

lib/archethic/db/embedded_impl/chain_writer.ex
test/archethic/db/embedded_impl_test.exs

Fixes #416 
To validate this, we should try to simulate load and run for a certain amount of time

Fix db timeouts

---

lib/archethic/p2p/mem_table_loader.ex

Added Checks for Same Slot when Node is Available in Slot.
When the nodes are loaded from DB and we are in the same slot, we should set synced to true as the node was previously available, which implies that it was synced.
When the node is loaded in the next slot, i.e beacon chain summary has been changed, then we want the node to be synced but not available as it might be the case that node is not available later.
Fixes # 436
Local manual testing, And Tests Passes
- …

P2P view is invalid after quick disconnection of a node

---

lib/archethic_web/graphql_schema.ex

:page, :iinteger to :page, :page
Fixes # (#486)
- iGraphQL-Test

resolve page scaler

---

lib/archethic_web/graphql_schema.ex
lib/archethic_web/graphql_schema/resolver.ex
lib/archethic_web/graphql_schema/transaction_type.ex

Adds a new GraphQL Schema to the API to fetch token information
Fixes # 407
- Feature Addition
Manual testing with single node

GraphQL API to get token information #407

---

lib/archethic/account/mem_tables_loader.ex
test/archethic/account/mem_tables_loader_test.exs
test/archethic/account_test.exs
test/archethic/bootstrap/network_init_test.exs
test/archethic/bootstrap/sync_test.exs
test/archethic/bootstrap_test.exs
test/archethic/reward/mem_tables_loader_test.exs
test/archethic/reward_test.exs
test/support/template.ex

Requires proper testing here.
Fixes # (#484 )
Fixed in pr   Transform miner reward token to UCO #381 #403
Requires testing

Testing for Reward Minting #484

---

lib/archethic_web/graphql_schema/transaction_type.ex

Include the TokenId description in GraphQL Schema.
Fixes #492
Documentation Update
N/A

Documentation Update in GraphQL #492

---

lib/archethic/bootstrap/transaction_handler.ex
lib/archethic/reward.ex

Addition of Inherit Constraints to Network Transactions
Fixes #422
Manual Tested. No tests required

Addition of Inherit Constraints to Network Transactions #422

---

lib/archethic/contracts/contract/constants.ex
lib/archethic/contracts/interpreter.ex
lib/archethic/contracts/interpreter/transaction_statements.ex
lib/archethic/db/embedded_impl/encoding.ex
lib/archethic/mining/standalone_workflow.ex
lib/archethic/utils/regression/playbooks/smart_contract.ex
test/archethic/contracts/interpreter_test.exs
test/archethic/contracts/worker_test.exs
test/archethic/contracts_test.exs

Fix smart contract interpreter to be consistent with the example in the docs

Fix interpreter from examples

---

lib/archethic/p2p/listener_protocol.ex

Whenever a node is bootstrapping , it must reject Request messages .  
ListenerProtocol handles Incoming new messages from other nodes and
no response is processed here.
Connection modules handles this nodes request get messages and
then its response is processed.
Fixes # (#507)
- iex -S mix with multiple nodes
- Any dependent …

Resolves #507 : Start listening P2P connections after complete bootstrap 

---

lib/archethic/oracle_chain/mem_table_loader.ex

Avoid oracle notification during the bootstrap

---

lib/archethic/mining/transaction_context.ex
lib/archethic/reward/scheduler.ex
test/archethic/reward/scheduler_test.exs

Fix reward scheduler issue: index and next address were not correctly calculated in some case
Fix node distribution in mining context when there is few nodes availables

Fix scheduler issue

---

lib/archethic/bootstrap.ex
lib/archethic/bootstrap/network_constraints.ex
lib/archethic/mining/pending_transaction_validation.ex
lib/archethic/oracle_chain.ex
lib/archethic/oracle_chain/mem_table.ex
lib/archethic/oracle_chain/scheduler.ex
lib/archethic/reward.ex
lib/archethic/self_repair/sync.ex
lib/archethic/shared_secrets.ex
test/archethic/mining/pending_transaction_validation_test.exs

Validate previous txn should be of type network only and public key exists in it.
Fixes # (#423)
dependent on #508 #515  …

Resolves: Ensure network transaction type only passed in a network transaction chain#423

---

lib/archethic/mining/pending_transaction_validation.ex
lib/archethic/shared_secrets/node_renewal.ex
lib/archethic/shared_secrets/node_renewal_scheduler.ex
test/archethic/mining/pending_transaction_validation_test.exs
test/archethic/shared_secrets/node_renewal_test.exs

Fix node shared secrets indexing in schedulers
FIx pending validation network last address

Fix node shared secrets schedulers

---

lib/archethic/replication.ex
lib/archethic/telemetry.ex
test/archethic/bootstrap/network_init_test.exs
test/archethic/replication_test.exs
test/archethic/self_repair/sync/transaction_handler_test.exs
test/archethic/self_repair/sync_test.exs

Fix the replication transaction chain (due to regression)

Fix replication transaction chain ordering writing

---

config/config.exs
lib/archethic/mining/standalone_workflow.ex

Provide timeouts for standalone workflow helping to clean mining processes

Add timeout in standalone workflow

---

lib/archethic/beacon_chain/slot_timer.ex
lib/archethic/bootstrap.ex
lib/archethic/metrics/ets_flush.ex
lib/archethic/metrics/metric_supervisor.ex
lib/archethic/oracle_chain/scheduler.ex
lib/archethic/p2p/client/connection.ex
lib/archethic/p2p/client/transport/tcp_impl.ex
lib/archethic/self_repair.ex
lib/archethic/self_repair/sync.ex

Provide some fixes for : 
- connection
- oracle chain schedulers
- performance of metrics aggregation

Some fixes for P2P and OracleChain

---

lib/archethic_web/live/chains/beacon_live.ex
lib/archethic_web/live/explorer/cache.ex
lib/archethic_web/live/explorer_index_live.ex
lib/archethic_web/live/last_ten_transactions.ex
lib/archethic_web/live/top_transactions_component.ex
lib/archethic_web/supervisor.ex
lib/archethic_web/templates/explorer/index.html.leex

Fixes #404
Manual Tested
- I have added tests that prove my fix is effective or …

Add last transactions feed on the homepage #404

---

lib/archethic/crypto/keystore/node/software_impl.ex
lib/archethic/crypto/keystore/shared_secrets/software_impl.ex
test/archethic/crypto/keystore/shared_secrets/software_impl_test.exs

This PR brings secrets wrapping to avoid exposure of the node's seed and node shared secrets seeds in the memory.
By using closures (anonymous functions), the sensitive data is hidden for inspection.
Functions are defined to sign, derive keys securely.

Wrap secrets to blind private keys

---

.tool-versions
assets/package-lock.json
assets/package.json
assets/webpack.config.js
config/dev.exs

Upgrade js dependencies to solve dependabots warnings.
Migrating from webpack v4 to v5
- Dependencies update

Upgrade js dependencies to fix vulnerabilities

---

.github/workflows/ci.yml
.tool-versions
Dockerfile
README.md
lib/archethic/shared_secrets.ex
lib/archethic_web/templates/explorer/index.html.leex
scripts/install.sh

This PR updates elixir to 1.14.1 and OTP to 24.3.4.6.
⚠️ Unfortunately the docker image for this specific combination doesn't exist yet, so a [PR is opened](https://github.com/erlef/docker-elixir/pull/54) to create it.
A few tests to create transactions have been run locally.
- I have performed a self-review of my …

Upgrade elixir to 1.14.1 and otp to 24.3.4.6

---

lib/archethic/p2p/client/connection.ex
lib/archethic/p2p/client/transport/tcp_impl.ex
lib/archethic/p2p/listener.ex

Fix connection module not handling tcp reponse while in disconnected state.
Improve socket connection by adding keepalive and reuseaddr flag

Fix connection

---

lib/archethic/mining/validation_context.ex
test/archethic/mining/validation_context_test.exs

CrossValidation nodes now check the Proof Of Work (public key) is authorized (available in the list of origin public keys). 
Fixes #664 
Breaking change, something that was allowed is not anymore
Integration tests were added
My code follows the style guidelines of this project
I have performed a self-review of my own code
I have commented my code, particularly in hard-to-understand areas
I have made corresponding changes to the documentation
My changes generate no new warnings
I have added tests that prove my fix is effective or that my feature works
New and existing unit tests pass locally with my changes
Any dependent changes have been merged and published in downstream modules

CrossValidation check Proof Of Work is authorized

---

lib/archethic/beacon_chain.ex
lib/archethic/beacon_chain/subset.ex

This PR improve Task's timeout handling to stop the task properly.
Enhancement

Improve Task's timeout handling

---

lib/archethic.ex
lib/archethic/account/mem_tables/token_ledger.ex
lib/archethic/account/mem_tables/uco_ledger.ex
lib/archethic/contracts.ex
lib/archethic/contracts/worker.ex
lib/archethic/db/embedded_impl.ex
lib/archethic/replication.ex
lib/archethic/self_repair.ex
lib/archethic/transaction_chain.ex
test/archethic/bootstrap/network_init_test.exs
test/archethic/bootstrap_test.exs
test/archethic/contracts/worker_test.exs
test/archethic_test.exs

Fixes multiple bugs mainly in replication part to properly store transactions and their last address.

Fix some bugs on sharded transactions

---

lib/archethic/account/mem_tables_loader.ex
lib/archethic/beacon_chain/summary.ex
lib/archethic/beacon_chain/summary_aggregate.ex
lib/archethic/mining.ex
lib/archethic/mining/fee.ex
lib/archethic/replication/transaction_validator.ex
lib/archethic/transaction_chain/transaction/cross_validation_stamp.ex
lib/archethic/transaction_chain/transaction/validation_stamp.ex
lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations/unspent_output.ex
lib/mix/tasks/migrate.ex
test/archethic/db/embedded_impl_test.exs

Remove the upgrades of the protocol version to be cleared before the mainnet launch

Reset protocol version to 1

---

config/prod.exs

Support origin sofware keys with the Uniris's CA

---

config/prod.exs

Change pool addresses

---

lib/archethic/p2p/message.ex

The algorithm while processing the message `%GetTransactionInputs` is not efficient and takes long time, so the sender of the message fall in timeout.
This PR improve the algorithm
Run the message with an account of 6500 inputs takes average of 10 seconds
With the update it takes few millisecond
- Any dependent changes have been merged and …

Improve calculation time while getting inputs

---

lib/archethic/beacon_chain/summary_aggregate.ex

Fix a bug while aggregating a summary aggregate without availability adding time.
This bug is caused when the function `BeaconChain.fetch_and_aggregate_summary` do not retrieve any beacon summary, by default it create an empty summary aggregate with en empty list of availability adding time.
So when aggregating this empty summary aggregate, a nil value is passed to the trunc function which cause crashes
Fixes #787 
- I have added tests that prove my fix is effective or that …

Fix truncate on nil value

---

lib/archethic.ex
lib/archethic/contracts/interpreter/library.ex
lib/archethic/db.ex
lib/archethic/db/embedded_impl.ex
lib/archethic/db/embedded_impl/chain_index.ex
lib/archethic/db/embedded_impl/chain_reader.ex
lib/archethic/oracle_chain/scheduler.ex
lib/archethic/p2p/message.ex
lib/archethic/p2p/message/genesis_address.ex
lib/archethic/p2p/message/get_genesis_address.ex
lib/archethic/transaction_chain.ex
lib/archethic_web/controllers/api/origin_key_controller.ex
lib/archethic_web/controllers/faucet_controller.ex
lib/archethic_web/live/chains/oracle_live.ex
lib/archethic_web/live/chains/transaction_live.ex
test/archethic/bootstrap/network_init_test.exs
test/archethic/bootstrap_test.exs
test/archethic/contracts/interpreter/action_test.exs
test/archethic/contracts/interpreter/condition_test.exs
test/archethic/db/embedded_impl_test.exs
test/archethic/replication/transaction_context_test.exs
test/archethic/replication_test.exs
test/archethic/self_repair/self_repair_test.exs
test/archethic/self_repair/sync/transaction_handler_test.exs
test/archethic/self_repair/sync_test.exs
test/archethic_test.exs
test/archethic_web/controllers/faucet_controller_test.exs
test/archethic_web/graphql_schema_test.exs
test/support/template.ex

This PR provide some refactor in the DB, to remove and enhance functions.
Also permit to retrieve a chain and a chain size from the DB based on a genesis address.
Also remove the limit address while retrieving a chain from DB, now it always return 10 transactions or transaction until the end of the file
- Improvement 
Updated some unit tests
- New and …

Refactor DB plus some optimization on explorer

---

lib/archethic/application.ex
lib/archethic/mining.ex
lib/archethic/mining/distributed_workflow.ex
lib/archethic/mining/standalone_workflow.ex
lib/archethic/mining/validation_context.ex
lib/archethic/p2p/client/connection.ex
lib/archethic/p2p/listener_protocol.ex
lib/archethic/p2p/message.ex
lib/archethic/p2p/message/acknowledge_storage.ex
lib/archethic/p2p/message/notify_replication_validation.ex
lib/archethic/p2p/message/replicate_pending_transaction_chain.ex
lib/archethic/p2p/message/validate_transaction.ex
lib/archethic/p2p/message_envelop.ex
lib/archethic/replication.ex
lib/archethic/replication/supervisor.ex
lib/archethic/replication/transaction_pool.ex
lib/archethic/utils/regression/benchmarks/p2p_message.ex
test/archethic/mining/distributed_workflow_test.exs
test/archethic/mining/standalone_workflow_test.exs
test/archethic/p2p/client/connection_test.exs
test/archethic/p2p/messages_test.exs
test/archethic/replication/transaction_pool_test.exs
test/archethic/replication_test.exs
test/archethic_web/graphql_schema_test.exs

Improve atomic commitment replication

---

lib/archethic/contracts/loader.ex
lib/archethic/contracts/worker.ex
test/archethic/contracts/worker_test.exs

Initialization wasn't working due to the transactions that were not entirely filled.
Fixes #825
Tested with this scenario: 
1. Start 3 nodes
2. Create SC
3. Restart nodes 
4. Trigger the SC

Fix SC workers initialization

---

lib/archethic_cache/lru.ex

LRU: use genserver

---

lib/archethic/contracts/interpreter/action.ex
lib/archethic_web/live/settings_live.ex

small cleanup. That clause never match,

SC: action: remove obsolete clause

---

lib/archethic.ex
lib/archethic/beacon_chain/slot_timer.ex
lib/archethic/bootstrap.ex
lib/archethic/networking/scheduler.ex
lib/archethic/oracle_chain/scheduler.ex
lib/archethic/p2p/listener.ex
lib/archethic/pub_sub.ex
lib/archethic/reward/scheduler.ex
lib/archethic/self_repair.ex
lib/archethic/self_repair/scheduler.ex
lib/archethic/self_repair/sync.ex
lib/archethic/shared_secrets/node_renewal_scheduler.ex
lib/archethic_web/channels/user_socket.ex
lib/archethic_web/endpoint.ex
test/archethic/beacon_chain/slot_timer_test.exs
test/archethic/db/embedded_impl/chain_index_test.exs
test/archethic/oracle_chain/scheduler_test.exs
test/archethic/pub_sub_test.exs
test/archethic/reward/scheduler_test.exs
test/archethic/self_repair/scheduler_test.exs
test/archethic/shared_secrets/node_renewal_scheduler_test.exs
test/test_helper.exs

Fixes #871 
- Unit tests
-  Simulated manual tests …

Restart self repair when it crashes

---

lib/archethic/p2p/message/first_transaction_address.ex
lib/archethic/p2p/message/genesis_address.ex
lib/archethic/p2p/message/get_first_transaction_address.ex
lib/archethic/p2p/message/get_genesis_address.ex
lib/archethic/transaction_chain.ex
test/archethic/bootstrap/network_init_test.exs
test/archethic/bootstrap_test.exs
test/archethic/contracts/interpreter/legacy/action_interpreter_test.exs
test/archethic/contracts/interpreter/legacy/condition_interpreter_test.exs
test/archethic/contracts/interpreter/legacy/library_test.exs
test/archethic/contracts/interpreter/library/common/chain_test.exs
test/archethic/p2p/message/first_transaction_address_test.exs
test/archethic/p2p/message/get_first_transaction_address_test.exs
test/archethic/replication/transaction_context_test.exs
test/archethic/transaction_chain_test.exs
test/archethic_web/controllers/faucet_controller_test.exs
test/archethic_web/graphql_schema_test.exs

Add conflict resolution to `fetch_first_transaction_address_remotely` and `fetch_genesis_address_remotely`.
Fixes #942
Added the unit tests required

Add conflict resolution to 2 functions of the TransactionChain module

---

test/archethic_web/graphql_schema_test.exs

Fixes some test that was in error sometimes.
Also fix the goal of the test that were not accurate
Unit tests

Fix graphql beacon summary test

---

lib/archethic/contracts/worker.ex

When a contract did not produce a new transaction, the log in console was `Contract execution failed`. Which was wrong.
Log improvment
manually

Smart Contracts: Improve logs of contracts that do not produce a next transaction

---

lib/archethic/oracle_chain/services/uco_price/providers/coin_marketcap.ex

Fix the CoinMarketCap provider.
- remove referer
- use TaskSupervisor
- handle non-200 http code
Fixes #1017 
Manual tests

Fix the CoinMarketCap provider

---

lib/archethic/oracle_chain/services/uco_price/providers/coin_marketcap.ex

CoinMarketCap is currently chaning their UI. There is probably some A/B testing going on. 
Here's an updated version of the scraper which handle both.
Fixes #1021
Manual test (got lucky and for the same oracle I got both UI)
```
2023-05-10 15:35:07.488 [debug] CoinMarketCap UI v1
2023-05-10 15:35:07.498 [debug] CoinMarketCap UI v2
2023-05-10 15:35:07.506 [debug] [pair: "eur", price: 0.06275]
2023-05-10 15:35:07.519 [debug] [pair: "usd", price: 0.06888]
```
- I have added …

UCO price provider: Handle the 2 UI of CoinMarketCap

---

lib/archethic/bootstrap/transaction_handler.ex
lib/archethic/networking/scheduler.ex
test/archethic/bootstrap/transaction_handler_test.exs
test/archethic/bootstrap_test.exs

This PR fixes an issue when an already authorized and available node restarts and send a new node transaction. In this case the P2P view was updated, but not all the other module as Crypto that does not update the last public key if the node.
Now it replicates completely the transaction
- Any dependent changes have been merged and published …

Replicate complete transaction, not only in P2P

---

lib/archethic/contracts.ex
lib/archethic/contracts/interpreter.ex
test/archethic/contracts/interpreter_test.exs
test/archethic/contracts/worker_test.exs

Conditions inherit are now optional.
Fixes #945 
Unit tested and tested manually with 3 scenarios:
1. no inherit condition
2. inherit condition that validates the next transaction
3. empty inherit condition that closes the chain

Smart Contracts: Optional inherit condition block

---

lib/archethic/transaction_chain.ex
test/archethic/transaction_chain_test.exs

**Base branch is testnet**
Fixes #1061
Unit tests added to the suite

Fx fetch_contract_calls conflict resolver

---

lib/archethic/beacon_chain/subset.ex

There was a typing issue on the code_change
hot reload

Fix Subset's code_change

---

config/prod.exs

Base branch: master
```60*60*24*15=1296000```

Out of sync threshold 15days

---

lib/archethic/beacon_chain.ex

in `BeaconChain.fetch_and_aggregate_summaries` there where 2 nested Task.async. This increase the risk of getting timeout.
To reduce this risk, the chunk by addresses is done before creating a task and there is only one task per `{node, chunked addresses}`
Fixes #1077 
Unit test still passes, running multiple node with benchmark
- Any …

Improve fetch summaries timeout

---

lib/archethic/contracts/interpreter/library/common/string.ex
test/archethic/contracts/interpreter/library/common/string_test.exs

Add 3 functions: 
1. String.to_hex/1
2. String.to_uppercase/1
3. String.to_lowercase/1
Fixes #1086 
Unit tested

Smart Contracts: String.to_hex/1, String.to_uppercase/1, String.to_lowercase/1

---

lib/archethic/contracts/interpreter.ex
test/archethic/contracts/interpreter_test.exs

To differentiate string looking like hexadecimal and real hexadecimal, we can now use `0xbaba` format.
During the `sanitize_code` function we convert `0xabc123def` to `"ABC123DEF"`
Unit tests

Add 0x hex format

---

lib/archethic.ex
lib/archethic/contracts.ex
lib/archethic/contracts/contract/context.ex
lib/archethic/contracts/interpreter.ex
lib/archethic/contracts/worker.ex
lib/archethic/mining.ex
lib/archethic/mining/distributed_workflow.ex
lib/archethic/mining/standalone_workflow.ex
lib/archethic/mining/validation_context.ex
lib/archethic/p2p/message/new_transaction.ex
lib/archethic/p2p/message/start_mining.ex
lib/archethic/p2p/message/validate_smart_contract_call.ex
lib/archethic/replication/transaction_validator.ex
lib/archethic/transaction_chain/transaction/validation_stamp.ex
test/archethic/contracts/contract/context_test.exs
test/archethic/contracts/interpreter/library/common/time_test.exs
test/archethic/contracts/interpreter_test.exs
test/archethic/contracts/worker_test.exs
test/archethic/contracts_test.exs
test/archethic/p2p/message/validate_smart_contract_call_test.exs
test/archethic/p2p/messages_test.exs

Validators used to only check the inherit condition. Now they actually execute the code of previous transaction and compare it to current transaction. This ensure the transaction is legitimate.
Fixes #925
Unit tested + Tested with 3 nodes.

Smart Contracts: Validation workflow refactor

---

.credo.exs
lib/archethic/p2p/client/connection.ex
lib/archethic/telemetry.ex
lib/archethic_web/endpoint.ex

Passes all telemetry in millisecond to be consistent
Fixes some metric name inconsistency
Allow request on /metrics even if node is not bootstrapped yet

Fix telemetry

---

lib/archethic/contracts/interpreter/condition_interpreter.ex
test/archethic/contracts/interpreter/condition_interpreter_test.exs

Parser will check the condition fields are valid
Fixes #1079
Unit tested & test with simple scenario: 
```
@version 1
condition inherit: [ foo: true ]
```
Transaction refused: `Smart contract invalid "invalid condition field: foo - condition - L2"`

Smart Contracts: check condition fields are valid

---

lib/archethic/mining/distributed_workflow.ex

When a mining timeout is reached, if the node already received some replication confirmations, it means the transaction was fully validated but some replication nodes didn't respond with storage confirmations.
In this case we still notify the beacon chain with received confirmations and also notify previous chain.
Fixes #943 
Started 4 nodes, updated the code of one as so it does not respond to the message `ReplicationPendingTransactionChain` when the transaction is type of :transfer
Send multiple transaction with few UCO to have the case a node received only one of 2 expected confirmations. (faucet is not working as it elected the 4 nodes for validation)
Log "Didn't received all confirmations before mining timeout" appeared
- My code …

Send received confirmations on mining timeout

---

lib/archethic/utils/regression/playbook.ex

This PR updates the playbook to add a new function that gets the transaction fee for https://github.com/archethic-foundation/smart-contract-playground/issues/17
Tested locally

Add get_transaction_fee to playbook

---

lib/archethic/mining/transaction_context.ex

On mainnet we can see that some cross validation nodes do not have the time to send the mining context to the coordinator before the 3ms of timeout.
This can be explained due to high latency but also the way a node retrieve the context.
Currently a node fetch the previous transaction and the p2p view concurrently and then fetch the utxos.
This is improved by fetching the utxos concurrently with other fetch.
Also fixed the timestamp of transaction fetching …

Optimize context retrieving

---

lib/archethic/contracts.ex
lib/archethic/utils/regression/playbook.ex
test/archethic/contracts_test.exs

2 bugfixes while working on playground:
1. Contract validation was wrong resulting in the possibility to overwrite a contract
2. Encode16 the content when calling the API
Tested while working on the playground

Fix contract validation & Playbook.tx_to_json

---

scripts/test-release.sh

1. Avoid to do `mix distillery.release` 2 times (1 for each node)
2. Unpack the release in the prepare

Improve test-release.sh

---

lib/archethic/contracts/interpreter/library/common/chain.ex
lib/archethic/contracts/interpreter/library/common/chain_impl.ex
test/archethic/contracts/interpreter/library/common/chain_test.exs

Add new function in smart contract library to get the burning address

Add new library function Chain.get_burn_address

---

lib/archethic.ex
lib/archethic/contracts.ex
lib/archethic/contracts/interpreter.ex
lib/archethic/contracts/interpreter/scope.ex
lib/archethic_web/api/ecto_schemas/function_call_payload.ex
lib/archethic_web/api/jsonrpc/controllers/jsonrpc_controller.ex
lib/archethic_web/api/jsonrpc/error.ex
lib/archethic_web/api/jsonrpc/method.ex
lib/archethic_web/api/jsonrpc/methods/call_contract_function.ex
lib/archethic_web/web_utils.ex
test/archethic_web/api/jsonrpc/error_test.exs
test/archethic_web/api/jsonrpc/methods/call_contract_function_test.exs

Allows to call a smart contract public function through the Json RPC api
Tested new rpc methods and errors

Rpc function call

---

lib/archethic/contracts.ex
lib/archethic/contracts/interpreter.ex
lib/archethic/contracts/interpreter/action_interpreter.ex
lib/archethic/contracts/interpreter/library/common/time.ex
lib/archethic/contracts/interpreter/scope.ex
test/archethic/contracts/interpreter/function_interpreter_test.exs
test/archethic/contracts/interpreter/scope_test.exs
test/archethic/contracts/interpreter_test.exs

Ensures that a user can not overwrite "protected" variables such as time_now or functions
Fixes #1183 
Tested in scope and interpreter

protect private variables

---

lib/archethic/contracts/interpreter/common_interpreter.ex
lib/archethic/contracts/interpreter/condition_interpreter.ex

fix condition kwargs parsing

---

README.md

Add the node requirement within the documentation
Fixes #1229 
- Update documentation to let the user know he has to install npm to use the project locally
-

Add node requirement

---

lib/archethic/contracts.ex
lib/archethic/contracts/interpreter.ex
lib/archethic/contracts/interpreter/function_interpreter.ex
lib/archethic/contracts/interpreter/scope.ex
mix.exs
test/archethic/contracts/interpreter/scope_test.exs

Functions were failing with map parameters.
Fixes #1257 
Unit tests & playground

Fix functions with map params

---

lib/archethic/beacon_chain/subset/summary_cache.ex

this was live on testnet since 12/09

Fix the ETS table before iterating on it to avoid 'invalid continuation'

---

lib/archethic/contracts/interpreter/library/common/math.ex
test/archethic/contracts/interpreter/library/common/math_test.exs

Add new Smart Contract module `Math`. It provide these functions:
- trunc
- pow
- sqrt
- rem
Tested with doctest and manual test through playground

Add SC Math module

---

config/dev.exs
lib/archethic/contracts/interpreter/library/common/http.ex
lib/archethic/contracts/interpreter/library/common/http_impl.ex
test/archethic/contracts/interpreter/library/common/http_impl_test.exs
test/support/mock_server.ex

This PR allow users to make request with POST / PUT / DELETE / PATCH request method.
They can also make their own headers
Unit tests
Manual test with simple contract

Improve SC HTTP to use POST request

---

lib/archethic/bootstrap/network_init.ex
lib/archethic/contracts/worker.ex
lib/archethic/mining.ex
lib/archethic/mining/distributed_workflow.ex
lib/archethic/mining/fee.ex
lib/archethic/mining/smart_contract_validation.ex
lib/archethic/mining/standalone_workflow.ex
lib/archethic/mining/validation_context.ex
lib/archethic/p2p/message/replicate_transaction.ex
lib/archethic/p2p/message/smart_contract_call_validation.ex
lib/archethic/p2p/message/validate_smart_contract_call.ex
lib/archethic/p2p/message/validate_transaction.ex
lib/archethic/replication.ex
lib/archethic/replication/transaction_validator.ex
lib/archethic_web/api/jsonrpc/methods/estimate_transaction_fee.ex
lib/archethic_web/api/rest/controllers/transaction_controller.ex
test/archethic/mining/distributed_workflow_test.exs
test/archethic/mining/fee_test.exs
test/archethic/mining/smart_contract_validation_test.exs
test/archethic/mining/validation_context_test.exs
test/archethic/p2p/message/validate_smart_contract_call_test.exs
test/archethic/replication/transaction_validator_test.exs
test/archethic/replication_test.exs
test/support/transaction_factory.ex

This PR implement a new way to calculate fee for the smart contract:
- If a user trigger a contract => user pay additional fee, contract execution is free
Unit test + manual test
Create a contract with trigger on transaction, trigger this contract. The trigger transaction should have more fees and the contract tx should be free
- Any …

User pay contract fee

---

lib/archethic/metrics/poller.ex

This changes aims to reduce the bandwidth consumption during the bootstrap time
- Enhancements
When you start a node, the metrics poller would be actived after the end of the bootstrap.
This log should be present:
```
Metric poller scheduler started
```

Start the metrics poller once the bootstrap is done

---

lib/archethic_web/api/graphql/schema/resolver.ex

Fix bug in the version GraphQL API to retrieve the code's version

Fix GraphQL API to get the code's version

---

lib/archethic/db/embedded_impl/encoding.ex
lib/archethic/p2p/message/get_unspent_outputs.ex
lib/archethic/p2p/message/unspent_output_list.ex
lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations/unspent_output.ex
lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations/versioned_unspent_output.ex
lib/archethic/transaction_chain/transaction_summary.ex
lib/archethic_web/explorer/live/transaction_details_live.ex

Fixes some serialization issue on State utxo with bitstring over binary
Tested using mutliple contract with state on multiple nodes

Fix serialization issue on state utxo

---

rel/config.exs
rel/vm.args
scripts/install.sh
scripts/release.sh

Scripts now takes arguments so we can deploy both testnet & mainnet on the same machine.
Also change the version of TPM2-TSS because the version was removed from Github 🤦

Scripts now takes arguments (testnet vs mainnet)

---

lib/archethic/utils.ex
test/archethic/utils_test.exs

Utils.run_exclusive doesn't not send messages anymore

---

lib/archethic/transaction_chain.ex
test/archethic/transaction_chain_test.exs

Fix an issue where the TransactionChain.fetch function could return an invalid result when data are fetched from DB and Remote

Fix paging state

---

lib/archethic_web/explorer/live/transaction_details_live.html.heex

Fix issue when there is a movement of a token that is minted in the same transction.
Tested manually. 
Test file: 
```yaml
{
"supply": 10000000000,
"type": "fungible",
"decimals": 8,
"name": "COINCOIN",
"symbol": "CC",
"allow_mint": true,
"recipients": [{"to": "00002223BBD4EC3D64AE597696C7D7ADE1CEE65C639D885450AD2D7B75592AC76AFA", "amount": 33}],
"aeip": [2, 18, 19]
}
``` …

Explorer: TransactionDetails page bugfix

---

lib/archethic_web/explorer/live/transaction_details_live.ex

Fixes the token properties of UTXO that where not retrieved
Created a transaction with multiple token UTXO

Fix utxo token properties on explorer

---

lib/archethic_web/explorer/live/node_details_live.html.heex

Add a button to open the node's explorer

---

lib/archethic/transaction_chain.ex
test/archethic/transaction_chain_test.exs

Fix issue that made the transaction to be entirely resynced in some cases.
Fixes #1388 
- 
Patched a testnet node and added unit test

Fix regression in TransactionChain.fetch

---

test/archethic/beacon_chain/subset/stats_collector_test.exs

Those tests were often randomly failing.

StatsCollector: fix flaky tests

---

lib/archethic.ex
lib/archethic/bootstrap.ex
lib/archethic/bootstrap/network_init.ex
lib/archethic/mining/distributed_workflow.ex
lib/archethic/mining/standalone_workflow.ex
lib/archethic/networking/scheduler.ex
lib/archethic/p2p/message/replicate_pending_transaction_chain.ex
lib/archethic/p2p/message/replicate_transaction.ex
lib/archethic/replication.ex
lib/archethic/replication/transaction_context.ex
lib/archethic/self_repair.ex
lib/archethic/self_repair/network_chain.ex
lib/archethic/self_repair/repair_worker.ex
lib/archethic/self_repair/sync/transaction_handler.ex
lib/archethic/utxo.ex
test/archethic/bootstrap_test.exs
test/archethic/p2p/messages_test.exs
test/archethic/replication/transaction_context_test.exs
test/archethic/replication_test.exs
test/archethic/self_repair/network_chain_test.exs
test/archethic/self_repair/repair_worker_test.exs
test/archethic/self_repair/self_repair_test.exs
test/archethic/utxo_test.exs

Improve workflow to determine genesis address during replication

Genesis ledger control

---

lib/archethic/self_repair/sync.ex
lib/archethic/self_repair/sync/transaction_handler.ex
lib/archethic/transaction_chain/transaction/validation_stamp/ledger_operations/unspent_output.ex

Fix some issue after AEIP-21 phase 1 development
Running self repair using testnet node bootstrap

Fix aeip 21 bugs

---

lib/archethic.ex
lib/archethic/p2p/message/get_balance.ex
lib/archethic/transaction_chain/transaction_input.ex
lib/archethic/utxo.ex
lib/archethic_web/api/graphql/schema/resolver.ex
test/archethic_test.exs
test/archethic_web/api/graphql/schema_test.exs

Fixes #1412
- Enhancement
Run a node before PR, create some faucet list the inputs of the genesis
Checkout the PR branch, list the inputs it should be the same
Make transaction from this genesis chain
Checkout the AEIP-21 main branch, list the inputs of the genesis and the transaction
Checkout the PR branch, list the inputs of the genesis and the transaction, they should be the same
- Any …

AEIP21-P2: Adapt graphql queries

---

lib/archethic_web/explorer/components/amount.ex
lib/archethic_web/explorer/components/inputs_list.ex
lib/archethic_web/explorer/components/unspent_outputs_list.ex
lib/archethic_web/explorer/live/chains/transaction_chain_live.ex
lib/archethic_web/explorer/live/chains/transaction_chain_live.html.heex
lib/archethic_web/explorer/live/explorer_index_live.ex
lib/archethic_web/explorer/live/transaction_details_live.ex
lib/archethic_web/explorer/live/transaction_details_live.html.heex
lib/archethic_web/explorer/templates/explorer/index.html.heex
lib/archethic_web/web_utils.ex

Fixes #1411
Tested manually by creating a token and sending it to chains. Then check these chains in the explorer.

AEIP21-P2: Display assets balance & unspent outputs in the chain page

---

priv/migration_tasks/prod/1.5.0@aeip_21-2.exs

Fix migration to store inputs as the next address validation inputs

Fix migration to store inputs as the next address validation inputs

---

priv/migration_tasks/prod/1.5.0@aeip_21-2.exs

Fix migration 1.5.0

---

lib/archethic/contracts/loader.ex
lib/archethic/db.ex
lib/archethic/db/embedded_impl.ex
lib/archethic/db/embedded_impl/chain_index.ex
lib/archethic/utils/job_cache.ex
test/support/template.ex

Optimize DB.get_last_chain_address

Optimize Loader init and DB.get_last_chain_address

---

Makefile
lib/archethic/utxo.ex
lib/archethic/utxo/db_ledger/file_impl.ex
lib/mix/tasks/db.ex
rel/commands/db
rel/config.exs

This changes introduces tool to deal with database including cleaning and rebuild utxo entries.
Start a node, make some transactions.
Stop it
Run `mix archethic.db --rebuild-utxo`
The genesis state should be the same as expected.

feat ✨ (db): Add tool to interact with DB + cleaning tasks

---

lib/archethic/mining/smart_contract_validation.ex
lib/archethic/replication/transaction_context.ex

Fix Election for SC Call validation during mining and transaction context in replication

Fix genesis nodes Election for UTXO and SC call

---

lib/archethic/db/embedded_impl.ex
lib/archethic/db/embedded_impl/chain_index.ex
lib/mix/tasks/db.ex

Improve the mix archethic.db --rebuild utxo
- Enhancement
- 

Improve mix archethic.db --rebuild-utxo

---

lib/archethic.ex
lib/archethic/p2p/message/balance.ex
lib/archethic/p2p/message/get_balance.ex
test/archethic/p2p/client/connection_test.exs
test/archethic/p2p/message/get_unspent_outputs_test.exs
test/archethic/p2p/messages_test.exs
test/archethic/transaction_chain_test.exs
test/archethic_test.exs

Add new field `last_chain_sync_date` in message `Balance` to resolve conflict

Add last_chain_sync_date in GetBalance message

---

lib/mix/tasks/db.ex

Improve command rebuild-utxo:
- directly store transaction in ets table to avoid getting it again after
- fetch transaction if it is not available in local

Improve rebuild-utxo task

---

lib/archethic/contracts/worker.ex
lib/archethic/utils/regression/api.ex
lib/archethic/utils/regression/playbooks/smart_contract.ex
lib/archethic/utils/regression/playbooks/smart_contract/counter.ex
lib/archethic/utils/regression/playbooks/smart_contract/deterministic_balance.ex
lib/archethic/utils/regression/playbooks/smart_contract/dex.ex
lib/archethic/utils/regression/playbooks/smart_contract/legacy.ex
lib/archethic/utils/regression/playbooks/smart_contract/uco_ath.ex
lib/archethic_web/api/graphql/schema/resolver.ex

Add new playbook with DEX implementation.
Also fix a bug in worker and in chain unspent output resolver

Add dex playbook

---

lib/archethic/contracts/loader.ex
lib/archethic/contracts/worker.ex
lib/release/parse_contract_code.ex
mix.exs
rel/config.exs

Up version 1.5.0-rc7

---

lib/archethic/contracts.ex
lib/archethic/mining/smart_contract_validation.ex

Fix UTXO with nil from

---

lib/archethic/mining/smart_contract_validation.ex
lib/archethic/transaction_chain/versioned_transaction_input.ex
mix.exs

Fix SC validation timeout

---

lib/archethic/utxo.ex
lib/archethic/utxo/loader.ex
lib/archethic/utxo/memory_ledger.ex
test/archethic/contracts/worker_test.exs
test/archethic/utxo/memory_ledger_test.exs
test/archethic/utxo_test.exs

Improve utxo loading

---

lib/mix/tasks/db.ex

Optimize rebuild utxo command

---

lib/archethic/contracts/loader.ex
lib/archethic/contracts/worker.ex
test/archethic/contracts/worker_test.exs

Fix trigger worker

---

lib/archethic/bootstrap/sync.ex

Do not override first enrolled node on bootstrap

---

lib/archethic/utils/websocket/handler.ex

Fix playbook heartbeat on websocket

---

lib/archethic/db/embedded_impl/chain_index.ex
lib/archethic/db/embedded_impl/chain_reader.ex

Optimize  `ChainIndex.get_tx_entry` by reducing `:file.read` call
Unit test and also manual benchmark

Optimize ChainIndex.get_tx_entry

---

lib/archethic/beacon_chain/slot_timer.ex
lib/archethic/beacon_chain/subset.ex
lib/archethic/beacon_chain/subset/summary_cache.ex
lib/archethic/beacon_chain/summary_timer.ex
lib/archethic/mining/distributed_workflow.ex
lib/archethic/replication/transaction_pool.ex
lib/archethic/self_repair/repair_worker.ex
lib/archethic/self_repair/scheduler.ex
lib/release/restart_telemetry.ex
mix.exs

Release 1.5.1 rc1

---

assets/css/app.scss
assets/css/explorer.scss
assets/js/app.js
assets/webpack.config.js
lib/archethic_web/explorer/live/code_viewer_live.ex
lib/archethic_web/explorer/live/code_viewer_live.html.heex
lib/archethic_web/explorer/live/transaction_details_live.html.heex
lib/archethic_web/explorer/views/explorer_view.ex

Fix code highlight issue on code viewer and add code highlight on transaction details

Code highlight

---

assets/js/metric_config.js

Display yaxis in S instead of MS to reflect real-world values.
1st commit is just auto format

Dashboard Y-axis in second

---

lib/archethic/bootstrap.ex
lib/archethic/self_repair.ex

Fix some bootstrap issues

---

lib/archethic/contracts/interpreter/library/common/list.ex

Add 2 functions to the `List` module

Smart Contracts: Add `List.reverse/1` and `List.sort/1`

---

lib/archethic/crypto/keystore/node/software_impl.ex
lib/archethic/crypto/keystore/shared_secrets/software_impl.ex
lib/archethic/p2p/mem_table.ex

Remove unused function for 1.5.9 migration

Remove 1.5.9 migration function

---

lib/archethic/p2p/client/connection.ex
lib/archethic/p2p/listener_protocol.ex

stop the listener when closing the socket

---

lib/archethic/p2p.ex

Refactor P2P.quorum to avoid executing acceptance resolver multiple time

refactor quorum to run acceptance resolver once

---

.tool-versions
assets/package-lock.json
assets/package.json

Update node to latest LTS version
Also update assets npm package dependencies.

Update node version and dependencies version

---

lib/archethic/contracts.ex
lib/archethic/contracts/contract/state.ex
lib/archethic/mining/smart_contract_validation.ex
lib/archethic/p2p/message/validate_smart_contract_call.ex
test/archethic/contracts_test.exs
test/archethic/oracle_chain/services/hydrating_cache_test.exs
test/archethic_test.exs

Update Smart contract state maximum size from 256 KB to 3 MB
Update Smart contract default execution timeout from 5s to 15s

Update sc stats

---

lib/archethic/transaction_chain/transaction/data/contract.ex
lib/archethic_web/api/graphql/schema/transaction_type.ex
priv/json-schemas/schemas/object/contract.json

Fixes some issue with transaction V4
- Allow "null" as contract value in json schema
- Prohibit additional properties in contract manifest
- Update graphql doc with Contract field

Transaction V4 API fixes

---

mix.exs

Bump to v1.7.0 to fix migrations.

Up version 1.7.0

---

lib/archethic/p2p/client/connection.ex

Fixes an issue where a connection could close but still receiving timeout event which was not handled

Fix function clause on request timeout in connection

---

scripts/install.sh

Set asdf to version 0.15.0, new version is a complete breaking change

Set asdf install to 0.15.0

---

.github/workflows/ci.yml

Update ubuntu 22.04
